### ISSUE TITLE
[messbox] propogates "paste" (ctrl-v) events to patch

### ISSUE THREAD

**Issue by sebshader** [porres/pd-else#1013]
I believe the expected behavior is only to paste from the clipboard into [messbox]
however, currently ctrl-v also propagates to the patch window, which also puts pd into edit mode, among other things.
Here's one way to test:
1. copy some text into the clipboard
2. select a pd object in edit mode and copy (ctrl-c)
3. put cursor into [messbox]
4. hit ctrl-v

the text will be pasted into [messbox], but the object that was selected will be copy-pasted as well.
I think perhaps the tcl "break" message has to be used in some binding to avoid propagating the event (perhaps in conjunction with the "bindtags" command)
the way might be to put the individual widget binding after the Text class binding with "bindtags", and then call "break" in the individual widget's binding for ctrl-v I think

It also seems like the text widget always retains the keyboard focus, instead of the focus going back to the patch window at some point. In order to be able to use ctrl-v in the patch that [messbox] is in after the above change is made that might also have to be fixed/changed.

**Comment by porres** [comment]
you know, I stole this from some object and I really have no much idea on how to deal with tcl/tk yet. You seem like a good tcl.tk master and I'd really appreciate if you could help me with this one :)

**Comment by sebshader** [comment]
@porres ok I'll try to pr sometime
