### ISSUE TITLE
display object not working

### ISSUE THREAD

**Issue by Drugo23** [porres/pd-else#1041]
When I send any message/number/list the object blinks and outputs the message but doesn’t display anything. Display~ is working properly though. I’m using the latest release of ELSE (it was working properly on other releases) and pd. I’m on Windows 10.

**Comment by porres** [comment]
this is hard because I can't reproduce it,
and it's an abstraction, so maybe one object is not working for windows, but  have no idea which

**Comment by porres** [comment]
could you try and do some debugging on this? You have version 40 now?

**Comment by Drugo23** [comment]
It seems that there is an issue with the router object. if I just open the abstraction, I have no messages coming from any of the router outlets, but if I make a new router object in the same spot, patched as it was before, it works.

**Comment by porres** [comment]
I think it's a problem with your installation, if you're loading an earlier version of [router], then it won't work. So you have to fix this, delete the old one you're loading somehow
