### ISSUE TITLE
Note2pitch not working

### ISSUE THREAD

**Issue by Drugo23** [porres/pd-else#1042]
When I send note names such as C4 the console says “list fromsymbol: no method for C4” and the object doesn’t output anything. I’m using the latest ELSE release (it was working on beta 38) and pd. I’m on Windows 10

**Comment by porres** [comment]
this is hard because I can't reproduce it,
and it's an abstraction, so maybe one object is not working for windows, but  have no idea which

**Comment by porres** [comment]
could you try and do some debugging on this? You have version 40 now?
