### ISSUE TITLE
Problem with [presets] in combination with [sequencer]

### ISSUE THREAD

**Issue by bazilmuzik** [porres/pd-else#1049]
I think the issue is quite self-understandable from the patch attached. But in short, using the [set< message with | as barlines does something wierd... Or it's the fact that [presets] adds automatically || at the end of the line that messes things up, I don't know...

[presets_ISSUE.zip](https://github.com/porres/pd-else/files/6641347/presets_ISSUE.zip)

**Comment by porres** [comment]
hmm, I see what I did there

**Comment by porres** [comment]
hmmm, I see what I did there...

**Comment by porres** [comment]
closed by https://github.com/porres/pd-else/commit/3a8314c33a8110ba80f37d9a1c491cebd58c9bef
