### ISSUE TITLE
Pd explodindo com [presets]

### ISSUE THREAD

**Issue by emviveros** [porres/pd-else#1057]
Quando o [presets] tem argumento utilizado mais de uma vez ele explode

https://user-images.githubusercontent.com/3089536/123811974-1a3b0100-d8ca-11eb-9ec7-8dc05ad47fa5.mov

[patchs_pd_explode.zip](https://github.com/porres/pd-else/files/6733966/patchs_pd_explode.zip)

**Comment by emviveros** [comment]
Simplifiquei ainda mais o patch e agora não explode, mas retorna um erro:
```error
clone: instance number 1 out of range
```

[mais_simples.pd.zip](https://github.com/porres/pd-else/files/6734320/mais_simples.pd.zip)

**Comment by porres** [comment]
explode pq vc tá chamando um receive que tá ligado numa abstração e isso não pode

o outro erro é conhecido e rola quando vc só tem um endereço e é outra coisa

**Comment by porres** [comment]
> o outro erro é conhecido e rola quando vc só tem um endereço e é outra coisa

na real é pq vc tem o receive repetido (o que não faz sentido, na real e deve ser evitado) e apenas um argumento

**Comment by emviveros** [comment]
Não sabia disso.. Então como se faz? usando [value]?

**Comment by porres** [comment]
tem que ligar num objeto compilado qualquer que recebe um bang e cospe alguma coisa

**Comment by emviveros** [comment]
> o outro erro é conhecido e rola quando vc só tem um endereço e é outra coisa

Como assim? Tem um endereço e é outra coisa?

**Comment by porres** [comment]
> Como assim? Tem um endereço e é outra coisa?

tem um endereço (argumento), ele tá referenciado repetidamente em dois receives (o que vc não devia fazer) e é outra coisa (outro problema, outra questão, outro issue não relacionado)
