### ISSUE TITLE
gain~ have to save if I modify mode

### ISSUE THREAD

**Issue by raynovich** [porres/pd-else#1069]
Hey all,
In the gain~ function, if I set the mode then I have to save the object.  Is this intended?  I was looking to see why this was and could not figure it out.

**Comment by porres** [comment]
yes, it's intentional and this works in the same way as other GUIs in Pd. If you change the color of a bang via messages, you need to save the patch so the changes are saved

**Comment by raynovich** [comment]
Thanks for the quick response.  Sorry if I am asking ignorant questions.   Is the intent to use only quadratic scaling?  I am trying to use db scaling and setting mode 1.  

I may not have asked the question clearly. 

I have an object that I am using your gain~ object.  In my object I am setting the mode to |mode 1( upon starting my new object.  I have multiple objects using gain~.  When I try to close my patch, the system requires me to save a subpatch which has gain~.  

To me honestly, this seems unnecessary.  

Also, I have been trying to figure out how to use your five variables correctly in the function.

gain~ $1 $2 $3 $4 $5.

I think $2 is the mode, but when I put a number other than 0 no sound comes out.  

Again, I am using your gain~ object with success.  It is nice.  I would love to understand better.

William

**Comment by porres** [comment]
I think I found and fixed the bug, try it

**Comment by raynovich** [comment]
Hello,
I am not sure the system is doing what I want it to do, but I think it was TOTALLY my fault.  Well maybe not.  That being said, I downloaded the newest update and so far so good.

The issue is that when you change the mode you HAVE to resave.  That makes sense, but I was not thinking correctly.  The system does seem to remember the past mode.

Hope that makes sense,
William
