### ISSUE TITLE
[midi] can't reach end of track

### ISSUE THREAD

**Issue by MikeMorenoDSP** [porres/pd-else#1070]
[midi] object skips the empty space at the end of the midi file, not respecting the length of the clip.

Here, I highlighted the space that is being skipped at the end.

![image](https://user-images.githubusercontent.com/3298036/132104237-f262c76e-80f6-4bea-871c-ca027f483497.png)

And, here's a screen capture of the looped audio vs the looped midi.
I'm using the midi-seq.mid example from the library.

![image](https://user-images.githubusercontent.com/3298036/132104289-58e6655c-8e91-41eb-8c84-e098ac25e030.png)

Any advice?

**Comment by porres** [comment]
same happens for cyclone/seq, right?

**Comment by styk-tv** [comment]
i just tested on latest else-midi, cyclone-seq and the end of clip is equivalent with the end of the last note. i tried to artificially update end of track in midi file to correspond with end of 4 bars (above example plays twice) hence clear shift error. immediate start of second track repetition is directly attached to the end of the last node from the previous one.

@porres what would be your suggestion to tell else-midi to loop to a track end? if it cannot be done using midi message maybe directly in pd?

I also found this in midi specification:
![Screenshot 2021-09-05 at 09 39 27](https://user-images.githubusercontent.com/838921/132124193-ce49a47b-4eae-4e18-af22-d8e2dec61638.png)

**Comment by porres** [comment]
I bet that the late Marin Peach's [midifile] object deals nicely with this as it is much more sophisticated. I see the "End of track" case being treated in the line 681 of its source code downloaded from deken (btw, 2F = 47).

**Comment by styk-tv** [comment]
Thanks for the tip Alex.

RIP Mr Peach

**Comment by porres** [comment]
> Is else/midi considered supporting MIDI 1 types or only MIDI 0?

I dunno, I'm basically just stealing this from cyclone/seq and I don't how that deals with this.

> Could anyone confirm end-of-track can be forced to a position that is not the end of last note in a way that it would be respected by a current else/midi or even cyclone/seq implementations?

how can one do that? I don't have a MIDI editor that shows all these raw data.  I once used a MIDI editor that would show me tempo in BPM, bar signs, tracks, lots of stuff, and also the raw data. Can’t remember what it was though…

can you guys give me a simple MIDI file with a couple of monophonic notes into a single track, that is with minimal information, and then a pause withthe "end of track" specification? Just so I can test it...

**Comment by styk-tv** [comment]
<img width="950" alt="Screenshot 2021-09-05 at 23 07 37" src="https://user-images.githubusercontent.com/838921/132143004-e14c2155-5b2d-4af6-b55f-7cc760a63fff.png">

<img width="903" alt="Screenshot 2021-09-05 at 23 23 43" src="https://user-images.githubusercontent.com/838921/132143007-eceeafa5-f303-430c-83de-8942517cc9f4.png">

mid file is zipped as github did not like .mid extension
[one-bar-4x-8th-notes.mid.zip](https://github.com/porres/pd-else/files/7112446/one-bar-4x-8th-notes.mid.zip)

**Comment by porres** [comment]
how do you assemble midi files manually?

here's what  I get when opening your file with sublime text editor

4d54 6864 0000 0006 0000 0001 0060 4d54
726b 0000 0039 00ff 0301 0000 ff58 0404
0224 0800 ff58 0404 0224 0800 903c 6430
803c 4030 9043 6430 8043 4030 9040 6430
8040 4030 903e 6430 803e 4000 ff2f 00

> Can’t remember what it was though…

It was something like this https://jeffbourdier.github.io/midiopsy/ but for macOS

this one seems to do the job, but not free/open source https://www.canato.se/my_home/ and I couldn't even open the trial version

**Comment by styk-tv** [comment]
I updated endOfTrack message and recreated the midi file. new file zipped is here.
[one-bar-4x-8th-notes.384.mid.zip](https://github.com/porres/pd-else/files/7112491/one-bar-4x-8th-notes.384.mid.zip)

py-midicsv output
```
0, 0, Header, 0, 1, 96
1, 0, Start_track
1, 0, Title_t, "\000"
1, 0, Time_signature, 4, 2, 36, 8
1, 0, Time_signature, 4, 2, 36, 8
1, 0, Note_on_c, 0, 60, 100
1, 48, Note_off_c, 0, 60, 64
1, 96, Note_on_c, 0, 67, 100
1, 144, Note_off_c, 0, 67, 64
1, 192, Note_on_c, 0, 64, 100
1, 240, Note_off_c, 0, 64, 64
1, 288, Note_on_c, 0, 62, 100
1, 336, Note_off_c, 0, 62, 64
1, 384, End_track
0, 0, End_of_file
```

And with ToneJs/Midi
```
{
  "header": {
    "keySignatures": [],
    "meta": [],
    "name": "\u0000",
    "ppq": 96,
    "tempos": [],
    "timeSignatures": [
      {
        "ticks": 0,
        "timeSignature": [
          4,
          4
        ],
        "measures": 0
      },
      {
        "ticks": 0,
        "timeSignature": [
          4,
          4
        ],
        "measures": 0
      }
    ]
  },
  "tracks": [
    {
      "channel": 0,
      "controlChanges": {},
      "pitchBends": [],
      "instrument": {
        "family": "piano",
        "name": "acoustic grand piano",
        "number": 0
      },
      "name": "\u0000",
      "notes": [
        {
          "duration": 0.25,
          "durationTicks": 48,
          "midi": 60,
          "name": "C4",
          "ticks": 0,
          "time": 0,
          "velocity": 0.7874015748031497
        },
        {
          "duration": 0.25,
          "durationTicks": 48,
          "midi": 67,
          "name": "G4",
          "ticks": 96,
          "time": 0.5,
          "velocity": 0.7874015748031497
        },
        {
          "duration": 0.25,
          "durationTicks": 48,
          "midi": 64,
          "name": "E4",
          "ticks": 192,
          "time": 1,
          "velocity": 0.7874015748031497
        },
        {
          "duration": 0.25,
          "durationTicks": 48,
          "midi": 62,
          "name": "D4",
          "ticks": 288,
          "time": 1.5,
          "velocity": 0.7874015748031497
        }
      ],
      "endOfTrackTicks": 384
    }
  ]
}
```

You can see now correct value of (track=1 bar=4xPPQ=4x96=384) as on the screenshot. However, it is not respected in else/midi  I have not tested with [midifile] yet. Its past midnight in London.

**Comment by porres** [comment]
here's your new file opened in the sublime text editor

4d54 6864 0000 0006 0000 0001 0060 4d54
726b 0000 0039 00ff 0301 0000 ff58 0404
0224 0800 ff58 0404 0224 0800 903c 6430
803c 4030 9043 6430 8043 4030 9040 6430
8040 4030 903e 6430 803e 4030 ff2f 00

> 4d54 6864 0000 0006 0000 0001 0060 4d54
> 726b 0000 0039 00ff 0301 0000 ff58 0404
> 0224 0800 ff58 0404 0224 0800 903c 6430
> 803c 4030 9043 6430 8043 4030 9040 6430
> 8040 4030 903e 6430 803e 4000 ff2f 00

this was the old one

**Comment by porres** [comment]
> I used these:
> ToneJs/Midi: https://tonejs.github.io/Midi/
> PyMidiCsv: https://pypi.org/project/py-midicsv/
> Ableton11: https://www.ableton.com/en/trial/

I don't think I can deal with ToneJs/Midi & PyMidiCsv. I'm still looking around for that MIDI Editor that showed metadata, events and the whole MIDI stream of a file as raw MIDI and what it meant... you could then edit and play, it was so cool...

**Comment by styk-tv** [comment]
Yes i would prefer that but I don't know any solid ones.

**Comment by porres** [comment]
midifile gives us 384 as the last tick on your file as I did bet so

**Comment by porres** [comment]
I'm moving the discussion to https://github.com/porres/pd-cyclone/issues/557 please join us

**Comment by porres** [comment]
I have a fix for this in [cyclone/seq], see https://github.com/porres/pd-cyclone/issues/557#issuecomment-917020285

please test it @MikeMorenoDSP and @styk-tv

**Comment by porres** [comment]
I'm pretty confident I've fixed this i cyclone, plus I made other improvements, the same are being made to else/midi and ELSE, which will probably be updated sooner. I also added a built in loop function in else/midi, which makes things much more convenient

**Comment by porres** [comment]
This is already part of the new release!
