### ISSUE TITLE
[loop] "couldn't create" errors

### ISSUE THREAD

**Issue by MSGreen4** [porres/pd-else#1075]
A couple of argument lists to [loop] cause "couldn't create" errors: [loop 1 -b] (found in loop-help.pd) and [loop -offset 1] (found in [cents2scale], so that abstraction does not work). [loop -b] and [loop 1 -offset 1] can be created, however. For what it's worth, I'm using Mac version 1.0-0 beta-43.

**Comment by porres** [comment]
> For what it's worth, I'm using Mac version 1.0-0 beta-43.

well, works for me, macOS 10.14.6, Pd 0.51-4 - what about you?

**Comment by MSGreen4** [comment]
I'm using Pd 0.51-4 on the antiquated OSX 10.10 (I enjoy being an old fuddy-duddy). The compiled 0.51-4 is supposed to work on Mac systems as old as 10.9 (maybe). If [loop] works with current systems, then I'll just work around the "couldn't create" errors.

**Comment by porres** [comment]
it's weird that it doesn't work on earlier systems, so I'm keeping this open. It'd be good if you could test on a machine with a newer system, but I can't understand what the problem could be. Can you also compile from source and test?

**Comment by MSGreen4** [comment]
Unfortunately, I don't have access to a machine with a newer system. As for compiling from source, we'll see ... Sorry to be so not helpful!
