### ISSUE TITLE
player~ don't make "play" message play right away?

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1110]

**Comment by dipaloka** [comment]
i failed to get this "set" message to work, below is the error:

`tabplayer~: no method for 'symbol'`

Does anybody know how to resolve this? Seems to be an issue with tabplayer~?

**Comment by porres** [comment]
I get a different error "inlet: expected 'symbol' but got 'sax.wav'"

**Comment by porres** [comment]
I don't see a use case for 'set' now... but it'd be nice if we could open a file without start playing it

**Comment by brandflake11** [comment]
Is this issue also referring to when opening a new file with |player~| it also automatically starts playing, regardless of the 3rd argument (which in the help file says it will set it to/not to autostart)? 

Basically, regardless of the autostart argument, |player~| will start playing when told to open a new file.

**Comment by porres** [comment]
the open message will always play a file, this is regardless of the autostart...

maybe I should make it just open and let the user tell it to play.

**Comment by porres** [comment]
recently another similar issue was opened and I closed it and just figured I removed the reload and set messages on purpose...

**Comment by porres** [comment]
I'll reboot this
