### ISSUE TITLE
#mouse_mouse: no such object.  In console after deleting [pad] object

### ISSUE THREAD

**Issue by RetroMaximus** [porres/pd-else#1124]
At on point I was browsing new objects and added [pad] to the patch then deleted it. To be honest it could have been [keyboard] now that I think about it. I was tinkering with both around the same time. But this error still remains. I've opened the patch in a text editor to search for any mention of mouse or the pad object and the result is always false. where else could this object be stored? I'm curious if this is just on my pc or if is in the document somewhere. 

#mouse_mouse: no such object 

My patch is available here. 

I should mention I am using Pd 0.52.0 testbuild

https://github.com/RetroMaximus/Oversynth/

**Comment by porres** [comment]
Hi, I can't debug a patch this big/complex... I need a minimal patch that shows the behaviour, please see if you can provide me that. If so, I'll reopen the issue.

**Comment by porres** [comment]
so, can't you provide me a single patch and not a link to a repo? :)

**Comment by porres** [comment]
moreover, i'm not convinced the error would come from a deleted pad object at all

**Comment by porres** [comment]
else/multi.vsl is an abstraction that uses else/mouse...

now I need a minimal patch that gives me this error with this object to see if I can reproduce it

**Comment by porres** [comment]
I also dont understand what the error is for you and when it happens

**Comment by RetroMaximus** [comment]
Sorry I didnt see any of your responses come through until now. I will try to recreate this issue. apologies.
