### ISSUE TITLE
Bug in merge.c

### ISSUE THREAD

**Issue by timothyschoen** [porres/pd-else#1127]
Array of size x_numinlets get allocated (line 117) before x_numinlets is defined (line 153). If you run the code with any kind of address sanitiser, it will crash on line 118 when we write outside of bounds.

**Comment by porres** [comment]
are using some kind of debugger? is that all you found?

**Comment by porres** [comment]
does c50e7bd settle this?

**Comment by timothyschoen** [comment]
Yes, that fixes it, thanks!
