### ISSUE TITLE
add [knob]

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1134]

**Comment by lupin3rd** [comment]
A very important object :+1: 
do you think to add on next releases?
Thank you

**Comment by porres** [comment]
waiting to see if it gets into vanilla

**Comment by porres** [comment]
@timothyschoen let's do it? :) need help

**Comment by timothyschoen** [comment]
I have a bit more time now the new PlugData is out, how are you planning to handle this?

**Comment by porres** [comment]
So, I just stole the latest code from the knob PR, here's the branch https://github.com/Ant1r/pure-data/tree/feature/knb3

I just had to edit the code of the knob so we have a proper "knob_setup" function and compiled against pd 0.53, it works! But I also need to include/update in Pd's source code 2 tcl files (dialog_iemgui_knb.tcl / dialog_iemgui.tcl) into the 'tcl' folder.

By the way, have you updated plugdata to 0.53?

So... I would need a simple help making this more independent. 1st step would be to have a single tcl file that doesn't need to be part of pd's application. Next step would be to not have any tcl file at all, like we did with the number box.

But anyway, now that we also have a signal number box and will also have an actual number box, I think I will end up making changes and work on my own 'else like' GUI to make things consistent. So this would stick to ELSE even if knob gets in... fuck it :) I don't care :) 

One of the things I do differently is the initialization value not being a 'savestate'. I also wanna make it simpler and forget about 'labels' (we just use [else/note] for that in ELSE)... in the end, I might also steal sliders from Pd and make my own one. I also have plans to implement a different built in exponential function for all my GUIs (knob/number boxes, sliders). Maybe some of this stuff gets into iemguis (I will try), but best case scenario it will take years :) 

So, just help me compiling this as a single and independent 'C' code and I will work on this and ask you for help later ;)

**Comment by porres** [comment]
oh, here's my compiltation test with the needed tcl files 

[knob.zip](https://github.com/porres/pd-else/files/9938798/knob.zip)

**Comment by porres** [comment]
I waited.. it's been 2.5 years that this PR was first proposed, time to jump ahead and just steal it :)

**Comment by porres** [comment]
you know what, we may need to wait a bit, I just found 2 bugs in this thing and we should wait till it gets fixed upstream first... but you know the drill now :)

**Comment by porres** [comment]
>  I will work on this and ask you for help later ;)

Since I have changes that would be reflected in the properties, I need help with tcl tk :) 

I know you say you don't know anything about it, but I know even less, and I actually hope you help me and TEACH me so I don't need to bug you :) 

so, for now, maybe we can work in other stuff, like the changes I wanted to make to oscope~ and needed help also.

[bicoeff] is also in desperate need of being actually presentable.

**Comment by timothyschoen** [comment]
I can help with that. I must say that when I'm doing tcl/tk stuff, it's mostly a matter of copying stuff I see in other tcl/tk files, without always knowing what it does exactly.

So for example, for [note], I just looked at the font selector in the IEMGUI dialogs. I try to find the code that actually creates the font selector, and copy that over. Then, I look at all the variables that are used in that piece of code, and see where else they are used, and then copy that over as well (while also looking if those variables depend on other variables, basically repeating this process until you have everything).

The last thing after that is finding the place where the current values are passed to the dialog, and the place where the dialog passes them back to pd, and make sure our new parameters are handled in there.

Then when that's done, I try to run it and there are almost always problems. And debugging in tcl/tk is horrible, sometimes you get an error message, but sometimes you don't... It often requires going over the tcl/tk file line for line and trying to figure out where it goes wrong.

I guess the skill this relies on, is being good at having no idea what you're doing.

One thing I've noticed about tcl/tk is that there seems to be a distinction between local and global variables. If you want to use a global variable in a function, you have to declare that you want to use that global variable first. That leads to a lot of repeating variable names, and is really the most painful part of tcl/tk in my experience.

**Comment by timothyschoen** [comment]
> By the way, have you updated plugdata to 0.53?

Not yet, the update came out in the middle of v0.6.2 development, and there are a few internal changes that I need to integrate into PlugData (like the new hsl/vsl class).

**Comment by porres** [comment]
> I guess the skill this relies on, is being good at having no idea what you're doing.

ahahahhaha, well, you're an actual programmer

anyway, if you can just try to comment the code in [note] and others to try and make it clear (even saying things like "i think" or "maybe this" or "i don't know this") would be really helpful

**Comment by porres** [comment]
@timothyschoen good news, bugs have been fixed upstream, now we can steal and start working on it :) see https://github.com/porres/pd-knob

**Comment by timothyschoen** [comment]
Nice, repo is gone though :(

**Comment by porres** [comment]
> repo is gone though :(

what do you mean?

I'm still doing some basic code cleanup, tell me if you're at it already

**Comment by timothyschoen** [comment]
This repo: https://github.com/porres/pd-knob

Is not accessible to me. Is it private?

**Comment by porres** [comment]
hmmm, maybe :) well, found another bug, wait a moment

**Comment by porres** [comment]
ok, now made public and with a bug I introduced fixed... https://github.com/porres/pd-knob

**Comment by porres** [comment]
added undo ;)

**Comment by lupin3rd** [comment]
It will be on RC6 ? :-D

**Comment by porres** [comment]
no
