### ISSUE TITLE
Pedido de bang de fim para [loop]

### ISSUE THREAD

**Issue by emviveros** [porres/pd-else#1157]
O objeto [loop] podia enviar um bang de fim assim que o loop setado terminar.

Assim quando utilizado em conjunto com o [add] seria fácil tanto de zerar o sum, assim como de liberar o valor final do cálculo por um [f].

É útil para calcular fórmulas que fazem uso de somatório (Σ)

**Comment by porres** [comment]
amigo, é só usar um [trigger] ;) manda exemplos aí

**Comment by emviveros** [comment]
Segue o exemplo:
[exemplo_caso_[loop].pd.zip](https://github.com/porres/pd-else/files/7906123/exemplo_caso_.loop.pd.zip)

Daí seria:
1. bang de fim do loop
2. setar máximo e mínimo sem iniciar loop

Isso seria um facilitador para códigos onde estamos explorando números obtidos de generalizações matemáticas utilizando somatórios. Bom no paradigma de explorar "o som de expressões ou leis matemáticas, estatísticas" enfim... O céu é o limite...

**Comment by porres** [comment]
expandir a mensagem 'set' pra além de um float é ok e possível

**Comment by emviveros** [comment]
Acho que consigo ver um pouco do que está falando, mas como você faz para não sobrecarregar a leitura do patch toda a lógica de controle de fim do loop? Lembrando que para fazer esse controle, é necessário a adição de pelo menos mais um objeto [route] que receberá além do patch cord da saída do resultado do loop, outro patch cord para setar o parâmetro com o último número da contagem, sendo que isso já está feito no objeto [loop].

Me parece equivocado ter um objeto com esse nome que não é capaz de entregar quando o loop foi finalizado, e passar para o usuário a tarefa em nome de uma elegância, sendo que a consequência de não ter esse retorno do objeto seria aumentar a potencialidade de códigos espaguetes.

**Comment by porres** [comment]
não to entendendo o que vc tá falando sobre [route] nem nada, eu passei a versão do patch, acho que precisa só de um trigger.

um 'for' não traz nenhum comando dizendo que acabou, ele só acaba, depois vc segue com o código, e pra organizar a sequencia se usa um trigger.

E enfim, eu tinha esse outlet na direita, mas era sempre ruim organizar o código, então eu preferia usar o trigger mesmo, achei que deixar esse negócio ali promovia spaghetti

E tem a ver tb com uma ideia de design que é "KISS" (keep it simple, stupid). Tipo, eu odeio o Uzi, por exemplo, que tem TRÊS OUTLETS!

Mas enfim, baixa a versão ELSE beta 20, que ainda tinha o outlet extra, veja o objeto lá, usa ele, me mostra num patch e me convença que tá mais elegante

**Comment by porres** [comment]
faria sentido, como eu falei, se fosse na esquerda, mas quando eu incluí na versão 8 esse segundo outlet, eu não quis quebrar a compatibilidade... aquilo ficou me incomodando demais até que eu pensei em um dia trocar a ordem dos outlets, no fim acabei apenas deletando ele na versão 21

**Comment by porres** [comment]
só se eu criar uma flag, que cria esse outlet na esquerda... mas aí vai complicando bastante o design...

**Comment by emviveros** [comment]
> não to entendendo o que vc tá falando sobre [route] nem nada, eu passei a versão do patch, acho que precisa só de um trigger.

Desculpe, não havia visto, mas de qq forma acho que enviou o teste errado...

**Comment by emviveros** [comment]
> E tem a ver tb com uma ideia de design que é "KISS" (keep it simple, stupid). Tipo, eu odeio o Uzi, por exemplo, que tem TRÊS OUTLETS!

Entendi de onde está vindo.. Isso é interessante mesmo... Porém, ainda não me convence de por exemplo o [count] ter o bang de final e o loop que seria o [count] facilitado e aplicado para loops não ter. 

Escrevi o mesmo com o loop da ELSE beta 20. Tem o problema da inversão da saída mesmo, mas de qualquer forma está bem mais legível que a versão com o [loop] atual.

[exemplo_loop.zip](https://github.com/porres/pd-else/files/7910317/exemplo_loop.zip)

**Comment by porres** [comment]
mas o count segue outra lógica, que não é de um [trigger]

o count e objetos como [sequencer], [pattern] e até outros do vanilla (como [tabplay~]) seguem essa lógica de dar um aviso quando um evento acontece.

Rapaz, eu perco muito tempo pensando nessas coisas ;)

**Comment by emviveros** [comment]
Acho que dá pra atenuar o problema do espelhamento da leitura do patch apenas arrumando um pouco melhor. Mas daí vai de caso a caso.. Neste caso, ficaria assim:

ANTES
![Captura de Tela 2022-01-21 às 01 13 56](https://user-images.githubusercontent.com/3089536/150464765-46e0eae0-2261-4467-8bf2-7769efc52172.png)


DEPOIS
![Captura de Tela 2022-01-21 às 01 13 34](https://user-images.githubusercontent.com/3089536/150464775-923c862d-36e6-41c6-9021-91c3b4a0edd4.png)

**Comment by porres** [comment]
Acho que vc não tá entendendo a ideia de só usar um trigger. É só botar ele antes.

Não precisa de route, de nada. E enfim, eu não acho legal subverter a lógica sequencial do Pd que primeiro as coisas saem da direita e depois vem na esquerda... como seria no loop, que é diferente de uma ideia de counter, pq é algo sequencial mesmo. E criar uma flag pra criar um inlet extra esquerdo só pra não usar um trigger me parece overkill

![Screen Shot 2022-01-21 at 01 45 31](https://user-images.githubusercontent.com/5360142/150467375-55f32fa4-cae3-4bb8-ab20-49ade3ec48ba.png)

**Comment by porres** [comment]
acho que vou ter que deixar claro esse princípio na documentação...

**Comment by emviveros** [comment]
Entendi. Sim documentar isso do trigger seria legal mesmo.

Agora me considero satisfeito com a decisão de design do objeto [loop], e como não será adicionado um outlet de endbang ao objeto eu estou fechando a issue.

**Comment by porres** [comment]
> E criar uma flag pra criar um inlet extra esquerdo só pra não usar um trigger me parece overkill

tipo, qual patch de pd não se usa dezenas de triggers aqui e ali?

enfim, tem duas ideias aqui, setar mais que um float na mensagem 'set' e, quem sabe, uma flag '-t' pra quem tiver preguiça de criar um trigger, podemos abrir essas issues

**Comment by emviveros** [comment]
Extender a mensagem set para aceitar uma lista parece uma boa.

Agora criar uma flag para modificar o comportamento do objeto pode ser um pouco transformers demais. Talvez apenas documentar o uso do trigger, como descrito aqui já resolve e deixa a lógica mais clara, pelo menos para o caso do somatório que apresentei.

**Comment by porres** [comment]
> test.pd.zip

vi que tinha te mandado um arquivo nada a ver, kkkkk
