### ISSUE TITLE
Variable and zero length arrays in keyboard, metronome and rec objects don't compile with MSVC

### ISSUE THREAD

**Issue by timothyschoen** [porres/pd-else#1182]
keyboard, metronome and rec don't compile with MSVC because it has no support for variable length arrays.

In keyboard it happens on line 63, 73, 156 and 357. These are all unnecessary VLA's because the size is constant.

The ones in rec are on line 191 and 206, these are actually VLA's, and need to be replaced with heap allocation.

In metronome the bug is a bit different, it creates an array of size 0 which is also not supported by MSVC. These are passed to the typedmess function, but can probably just be NULL instead?

also, small one: pic.c includes unistd.h, but without #ifndef _MSC_VER

After that it should compile for MSVC! I guess you could just use MSYS/MINGW, but for including it in (JUCE) projects like Camomile-ELSE and PlugData, it's very convenient if it works with MSVC.

**Comment by timothyschoen** [comment]
Yeah, PlugData is also still in pre-release so it's fine for now.

**Comment by porres** [comment]
note that rec is also based on cyclone/mtr, which should have the same issues, maybe we need a PR for that too ;)

**Comment by timothyschoen** [comment]
I've fixed MSCV support in PlugData now, I'm a little busy fixing issues still but in a few days I'll have a pull request ready. Another issue is the dir object, it uses <dirent.h> which is not available on MSVC.

**Comment by porres** [comment]
by the way, this may also affect plugdata https://github.com/porres/pd-else/issues/1174

**Comment by timothyschoen** [comment]
I've confirmed that this affects PlugData, very strange bug though.

**Comment by porres** [comment]
> I'm fixing all these issues anyways because I want to release a new version of PlugData hopefully tonight. Shall I send you a pull request?

wher'es the PR? :)

**Comment by timothyschoen** [comment]
Not there yet :(

The problem is that some objects like dir (and I believe some more) don't work with MSCV at all. I've just disabled them in PlugData, but for the pull request I have to actually fix those objects. I'm also not a Windows user, which makes it more difficult.

**Comment by porres** [comment]
> I could send you a PR for the other issues first if you'd like?

ok

**Comment by timothyschoen** [comment]
I've made a PR fixing most issues here, except for the ones in pic and dir.

**Comment by porres** [comment]
I may try to redo [dir] as an abstraction based on [file] and [pdcontrol], what do you think? Can you compile [file] alright?

**Comment by porres** [comment]
can you fix the issue with pic?

**Comment by timothyschoen** [comment]
I can compile file, it would be great to have dir based on file! I can solve the issue with pic, it just involves writing a wrapper like I did for mousepad and keyboard, should be pretty simple.

**Comment by porres** [comment]
>  it would be great to have dir based on file!

not that easy, i'd rather not have to... [file] should have more functionalities to make things easier...

**Comment by timothyschoen** [comment]
Maybe something like this could help:

https://github.com/tronkko/dirent

It's a single header dirent.h replacement for Windows, should be very simple to get it working this way.

**Comment by porres** [comment]
can we close this?

**Comment by timothyschoen** [comment]
yes!
