### ISSUE TITLE
[midi] dump with delta time?

### ISSUE THREAD

**Issue by Jonathhhan** [porres/pd-else#1213]
it would be great to have an alternative dump with delta times together with the midi messages as lists.
I added a method, but it only gives me the delta times:
```
static void midi_dump_delta(t_midi *x){
    t_midievent *ep = x->x_sequence;
    int nevents = x->x_nevents;
    while(nevents--){  // LATER rethink sysex continuation
        double bp = ep->e_delta;
        outlet_float(x->x_deltaout, (float)bp);
        ep++;
    }
    outlet_bang(x->x_bangout);
}
```
If I could output ep (delta time + midi event) as lists, I have what I want.
I combine them with an abstraction afterwards now...

**Comment by Jonathhhan** [comment]
Maybe better (but would be nicer to output each event with delta as a list instead of seperate floats):
static void midi_dump_delta(t_midi *x){
    t_midievent *ep = x->x_sequence;
    int nevents = x->x_nevents;
    while(nevents--){  // LATER rethink sysex continuation
        unsigned char *bp = ep->e_bytes;
        double dp = ep->e_delta;
        outlet_float(((t_object *)x)->ob_outlet, (float)dp);
        outlet_float(((t_object *)x)->ob_outlet, (float)*bp);
        int i;
        for(i = 0, bp++; i < 3 && *bp != MIDI_EOM; i++, bp++)
            outlet_float(((t_object *)x)->ob_outlet, (float)*bp);
            	if (*bp == MIDI_EOM)
	    outlet_bang(x->x_bangout);
        ep++;
    }
    outlet_bang(x->x_bangout);
}

**Comment by porres** [comment]
as a list is better, it could be an optional nonzero argument to 'dump', why don't you go ahead and make a PR?

**Comment by Jonathhhan** [comment]
a agree with the list and the argument. that would be great. I didnt make a PR because I did not manage to output the values as a list (first time I change an external)...

**Comment by porres** [comment]
You know, if you save the MIDI as a .txt, you get exactly this, the MIDI data with delta times! I see why one would like a dump method better, but you can maybe work with this for now...

**Comment by porres** [comment]
closing but it's still on my list but in a new issue
