### ISSUE TITLE
strange behavior with drum.seq

### ISSUE THREAD

**Issue by smomid** [porres/pd-else#1218]
Hi, 

I am using Pd 0.52.1 and I have Else version 1.0-0 beta 45.

When I use the drum.seq object, I noticed that if I don't have the lower leftmost corner box selected the whole sequence is shifting one column to the left. 

I don't think I noticed this behavior before, but I just updated the else library too. 

I am attaching a patch to display what I am talking about. Please let me know if you can recreate this behavior.

[DrumSeqBehavior.pd.zip](https://github.com/porres/pd-else/files/8172681/DrumSeqBehavior.pd.zip)

**Comment by jamshark70** [comment]
I can reproduce this. An initial `0` following `import` causes the left-shift.

The only difference between left and right here is that the left says `import 1 0...` while the right says `import 0 0...` but the data are filled into different positions.

![pd-drum-seq-import-bug](https://user-images.githubusercontent.com/318301/156672771-3138e58e-5f25-4dc5-b346-9bd406f986ad.png)

[22-0304-drum-seq-bug.pd.zip](https://github.com/porres/pd-else/files/8181932/22-0304-drum-seq-bug.pd.zip)

**Comment by porres** [comment]
sorry I didn't take care of this in the last update, it was already too big

**Comment by porres** [comment]
since this is an abstraction, you can just download the new patch from the fix above and you don't need to wait for the next update ;)

**Comment by smomid** [comment]
Where is the new fixed abstraction? I went to code/classes/abstractions and downloaded drum.seq and it seems like the same one with the bug in it. Unless I am missing something. 

thanks, Nick

**Comment by porres** [comment]
the fix is here https://github.com/porres/pd-else/commit/da13e897308471e7038f7ce66e0b607d7721cd3a

download the latest source and it should be fine, if not, let's reopen the issue

**Comment by smomid** [comment]
Hi. I copied the text into a text file, saved it. Then tried changing the file so it ended in .pd

The file still doesn't open in Pd for me. Maybe I am missing something because i don't convert Pure data files into text and back very often. But just letting you know I couldn't get the text to open up as a patch.

**Comment by porres** [comment]
dude, here's the new abstraction, try it [drum.seq.pd.zip](https://github.com/porres/pd-else/files/8535264/drum.seq.pd.zip)

**Comment by smomid** [comment]
Sorry man, I'm slow at figuring this shit out sometimes.

Yes the abstraction works.

Thank you, very helpful abstraction by the way. I'm using it a lot.

Nick
