### ISSUE TITLE
allow using an alternative pd-lib-builder Makefile

### ISSUE THREAD

**Issue by umlaeute** [porres/pd-else#123]
please allow the user to override used `Makefile.pdlibbuilder` as explained in https://github.com/pure-data/helloworld/blob/master/Makefile#L14-L16:

~~~make
# include Makefile.pdlibbuilder from submodule directory 'pd-lib-builder'
PDLIBBUILDER_DIR=pd-lib-builder/
include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder
~~~

**Comment by porres** [comment]
I think this is it then https://github.com/porres/pd-else/commit/b70c0003a825928086c4076b1bcdc22ac59b73b7
