### ISSUE TITLE
envgen~ crashes mac

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1238]

**Comment by timothyschoen** [comment]
<img width="790" alt="Screenshot 2022-04-30 at 12 52 19" src="https://user-images.githubusercontent.com/44585538/166102515-8b38fecc-8f85-4ed1-8ad3-1ec2e3310d03.png">

Very strange, I can't reproduce this...

**Comment by timothyschoen** [comment]
I think I know the problem: I used freebytes instead of free, but I didn't let pd know about the memory allocation. I've submitted a pull request with a fix.

Since I can't reproduce the issue I don't know if it will work... But it's nonetheless an improvement.

**Comment by porres** [comment]
got a compilation error 

Classes/Source/envgen~.c:267:23: error: too many arguments to function call,
      expected 1, have 2
        free(temp_at, sizeof(t_atom) * ac-nlines);
        ~~~~          ^~~~~~~~~~~~~~~~~~~~~~~~~~
