### ISSUE TITLE
add sfizz~ 

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1244]
after adding sfont~ (see https://github.com/porres/pd-else/issues/1243), there's a plan to also add an object based on "sfizz~".

sfizz is a sound font player for the sfz format, see https://sfzformat.com/software/players/ and https://sfz.tools/ 

it is released here <https://sfz.tools/news/2021/11/08/sfizz-1.1.1-release.html>. It comes as a wide range of plugins and also as a Pd external, see --> https://github.com/sfztools/sfizz/blob/develop/plugins/puredata/sfizz_puredata.c

what I like about this external is that it is provided as a single binary (no dynamic libs)

here's the help screenshot.

![Screen Shot 2022-05-03 at 15 12 48](https://user-images.githubusercontent.com/5360142/166516289-1e6ab024-8397-43fa-b984-1b68fa419356.png)

Ceammc seems to have stolen this object for their library as well, see https://github.com/uliss/pure-data/blob/ceammc/ceammc/ext/src/misc/sfizz_tilde.cpp

**Comment by porres** [comment]
So, I created a new repository with code from https://github.com/sfztools/sfizz

I just made minor adaptions, removed some basic unnecessary things and my idea is to have a repository just so it is able to build a new version of the Pd object, using pdlibbuilder and ship it as part of ELSE.

here's the repository: https://github.com/porres/pd-sfizz

**Comment by porres** [comment]
ping @Lucarda :)

**Comment by Lucarda** [comment]
see https://github.com/porres/pd-sfizz/issues/1#issuecomment-1371342840

can't get the object via `pd-lib-builder` but it works via `cmake`

**Comment by porres** [comment]
ok, asking tim for help again, but if you can compile the thing with cmake I'd like to be able to do the same, so please help me, as I wanna work a bit on the object design

**Comment by Lucarda** [comment]
i'm not sure if this works on your repo so keep copies of the `.c` and `*-help.pd` you are going to edit.

never did it on macOS. here it says you have to get things with `Homebrew`:

https://sfz.tools/sfizz/development/build/macos

the rest is something like this on Windows and Linux.


clone the repo 

`git clone https://github.com/sfztools/sfizz.git`

`cd` to the repo and init submodules

`git submodule update --init --recursive`

make a dir and cd to it

`mkdir build && cd build`

copy and paste this commands:

```
cmake .. \
-DENABLE_LTO=OFF \
-DSFIZZ_JACK=OFF \
-DSFIZZ_RENDER=OFF \
-DSFIZZ_LV2=OFF \
-DSFIZZ_LV2_UI=OFF \
-DSFIZZ_VST=OFF \
-DSFIZZ_AU=OFF \
-DSFIZZ_PUREDATA=ON \
-DSFIZZ_BENCHMARKS=OFF \
-DSFIZZ_DEMOS=OFF \
-DSFIZZ_DEVTOOLS=OFF \
-DSFIZZ_TESTS=OFF \
-DSFIZZ_SHARED=ON \
-DSFIZZ_USE_VCPKG=OFF \
-DSFIZZ_USE_SNDFILE=OFF \
-DSFIZZ_USE_SYSTEM_ABSEIL=OFF \
-DSFIZZ_USE_SYSTEM_SIMDE=OFF \
-DSFIZZ_USE_SYSTEM_KISS_FFT=OFF \
-DSFIZZ_USE_SYSTEM_PUGIXML=OFF \
-DSFIZZ_USE_SYSTEM_CXXOPTS=OFF \
-DSFIZZ_RELEASE_ASSERTS=OFF

```

then

`make`

if all went good the external is somewhere in the `build` dir.



this is just a guess: if you edit the `.c` file then just run again `make`.

**Comment by porres** [comment]
Hey, I can build with cmake just fine ;) thanks... but the mistery remains on how to steal this thing and use pdlibbuilder instead

**Comment by porres** [comment]
I actually used

mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release \
      -DSFIZZ_VST=OFF \
      -DSFIZZ_AU=OFF \
      -DSFIZZ_JACK=OFF \
      -DSFIZZ_LV2=OFF \
      -DSFIZZ_LV2_UI=OFF \
      -DSFIZZ_PUREDATA=ON \
      -DCMAKE_CXX_STANDARD=14 \
      ..
make -j$(sysctl -n hw.ncpu)


maybe I got a bunch of stuff I didn't need

**Comment by porres** [comment]
next time i'll try

mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release \
	-DENABLE_LTO=OFF \
	-DSFIZZ_JACK=OFF \
	-DSFIZZ_RENDER=OFF \
	-DSFIZZ_LV2=OFF \
	-DSFIZZ_LV2_UI=OFF \
	-DSFIZZ_VST=OFF \
	-DSFIZZ_AU=OFF \
	-DSFIZZ_PUREDATA=ON \
	-DSFIZZ_BENCHMARKS=OFF \
	-DSFIZZ_DEMOS=OFF \
	-DSFIZZ_DEVTOOLS=OFF \
	-DSFIZZ_TESTS=OFF \
	-DSFIZZ_SHARED=ON \
	-DSFIZZ_USE_VCPKG=OFF \
	-DSFIZZ_USE_SNDFILE=OFF \
	-DSFIZZ_USE_SYSTEM_ABSEIL=OFF \
	-DSFIZZ_USE_SYSTEM_SIMDE=OFF \
	-DSFIZZ_USE_SYSTEM_KISS_FFT=OFF \
	-DSFIZZ_USE_SYSTEM_PUGIXML=OFF \
	-DSFIZZ_USE_SYSTEM_CXXOPTS=OFF \
	-DSFIZZ_RELEASE_ASSERTS=OFF \
      	-DCMAKE_CXX_STANDARD=14 \
      ..
make -j$(sysctl -n hw.ncpu)





but I have no idea what the '-DCMAKE_CXX_STANDARD=14 \' is for, for example...

**Comment by porres** [comment]
> but the mistery remains on how to steal this thing and use pdlibbuilder instead

pinging @Lucarda , @timothyschoen and @charlesneimog to see if anyone can help me figuring out how to incorporate this in ELSE using pd-libbuilder

**Comment by porres** [comment]
> Can we wait until Pd 0.54 is out?

it's out :) @Lucarda

**Comment by Lucarda** [comment]
are you going to add a sfizz~ submodule in `else` or you just have a new folder with all the sfizz~ stuff?

**Comment by porres** [comment]
I don't know how to handle submodules, I could, it seems it's reasonable, but I need real help with it... I usually just copy stuff as I do feel more comfortable with it, but that's lazy I know

**Comment by Lucarda** [comment]
it seems the repo has changed

> On 2023/05/08 the project was divided into 2 repositories: this contains only the library required by third-party applications, and [sfizz-ui](https://github.com/sfztools/sfizz-ui) for plugins (and a future possible graphics standalone).

and the Pd external is now in `sfizz-ui`

we'll have to investigate what we need

**Comment by Lucarda** [comment]
if we do a `submodule` then you have to do

`git submodule update --init --recursive`

to get the files. also people downloading the repo via the zip pkg wont get what's inside submodules.

if we go into copying the folder then everything is normal and you just update the folder when you think is needed.

**Comment by porres** [comment]
Sure, I know. And I'm more comfortable keeping things here

**Comment by Lucarda** [comment]
basically we will need an `else/sfizz-ui` folder.

and we'll need your `pd-else/Classes/Source/sfizz_puredata.c`

then in the process we copy `pd-else/Classes/Source/sfizz_puredata.c`

to `sfizz-ui/plugins/puredata/sfizz_puredata.c`

do the calling of the `cmake`

and then place the external and the help patch in the `install` dir.

basically ,implementation needed :)

**Comment by porres** [comment]
Can you help with that in a pr?

**Comment by porres** [comment]
it took a damn while (not a real problem) but it did build! Nice! Thanks a lot!

**Comment by porres** [comment]
guess you're ready to send me a PR @Lucarda

**Comment by Lucarda** [comment]
done via #1679

we can close this one.
