### ISSUE TITLE
pic objects break puredata when Zoom New Windows preference is enabled

### ISSUE THREAD

**Issue by kdltr** [porres/pd-else#1248]
Tested with ELSE 1.0-rc1 tag and Puredata 0.52.2

How to reproduce:
- create a new patch
- insert a pic object (no need to put a different image in, the question mark one is fine)
- save and close the patch
- enable File->Preferences->Zoom New Windows
- reopen the patch

Pd will semi-freeze, the patch will not open and this gets displayed in the message window:

```
(Tcl) INVALID COMMAND NAME: invalid command name ".x55ab28e4d0.c"
    while executing
".x55ab28e4d0.c delete 55ab2594d0_in"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 $docmds"
```

**Comment by porres** [comment]
I wonder if other GUI objects are also fucked up...

**Comment by porres** [comment]
[pad] and at least some other is also fucked up...
