### ISSUE TITLE
Memory bug in args

### ISSUE THREAD

**Issue by timothyschoen** [porres/pd-else#1249]
In args.c, line 50-52:

```
            while (j < ac){
                j++;
               if ((av+j)->a_type == A_SYMBOL && x->x_separator == (atom_getsymbol(av+j))->s_name[0])

```

I believe ac is the number of elements, meaning that if you do j++ before the lookup, it will read out of bounds.

Does the reading need to start at 1 or 0? If it needs to start at 0, put j++ at the end of the while loop. If it needs to start at 1, replace ``` j < ac``` with ``` j < ac - 1```.

**Comment by porres** [comment]
dude, this object has been mysteriously crashing for years now :) maybe you found something ;)

**Comment by timothyschoen** [comment]
Yay, glad to help! This was the only obstacle that prevented All_objects from loading with Xcode's address sanitiser enabled, so this might be one of the last serious memory problems!

I also noticed a small thing: trigger2 object is removed (and t2 as well?), but it's still in All_objects.

**Comment by porres** [comment]
> I also noticed a small thing: trigger2 object is removed (and t2 as well?), but it's still in All_objects.

they're not here nope :)

**Comment by porres** [comment]
Now, this is code I injected from else/break.c - I wonder if "break" has no memory leak too...

**Comment by porres** [comment]
does https://github.com/porres/pd-else/commit/6191ec59bf3857a5586dfd0adec15515be4fe91f take care of it?

I honestly don't know how this code works :) but it's working now... and maybe it fixes it...

**Comment by timothyschoen** [comment]
That should fix it, but doesn't this do the same thing as ```while(j < ac - 1)```?  I think that's a prettier solution.

**Comment by porres** [comment]
It didn’t
