### ISSUE TITLE
[midi] crashes when given file doesn't exist

### ISSUE THREAD

**Issue by reduzent** [porres/pd-else#1251]
This happens on Linux. I haven't tested on other platforms. 

Tested with 20885c32b65058de489064e11506a8eb470b7076

**Comment by porres** [comment]
works fine on mac of course

@timothyschoen, is there a debugger that can catch this? do we need one specific for linux?

**Comment by porres** [comment]
@reduzent , what about a missing file for [sfont~] does it crash or handles it nicely?

**Comment by porres** [comment]
I'm using structure from cyclone, so maybe [cyclone/seq] also crashes! And I see it uses 'dirent.h', which is what I use for [else/dir] (see https://github.com/porres/pd-else/blob/master/shared/elsefile.c#L8 & also https://github.com/porres/pd-else/blob/master/shared/elsefile.c#L185 ) . It doesn't seem I need dirent though, right?

**Comment by timothyschoen** [comment]
> works fine on mac of course
> 
> 
> 
> @timothyschoen, is there a debugger that can catch this? do we need one specific for linux?

I'll try to use XCode sanitisers, sometimes it catches stuff that doesn't necessarily cause a crash on Mac.

**Comment by porres** [comment]
@reduzent, I made changes. Now I'm using open_via_path, which is better and searches the path. So, if you have ELSE in your path, the sfont~-help file will not complain that the file is not found. Hence, it will not cause the crash.

But we wanna know if not finding the file still crashes Pd! So make sure you do not have 'else' in your path or give it another bogus filename just to test it, please? I'd like to know if this is fixed before I get the new update release ready, thanks!

**Comment by porres** [comment]
Oh, yeah, @reduzent , you'd have to compile ELSE at the current state. If you can't or if that's just too much of a PITA, let me know and I can compile it for you a test version.

**Comment by porres** [comment]
Oh, and please also test if not finding the file in [sfont~] crashes or not! Thanks

**Comment by porres** [comment]
> Now I'm using open_via_path, 

it seems I should actually use canvas_open instead, like sfont~ does, changing it now

**Comment by porres** [comment]
> changing it now

done

**Comment by porres** [comment]
I still don't get the need to use 'close(fd)' and why not use sys_close instead. Maybe worth noting if there's still an issue

**Comment by reduzent** [comment]
> But we wanna know if not finding the file still crashes Pd! So make sure you do not have 'else' in your path or give it another bogus filename just to test it, please? I'd like to know if this is fixed before I get the new update release ready, thanks!

I had to test with daa42f619abab2ac85378f79baf4f7d2acb413c2, as current main doesn't compile for me. [midi] does _not_ crash when trying to load a non-existing file.

**Comment by reduzent** [comment]
Current m̀aster` (not `main`, sorry)  stops at:

```
Classes/Source/pic.c: In function ‘pic_filepath’:
Classes/Source/pic.c:77:14: error: too few arguments to function ‘canvas_open’
   77 |     int fd = canvas_open(glist_getcanvas(x->x_glist)),
      |              ^~~~~~~~~~~
In file included from Classes/Source/pic.c:3:
/home/roman/pd-src/pure-data/src/m_pd.h:450:12: note: declared here
  450 | EXTERN int canvas_open(const t_canvas *x, const char *name, const char *ext,
      |            ^~~~~~~~~~~
Classes/Source/pic.c:78:9: error: ‘filename’ redeclared as different kind of symbol
   78 |         filename, "", fname, &bufptr, MAXPDSTRING, 1);
```

**Comment by porres** [comment]
Oops, remove pic and I’ll fix this later

**Comment by porres** [comment]
Ok, fixed the compilation error. It should also work I guess, but now current master uses canvas_open, like sfont~ instead of open_via_path

**Comment by porres** [comment]
> instead of open_via_path

which was used in https://github.com/porres/pd-else/commit/daa42f619abab2ac85378f79baf4f7d2acb413c2

**Comment by porres** [comment]
well, made other changes but I guess this is fine now... if you cannot test, it's fine.

@timothyschoen I hope we can try other sanitizers to catch other crashes, thanks!
