### ISSUE TITLE
[bicoeff apass] not working on ms-windows

### ISSUE THREAD

**Issue by Lucarda** [porres/pd-else#126]
When opening "apass~help.pd" i get:

else/bicoeff apass 750 1
... couldn't create

**Comment by porres** [comment]
hi, what version do you have? In beta6 you shouldn't have the "apass~-help.pd" file as this object has been renamed to allpass.2nd~ in beta3 (see release notes: https://github.com/porres/pd-else/releases/tag/v1.0-beta3 )

It seems you have an old version of else, or perhaps mixed/different versions of else combined together. Please do a fresh re-install. Delete whatever you got and download the latest one (beta6: https://github.com/porres/pd-else/releases/tag/v1.0-beta6 ). You can also get it from deken.

**Comment by Lucarda** [comment]
I think i had a mixed old and new else library, not intenionally, just using Deken (seems it dont delete, it overwrites.)

Anyway with beta6 I can create [else/bicoeff eq] but **not** [else/bicoeff apass]. apass is mentioned in the help file.

**Comment by Lucarda** [comment]
Seems just a bug in the [bicoeff] help file, as i can create [else/bicoeff allpass], allpass, not apass.

: - )

**Comment by porres** [comment]
> just using Deken (seems it dont delete, it overwrites.)

yep, it should have an update procedure but it doesnt

> Seems just a bug in the [bicoeff] help file, as i can create [else/bicoeff allpass], allpass, not apass.
> 
> : - )

Seems you havent done what I told you yet, which is to have a fresh install of beta 6 ;)

**Comment by porres** [comment]
I mean, you should be able to create [else/bicoeff allpass] and not "apass", that's what the new help file says

**Comment by Lucarda** [comment]
See [https://github.com/porres/pd-else/blob/master/help/bicoeff-help.pd](https://github.com/porres/pd-else/blob/master/help/bicoeff-help.pd) line 265.

inlets: <apass, lowpass, highpass, bandpass, resonant, bandstop, eq, lowshelf, highs.....

![bicoeef](https://user-images.githubusercontent.com/25239522/33291767-bdbf3932-d3a5-11e7-93a3-69713653237d.jpg)

**Comment by porres** [comment]
oh, ok, I missed that then. I thought you mentioned it had a [else/bicoeff allpass] object.

Anyway, fixed! Thanks
