### ISSUE TITLE
Having some problems after updating else for multi.vsl

### ISSUE THREAD

**Issue by RetroMaximus** [porres/pd-else#1283]
I'm receiving this in pd console  when a patch is first loaded that uses multi.vsl
I can set values but the sliders never seam to update.

apologies but that is all I have to go on. I tried to re-install else a few times and the same error appears.
I've been using "Find Externals" to install else if that matters is the version available there updated?

I'm going to try a fresh pd install to see if I may have deleted something by mistake. But I don't see how I could have interrupted the installation process. This is the first time ive see a error that is labeled with [rescale]

This is the object arguments that im using.

[else/multi.vsl 285 40 0 1 12 empty empty empty 255 255 255 0 200 255 0 0 0 0 0 0 holder holder 0 0 0 0 0 0 0 0 0 0 0 0]

Here is the output to console.

`[rescale]: improper args
 else/rescale -clip 0 0 0 0
... couldn't create
[rescale]: improper args
 else/rescale -clip 0 0 0 0
... couldn't create
[rescale]: improper args
 else/rescale -clip 0 127 0 125
... couldn't create
[rescale]: improper args
 else/rescale -clip 0 127 0 127
... couldn't create
sigmund~ version 0.07
warning: text size ignoring extra argument: 
 1
warning: text size ignoring extra argument: 
 1
warning: text size ignoring extra argument: 
 1
warning: text size ignoring extra argument: 
 1
warning: text size ignoring extra argument: 
 1
warning: text size ignoring extra argument: 
 1
warning: text size ignoring extra argument: 
 1
[rescale]: improper args
 else/rescale -clip 0 0 0 0
... couldn't create
[rescale]: improper args
 else/rescale -clip 0 0 0 0
... couldn't create
[rescale]: improper args
 else/rescale -clip 0 127 0 125
... couldn't create
[rescale]: improper args
 else/rescale -clip 0 127 0 127
... couldn't create
warning: text size ignoring extra argument: 
 1
warning: text size ignoring extra argument: 
 1
warning: text size ignoring extra argument: 
 1
warning: text size ignoring extra argument: 
 1
warning: text size ignoring extra argument: 
 1
warning: text size ignoring extra argument: 
 1
warning: text size ignoring extra argument: 
 1
set: empty pointer
set: empty pointer`

![image](https://user-images.githubusercontent.com/59292329/174149073-4ce38a8d-7024-4a32-b0ab-da982ac8bf2f.png)

**Comment by RetroMaximus** [comment]
looks like -clip is the first argument for rescale and all the examples show it at the end.

**Comment by porres** [comment]
yes, -clip needs to come first

this is confusing, seems like you have a broken patch that needs to be updated to the new version of ELSE?

**Comment by RetroMaximus** [comment]
Apologies for the delay on my response. But I fix it everything is fine.
