### ISSUE TITLE
conv~ no audio & tcl/tk error

### ISSUE THREAD

**Issue by DocSunset** [porres/pd-else#1295]
I think there is something unusual going on, perhaps not related to the abstraction... I notice that even if I make an outlet~ at the top level of the abstraction and connect the input directly to it, there is still no audio passed through the abstraction.

As far as a detailed bug report, please let me know if there is any more information you would require than the following:

```
$ uname -a
Linux [hostname] 5.18.14-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 23 Jul 2022 11:46:17 +0000 x86_64 GNU/Linux
$ pd -version
Pd-0.52.2 ("") compiled 08:57:44 Apr  4 2022
```
Bug description:
conv~ produces no audio at its output
Steps to reproduce:
Open the help patch for conv~. Unmute the output abstraction and turn up the volume.
Expected behaviour:
Reverberated vacuous sound clip should play through speakers.

_Originally posted by @DocSunset in https://github.com/porres/pd-else/issues/861#issuecomment-1199374469_

**Comment by porres** [comment]
> I notice that even if I make an outlet~ at the top level of the abstraction and connect the input directly to it, there is still no audio passed through the abstraction.

that is too weird, and, well, tested it here and I couldn't get sound either. Even weirder, I'm getting tcl/tk errors in the help file...

Now, maybe, just maybe, my computer is too old and fucked (using a macbook air from 2013 now), I think I remember it only properly working on better machines.

By the way, this is a terribly inneficient object and you should probably just use some other convover, I like william brent's convolve~ object. I should include a proper partitioned convolution object in ELSE... @brbrofsvl promised me once :) 

may @timothyschoen would also enjoy that challenge.

Perhaps we could just use William Brent's code with some design changes.

**Comment by DocSunset** [comment]
My computer is also pretty old (mid 2012 macbook pro), so I can't rule out the possibility that old computers may have something to do with the issue.

I will check out Brent's convolve~! Thanks.

**Comment by porres** [comment]
I'm in the process of trying to steal brent's one --> https://github.com/porres/pd-else/issues/1301

**Comment by porres** [comment]
the error
![Screen Shot 2022-07-31 at 13 53 07](https://user-images.githubusercontent.com/5360142/182040759-6ec62302-4d1e-45e8-be0e-470c87ed21fe.png)

**Comment by brbrofsvl** [comment]
I've been working on it off and on. More off than on these days, but I have it in my queue. The biggest issue is getting an efficient partition scheme. I have done some tests with existing objects, but I still need to figure out some things.

Question – what would the specs look like, if you had a wishlist? I can think of all sorts of ways of interacting with such an object.

**Comment by porres** [comment]
what do you mean about 'specs'?

> I can think of all sorts of ways of interacting with such an object.

shoot them

I'm now at the point of stealing brent's work, but would love to have an original one. Brent's uses fftw3 which makes it efficient I guess and also allows arbitrary sizes other than power of 2, but I don't care about that, I don't need to choose in between 256/512/1024...

**Comment by brbrofsvl** [comment]
> what do you mean about 'specs'?

You can make the help file without having the object based on how you want the object to work.

Do you load the IR from a file? From an array? Multichannel?

To make it transparent to the user, I think there should be no delay with respect to the current block size.

**Comment by porres** [comment]
> Do you load the IR from a file? From an array? Multichannel?

I think that from an array makes sense

> To make it transparent to the user, I think there should be no delay with respect to the current block size.

yeah, that'd be awesome

**Comment by porres** [comment]
conv~ is now a new and compiled object
