### ISSUE TITLE
add numbox / numbox~

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1296]
based on https://github.com/porres/pd-cyclone/issues/591

**Comment by timothyschoen** [comment]
I do think it would be awesome to have an number box in ELSE that does hex, binary, int and float! Those others options Max has are cool but seem very context specific to me. 
It's actually not even that hard to turn [number] into a box that does that. All you have to do is convert the value before you pass it into the tcl/tk draw command. The user will have to make sure the numbox is wide enough though, this is the same in Max.

**Comment by timothyschoen** [comment]
As for [numbox~], I'll make some final fixes to [number~], then you can do whatever you want with that. You could make work like you described earlier. Let me know if you need any help with that.

**Comment by porres** [comment]
yeah, octal seems stupid...

as for 'MIDI', else already has [pitch2note] and [note2pitch], so maybe not needed, or maybe we create a new [pitchbox] cause I think it is important that you set a scale for dragging, but whatever, not important and we can start with those of course (hex, binary, int and float).

**Comment by timothyschoen** [comment]
The biggest challenge is writing the opposite conversion, when the user types in (hex or binary) text, and we have to turn it into a float. Still manageable tho.

**Comment by porres** [comment]
else has [dec2hex] and [hex2dec], but hey, having the ability to drag in hex values seem cool to me! That's what sold me into a new box :) 

>  Let me know if you need any help with that.

just get your final touches with number~ and get it over with, as we've been discussing, I might not even bother including it in Cyclone (sorry).

What would really really be helpful for both cyclone and ELSE is that if you could help me adding a decent properties box for cyclone/comment or else/note. Let it be else/note and I will later bring that also into cyclone!

**Comment by porres** [comment]
> Let it be else/note 

https://github.com/porres/pd-else/issues/1297

**Comment by timothyschoen** [comment]
PR is ready! And really, I don't mind if it ends up in ELSE. Maybe that's even better.

I will look at else/note but probably next week. I've been writing externals for two whole days now, my brain is done.

**Comment by porres** [comment]
the damn thing is that iohannes made a gazzilion changes to iemguis and I helped, we should have started based on that :( but I'll see what I can do based on this.

**Comment by porres** [comment]
@timothyschoen, I started working on else/numbox~

It's almost acceptable

I am using my "magic" dependency to check for signal connection so I can switch behaviours and perform routines, maybe I didn't need to, but it's working...

it's gonna take forever for me to clean up and remove iemguis dependency, but it can be done later if we have something that works.

Now for some bugs, actually, for some bugs that I inherited from your cyclone/number~ object.
- The compose color button in properties is not working!!!! It gives us a tcl/tk error.
- When we change parameters from properties, it sets the output value to zero!

Something that I need you to help me with is adding ramp time to properties instead of output mode (which needs to be removed now)

see https://github.com/porres/pd-else/blob/master/Classes/Source/numbox~.c and https://github.com/porres/pd-else/commit/78c73c640dc5f3c7f43a81cb8f30c4e1c0e1e182

**Comment by porres** [comment]
> The compose color button in properties is not working!!!! It gives us a tcl/tk error.

the error:

```
can't read "var_iemgui_l2_f1_b0": no such variable
can't read "var_iemgui_l2_f1_b0": no such variable
    while executing
"eval concat $$var_iemgui_l2_f1_b0"
    (procedure "::dialog_numbox::choose_col_bkfrlb" line 9)
    invoked from within
"::dialog_numbox::choose_col_bkfrlb .gfxstub7f8c22e12680"
    invoked from within
".gfxstub7f8c22e12680.colors.sections.but invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 23)
    invoked from within
"tk::ButtonUp .gfxstub7f8c22e12680.colors.sections.but"
    (command bound to event)

```

**Comment by timothyschoen** [comment]
I'll look at it, should be simple to fix. The var_iemgui_l2_f1_b0 variable is the selector for what colour we're modifying (label=2, foreground=1, background=0).

**Comment by timothyschoen** [comment]
I can also take out the remaining parts of iemgui

**Comment by porres** [comment]
I'm working a lot on this object, trying to get rid of iemgui dependency soon

**Comment by porres** [comment]
just uploaded my last version https://github.com/porres/pd-else/commit/c41c796bd6ad6876f9bf2323589c4b7d1596c1e0

let me know if you're gonna do something

> should be simple to fix. The var_iemgui_l2_f1_b0 variable is the selector for what colour we're modifying (label=2, foreground=1, background=0).

well, I dont get it, if it's a simple fix, please try to send me it, because if it's simple I don't think it will screw things up when merging even if I keep cleaning this up.

**Comment by porres** [comment]
wow, I really screwed up the object, hahaha, will have to revert back

**Comment by timothyschoen** [comment]
> just uploaded my last version [c41c796](https://github.com/porres/pd-else/commit/c41c796bd6ad6876f9bf2323589c4b7d1596c1e0)
> 
> let me know if you're gonna do something
> 
> > should be simple to fix. The var_iemgui_l2_f1_b0 variable is the selector for what colour we're modifying (label=2, foreground=1, background=0).
> 
> well, I dont get it, if it's a simple fix, please try to send me it, because if it's simple I don't think it will screw things up when merging even if I keep cleaning this up.

Sorry, I didn't mean it in a bad way, I meant it's simple for me because I've been looking at the IEMGUI dialog code quite a lot.

Haha that happens to me from time to time as well. I had already gotten rid of all the iemgui stuff, I'll see if I can merge that with your last version.

**Comment by porres** [comment]
> Sorry, I didn't mean it in a bad way

what are you being sorry for? :) 

just fixed my last screwed up change

**Comment by porres** [comment]
> Haha that happens to me from time to time as well. I had already gotten rid of all the iemgui stuff, I'll see if I can merge that with your last version.

Oh, hmm, no no no, I've been doing this as an excercize and really rewriting the thing ;)

**Comment by timothyschoen** [comment]
I've made a new commit, unfortunately I was already far into the process so the dependency on g_all_guis is gone now. I can send a PR, or you can just copy the "numbox_tilde_dialog_init" function, you decide :)

(I promise, there is still plenty of stuff that can be rewritten and improved!)

**Comment by timothyschoen** [comment]
Also, it would be cool if the outlet became a float outlet if there's a signal input. Otherwise that outlet isn't very useful.

**Comment by porres** [comment]
Finished removing that stupid dependency, but yeah, still have lots to clean and rewrite. Please just help me fix those errors, starting with the dialog one (I can copy it). I don't know what you've changed, I am just rewriting lots of things and will still work on it quite some more. Lots of things in iemguis are terrible and outdated, it feels like now I'm gonna start really working on this :) see https://github.com/porres/pd-else/commits/master

**Comment by porres** [comment]
> Also, it would be cool if the outlet became a float outlet if there's a signal input. Otherwise that outlet isn't very useful.

I beg to differ, I usually always connect the signal from the outlet somewhere else, I do that with display~ all the time and this is a replacement for it

**Comment by porres** [comment]
> I beg to differ, I usually always connect the signal from the outlet somewhere else, I do that with display~ all the time and this is a replacement for it

It keeps things well organized, not having to drag the object to the right and then make yet another connection from what's connected to it...

**Comment by timothyschoen** [comment]
That's fair, the float output isn't really all that useful anyway since it's just a random number from the input signal.

**Comment by porres** [comment]
> That's fair, the float output isn't really all that useful anyway since it's just a random number from the input signal.

not anymore :) I removed that too, it just outputs the first sample in the block now, I didn't think it was useful to increase the cost by keeping asking for random values

**Comment by porres** [comment]
Your PR had conflicts so I tried copying it. I still get the same error when trying to "compose color" and I get.

Please help me understand the problem. I wanna learn and be self suficient in tcl/tk :)

```
can't read "var_elsegui_l2_f1_b0": no such variable
can't read "var_elsegui_l2_f1_b0": no such variable
    while executing
"eval concat $$var_elsegui_l2_f1_b0"
    (procedure "::dialog_numbox::choose_col_bkfrlb" line 9)
    invoked from within
"::dialog_numbox::choose_col_bkfrlb .gfxstub7fdb64d56760"
    invoked from within
".gfxstub7fdb64d56760.colors.sections.but invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 23)
    invoked from within
"tk::ButtonUp .gfxstub7fdb64d56760.colors.sections.but"
    (command bound to event)
```

**Comment by porres** [comment]
But the ramp time parameter is working, see https://github.com/porres/pd-else/commit/b4ab221ef5137da9a34a2019917651a87b51901d

I promise I will stop cleaning this up until this is fixed now

**Comment by porres** [comment]
> see https://github.com/porres/pd-else/commit/b4ab221ef5137da9a34a2019917651a87b51901d

wrong commit

**Comment by porres** [comment]
> wrong commit

I'm really confused, sorry, seems to be the correct change

**Comment by porres** [comment]
Ok, we got dialog working! I will try to fix it myself, but I also inherited a weird bug that properties dialog zeroes out the output number.

Also, I don't understand that "undo" bit in the dialog and it seems we're doing it wrong.

New bug: setting the range inside properties doesn't work and stick around

**Comment by timothyschoen** [comment]
The undo bit makes it an undoable action. I think the order of params needs to be the same as in the creation function, but I'm not sure.

I think I know what's causing the range issue, I'll look at that soon.

**Comment by porres** [comment]
> same as in the creation function

what is the creation function? :)

**Comment by timothyschoen** [comment]
I meant numbox_tilde_new()

**Comment by porres** [comment]
so the same order as creation arguments, I'll do that

**Comment by porres** [comment]
this seems like a leftover from old "mode" toggle button

```
            "    if {[eval concat $$var_elsegui_ramp]} {\n"
            "        set $var_elsegui_ramp 0\n"
            "        $mytoplevel.para.ramp configure -text [_ \"Input\"]\n"
            "    } else {\n"
            "        set $var_elsegui_ramp 1\n"
            "        $mytoplevel.para.ramp configure -text [_ \"Output\"]\n"
```

**Comment by porres** [comment]
hmmm, messing with the undo list made clicking+dargging freeze Pd again!

**Comment by porres** [comment]
> hmmm, messing with the undo list made clicking+dargging freeze Pd again!

if I replace all objects for numbox~ without arguments in the file and open it, it works! If I save and reopen, it doesn't anymore!

**Comment by porres** [comment]
> if I replace all objects for numbox~ without arguments in the file and open it, it works! If I save and reopen, it doesn't anymore!

this happens regardless of the changes I made to the undo list... so it seems the thing was never fixed, and I can't find where and how exactly it did go wrong, but it seems it was fine before accepting your dialog fix. I have to go back to previous versions and investigate more.

**Comment by porres** [comment]
> but it seems it was fine before accepting your dialog fix. I have to go back to previous versions and investigate more.

it happened when I put all into a single _struct, a few versions before your dialog fix, so yeah, nothing to do with that and because of this.

**Comment by timothyschoen** [comment]
Got it, it's here:

``` (line 339, function numbox_tilde_dialog)
    int min = (int)getcolor_int(6, ac, av);
    int max = (int)getcolor_int(7, ac, av);
```

getcolor should be atom_getfloat

**Comment by porres** [comment]
> it happened when I put all into a single _struct, a few versions before your dialog fix, so yeah, nothing to do with that and because of this.

sorry for going back and forth, but going back and finding exactly when it happened, it was indeed when I seemingly applied by hand your tcl/tk changes by hand

**Comment by porres** [comment]
> Got it

cool, that's for the range, right? Got it...

**Comment by porres** [comment]
ok, fixed it... https://github.com/porres/pd-else/commit/bfc5d9d863541b0fa7a03874452dd657afabd8d3

but I don't know about the other tcl/tk changes that are making the GUI unresponsive, I guess we need to reboot it, and this is why every time I tried working with tcl/tk I gave up

**Comment by porres** [comment]
> this is why every time I tried working with tcl/tk I gave up

every single time I tried coding with it, editing it a bit, something crazy happens, nothing works, and I just give up, I can't manage to make any sense of it...

**Comment by timothyschoen** [comment]
What is you outcomment all the undo stuff? Do you still get the crash then?

**Comment by porres** [comment]
yup

**Comment by porres** [comment]
we have to go back, restore the old buggy previous properites dialog code and redo it :/ 

My strategy. Restore old code and first fix the "compose color" button. Later, replace "mode" for "ramp"

**Comment by timothyschoen** [comment]
I'd rather attach a debugger and see what's going on than go all the way back! I don't have time right, but maybe I can try it quickly...

**Comment by porres** [comment]
can a debugger pick up whats going on in the tcl/tk part?

**Comment by timothyschoen** [comment]
No, but it can pick up the cause for the whole application crashes, I thought that was the case here?

**Comment by porres** [comment]
if you're asking if pd crashes, yeah, it crashes.

**Comment by timothyschoen** [comment]
Okay, I'm gonna try!

**Comment by timothyschoen** [comment]
> this seems like a leftover from old "mode" toggle button
> 
> ```
>             "    if {[eval concat $$var_elsegui_ramp]} {\n"
>             "        set $var_elsegui_ramp 0\n"
>             "        $mytoplevel.para.ramp configure -text [_ \"Input\"]\n"
>             "    } else {\n"
>             "        set $var_elsegui_ramp 1\n"
>             "        $mytoplevel.para.ramp configure -text [_ \"Output\"]\n"
> ```

This can be removed, shouldn't cause any problems though.

**Comment by timothyschoen** [comment]
binbuf_addv(b, "ssiisiiissfff"

should be

 binbuf_addv(b, "ssiisiiissiff"
 
 Not sure if that causes it, but you use atom_getintarg so it might?
 
 I'm unable to get any crashes, what exactly do I need to do to cause that?

**Comment by porres** [comment]
wow, that indeed seems to have it fixed :) !!!!!!!

I can still get the crash with a previously saved file, but if I restart the process and save the file from scratch, it works fine. It makes sense that the bug is on the 'save' section ;) 

thanks!

**Comment by porres** [comment]
fix is here https://github.com/porres/pd-else/commit/e0f3049293ab4865bc7984046554318910bd319b

I will keep working on this. It's almost good to be included. It still bazzles me that the properties dialog zeroes out the output number.=, if we take care of that, I'll make sure this gets into the next release

**Comment by porres** [comment]
still cleaning the hell out of numbox~ and removing lots of stupid things...

wondering now why and how we're using **sys_queuegui**  and **sys_unqueuegui** and trying to understand this

**Comment by porres** [comment]
numbox~ is basically done and ready!

I will still try to fix that bug where setting properties zeroes out the output number value, which was inherited from the original cyclone/number~ code

I see that the undo is not actually working for properties, we get tcl/tk errors, so when I was changing it to the "correct" order and fixing it I actually introduced a bug - so I don't think I understand this code.

**Comment by porres** [comment]
@timothyschoen I fixed the undo bug, but it doesn't make sense. I reverted back to an earlier version where it worked but it did get the "mode" parameter in the undo atom list. We removed this parameter but it is still needed somehow in that message and I can't understand why... maybe it's something in the tcl/tk code that I can't see, what do you say?

here's the fix commit https://github.com/porres/pd-else/commit/52b1fa3925d06b1c85040f9d42b814f79270a23b

and this is what desn't make sense --> https://github.com/porres/pd-else/commit/52b1fa3925d06b1c85040f9d42b814f79270a23b#r80178374

**Comment by porres** [comment]
my last commit fixes the properties bug where it zeroed out values... there was checkmin-max function that screwed it up...

Well, all good to go, this is now ok to be included! Further improvements can come later, I will just double check for final touches/bugs/issues

**Comment by timothyschoen** [comment]
Nice!! I'll start writing a PlugData wrapper for it! I'm glad this made it into ELSE.

**Comment by porres** [comment]
Just included it in the library... I would wait a bit, or until a final release is made.

One thing I also noticed. Hitting enter in the properties does not apply changes and close the window, like in iemguis...

I would like to figure out the undo issue as well

It could be for later, but I'd love a resizing width via mouse drag in edit mode like in pd's gatom - it should have a double arrow icon as well.

As soon as this is 100% matured, we can go from it and work on your [numbox] object

**Comment by porres** [comment]
I need to work some more on argument parsing and include flags and also clean up and revise some more...

**Comment by porres** [comment]
Wow, I really cleaned the shit out of this thing, and the tcl/tk dialog is now at a separate file. I added the flag arguments, it's almost good to go. I do have ideas for some other design choices.

I would like to add an 'init' value, but not one that works like in iemguis. This would be a 'default initialization' parameter, like an argument for [osc~]. IEMGUIs have this as some sort of save state, which is stupid now that we have [savestate].

Maybe I should reboot this

**Comment by porres** [comment]
https://github.com/porres/pd-else/issues/1308
