### ISSUE TITLE
roadmap for next update or until a final release

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1303]
fix license issue https://github.com/porres/pd-else/issues/489

In a supposed order of priority:
- New [midi] object (breaking the old one).
- Add new dist~ noise object.
- generate and draw curved lines in [function]
- improve [bicoeff] https://github.com/porres/pd-else/issues/1332
- add properties window https://github.com/porres/pd-else/issues/1361
- finish band limited impulse oscillators https://github.com/porres/pd-else/issues/1288
- replace conv~ for a compiled object based on brent's convolve~ https://github.com/porres/pd-else/issues/1301
- All breaking changes I can think of...

**Comment by porres** [comment]
I'm now finishing revising my random generators, the first 3 items in my list above aren't really done and that's bad, @timothyschoen do you think you can help me at least with the oscillators and numbox~ (adding another parameter to properties)? My lowest bar is getting numbox~ done now.

**Comment by timothyschoen** [comment]
Finishing the impulse oscillators is going to require some more research, because I'm not really sure about how to fix it. I tried to fix it before, but that didn't work. 

I can look at [numbox~] though, what exactly needs to be done still?

**Comment by porres** [comment]
@timothyschoen a final version of ELSE needs only these things I guess. After that, there's no excuse to call this an experimental project anymore and it's been like that for a while as I just can't stop breaking things and I guess I have to admit that I will keep doing that but will maybe try not to do it so much?

**Comment by porres** [comment]
what's been on my list forever is generating and drawing curved envelope functions in [function].

**Comment by timothyschoen** [comment]
- Make a clear separation between ELSE and cyclone's utility functions
- Make sure bl.imp2~ uses the same code for complex calculations and bl.imp~

Both small tasks I can take care of!

Nice though, the list isn't too big! And yeah it's hard to not break stuff! It's why I'm going to stop adding features completely for PlugData between v0.7-v1.0... During that period, I'll also spend some more time testing ELSE objects.

**Comment by porres** [comment]
@timothyschoen this is my list of things for a final version. I would really like to be able to add properties windows for remaining GUI objects listed above and it would be great if I could learn how to do this... I also need help for other things here, like convolution and sfizz

**Comment by porres** [comment]
> Make a clear separation between ELSE and cyclone's utility functions

what about this?

**Comment by porres** [comment]
my gendy object is going really well by the way :)

**Comment by timothyschoen** [comment]
> my gendy object is going really well by the way :)

Nice! Looking forward to trying it!

> Make a clear separation between ELSE and cyclone's utility functions

I can look into that, should not be too difficult. I'm wondering if it's already causing issues because I haven't heard any. It is a recipe for problems in the future though.
