### ISSUE TITLE
Feature request for rand.seq 

### ISSUE THREAD

**Issue by lucianozanatta** [porres/pd-else#1306]
Please, add seed to rand.seq object

**Comment by porres** [comment]
essa porra me levou a revisar todos os geradores de sementes em todos os objetos, puta que pariu

**Comment by lucianozanatta** [comment]
Melhor resposta de suporte técnico que eu já recebi na vida

Em qua., 10 de ago. de 2022 às 23:08, porres ***@***.***>
escreveu:
