### ISSUE TITLE
unique seed sometimes fail

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1317]
Sometimes it just generates the same initial value over and over and also for other instances... this is really weird, I may need the help of @brbrofsvl

BTW, just revised all random generators and now they all use the same method that was stolen by matt from supercollider - previous discussion in https://github.com/porres/pd-else/issues/1311

**Comment by brbrofsvl** [comment]
What is the desired behavior?

**Comment by porres** [comment]
Here's the deal @brbrofsvl (and I'm also tagging @timothyschoen )

For all random generators, I have a "seed" message that, without arguments, sets to a unique seed value according to the current time, and each copy gets its own seed. But it's failing as I am getting the same results. Not every time, but every now and then, I send "seed" and I get the same sequence and even two copies of the object can generate the same sequence. See the picture below:

![Screen Shot 2022-08-20 at 02 13 56](https://user-images.githubusercontent.com/5360142/185730070-2de2adee-d23b-406e-a2c6-d63c9d5470b4.png)

The sequence "16 10 19 12 13 16 10 17 15 13 15 20" comes up every now and then when hitting "seed".

check the patch.

[bug.pd.zip](https://github.com/porres/pd-else/files/9386272/bug.pd.zip)

More on how the code works and should work on the next comments.

**Comment by porres** [comment]
This is a screenshot of the help file

![Screen Shot 2022-08-20 at 02 28 26](https://user-images.githubusercontent.com/5360142/185730410-5fa506d2-9906-4f69-b43a-8bc7cb2b0daa.png)

**Comment by porres** [comment]
as for the code, in the random number generators, for the seed method, I call "random_init(&x->x_rstate, get_seed(s, ac, av, ++instanc_n));" for instance, in [rand.i], we have:

https://github.com/porres/pd-else/blob/master/Classes/Source/rand.i.c#L18

the 'instanc_n' is an instance number, called above as "static" (static unsigned int instanc_n = 0;) and gets incremented everytime. I use this so every instance gets a different seed when getting a seed based on the system time.

in random.c we have "get_seed and "random_init", see

https://github.com/porres/pd-else/blob/master/shared/random.c#L36

"get_seed", calls "time" function to get a time value and multiplies by "151" and "instance number".

```
unsigned int get_seed(t_symbol *s, int ac, t_atom *av, int n){
    s = NULL;
    unsigned int timeval;
    if(ac && av->a_type == A_FLOAT)
        timeval = (unsigned int)(atom_getfloat(av));
    else
        timeval = (unsigned int)(time(NULL)*151*n);
    return(timeval);
}
```
random_init initializes "s1, s2, s3"

In the next post I will print what I get when calling these functions.

**Comment by porres** [comment]
So, I tried printing so I could debug. When giving "seed" to two different rand.i objects, I get 

timeval = 1660974233, which is given by time(NULL), then this gets mulitplied by different numbers according to the instance number and I got:

timeval*=151*n = 4200062779
random_init - f = 4200062720.000000

timeval*=151*n = 1604101498
random_init - f = 1604101504.000000

"random_init" is what the random_init function gets as a float for the seed value. It's weird, because "random_init" receives two different values, but this produces the same sequence for both...

"16 10 19 12 13 16 10 17 15 13 15 20"

**Comment by porres** [comment]
I seem to have fixed it by sending unsigned int to random_init instead of a float :)
