### ISSUE TITLE
No seed in [rand.list] and [randpulse]

### ISSUE THREAD

**Issue by MSGreen4** [porres/pd-else#1328]
The seed method and -seed flag did not get added to [rand.list] and [randpulse], presumably due to a clerical error. For this reason, the example in the [seed] subpatch of [rand.list] does not work as expected: -seed (treated as a float with value 0) and 123 are just additional items in the input list, and the outputs of the two [rand.list] objects are not coordinated. I'm using the compiled v1.0 release candidate 3 under Mac OS X 10.10.

**Comment by porres** [comment]
damn! I went one by one...

**Comment by porres** [comment]
[Archive.zip](https://github.com/porres/pd-else/files/9398318/Archive.zip)

it's here, it didn't go upstream :(

**Comment by porres** [comment]
other objects were affected, fix is here, get them all https://github.com/porres/pd-else/commit/e7b158f302f2a30db25b7e40ec035aa639a73083
