### ISSUE TITLE
Index error in [rand.list]

### ISSUE THREAD

**Issue by MSGreen4** [porres/pd-else#1329]
I think that [+ 1] in [rand.list] needs to be replaced with [- 1], since you want the highest random index value output by [rand.i] to be one less than the length of the table $0-list.

**Comment by porres** [comment]
yup

**Comment by porres** [comment]
@MSGreen4 just so you know, I re uploaded the package to deken with the latest fixes

**Comment by MSGreen4** [comment]
Thanks for letting me know! I'll reinstall from Deken.
