### ISSUE TITLE
[rand.i] with a single float argument

### ISSUE THREAD

**Issue by MSGreen4** [porres/pd-else#1331]
[rand.i] with a single float argument does not generate values ranging from 0 to the argument (inclusive), as the help file says it should. Instead it generates values from 1 to (argument - 1). Also, a list of three arguments does not seem to set the seed, as the [example] patch says it will.

**Comment by porres** [comment]
> Also, a list of three arguments does not seem to set the seed, as the [example] patch says it will.

forgot to change that

**Comment by porres** [comment]
thanks for reporting this, use -seed flag and two arguments for now. Please test other random generators if you can :)

**Comment by MSGreen4** [comment]
Happy to test other random generators as best I can. Thanks for fast response! ELSE is definitely my favorite Pd external.
