### ISSUE TITLE
[rand.f] with no arguments

### ISSUE THREAD

**Issue by MSGreen4** [porres/pd-else#1333]
[rand.f] with no arguments generates 0 only; [rand.i] likewise. Also I suspect that even with two arguments [rand.f] will never generate the lowest and highest random values.

**Comment by porres** [comment]
> I suspect that even with two arguments [rand.f] will never generate the lowest and highest random values.

well, the probability is definitely low

**Comment by MSGreen4** [comment]
Oops, of course you are right about that. I constructed a brute-force test
patch and got it to return the lower argument. 10^6 input to [until] didn't
work, but 10^9 did. Looking at the source code might have been a quicker
route to the answer...

**Comment by porres** [comment]
what about rand.f~ and rand.i~?

**Comment by MSGreen4** [comment]
AFAICT, [rand.i~] works as advertised. [rand.f~ 1] generates numbers between -1 and 1, should be between 0 and 1 according to the help file.

**Comment by porres** [comment]
i have fixed them all, and, in fact, changed how they work
