### ISSUE TITLE
[note] issues

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1344]
- Include "Undo" for proeprties.

**Comment by timothyschoen** [comment]
I'll take a look at this tomorrow!

**Comment by timothyschoen** [comment]
<img width="483" alt="Screenshot 2022-09-16 at 02 26 31" src="https://user-images.githubusercontent.com/44585538/190531143-f43f36c8-30cd-4937-8793-1eabf2a41f09.png">

I got most of it working now, the only things left on the list are:

- Incude new width parameter.
- Include "Undo"
- Colors set via properties are not saved with the patch.

I'll send a PR after I fix those (probably tomorrow, it's 2:30 at night over here!)

**Comment by timothyschoen** [comment]
Oh I see the outline color options is still there, that was a mistake, I'll remove that

**Comment by porres** [comment]
> I see the outline color options is still there, that was a mistake, I'll remove that

outline width and color might be a good idea, but not for now :)

**Comment by porres** [comment]
> Include "Undo"

I guess this is all that's left, right? I might be able to do that next week

**Comment by porres** [comment]
Hmm @timothyschoen , setting Text color from properties doesn't work now

**Comment by porres** [comment]
> Text color from properties doesn't work now

I couldn't figure out why and it looks pretty weird, we always get "back", no matter what

**Comment by porres** [comment]
Added UNDO, thanks a lot for the help and work you've done on this :) I cannot believe this happened ;) really happy, been hoping for this being eventually done for years!!!
