### ISSUE TITLE
[drunkard] repeats each output

### ISSUE THREAD

**Issue by MSGreen4** [porres/pd-else#1354]
I noticed that [drunkard] repeats each output. Each bang here will output two identical lines: 

[bang(
|
[drunkard]
|
[print]

Also, I'm surprised that the output is wrapped instead of folded at the boundaries.

**Comment by porres** [comment]
> I'm surprised that the output is wrapped instead of folded

it makes no sense to fold when you can set a weight for direction

for folding, see [brown]

**Comment by porres** [comment]
the issue is in [wrap2], [fold] also has the same bug
