### ISSUE TITLE
Timing problem with .mid export using [midi]

### ISSUE THREAD

**Issue by bazilmuzik** [porres/pd-else#1355]
[[midi]_problem.zip](https://github.com/porres/pd-else/files/9728996/midi._problem.zip)

I attached a little patch to show the problem, but in short, when I export (save) the sequence as a .mid and open it in a DAW, the timing of the events is totally wrong, even when putting the DAW in the right BPM.

**Comment by porres** [comment]
not gonna look at this for a while, I'm gonna actually rewrite and create a whole new midi object that is incompatible

**Comment by bazilmuzik** [comment]
Ha yes, I remember you mentionned that on Facebook, but thought maybe it was already done in the last ELSE release !  
Any idea when it will happen ?

**Comment by porres** [comment]
no :)

**Comment by bazilmuzik** [comment]
Haha ok, no problem XD I guess then the best way to share accurate .mid file is to record midi "live" from Pd to my DAW, and exporting the result from there !
