### ISSUE TITLE
[presets] loading is inconsistent with some objects

### ISSUE THREAD

**Issue by virusys** [porres/pd-else#1356]
Unless I am using it improperly, it seems that the [presets] object is inconsistent when loading certain values, especially number boxes. 

Attached is a screen recording of attempting to load examples from the presets-help.pd patch — certain values are recalled properly (symbols, and GUI objects) while number boxes and the [vslider] remain unchanged. 

https://user-images.githubusercontent.com/393711/194612760-27cba2aa-3650-4071-9646-cdcbf91a1f65.mov

Running Pd 0.52.2 on MacOS Montery 12.4
ELSE version 1.0-0 RC-3

**Comment by porres** [comment]
I don't know what happened but this is not happening anymore in the current state. Current help file works and all...

**Comment by porres** [comment]
releasing rc-4 tomorrow or soon btw

**Comment by virusys** [comment]
I can confirm this is no longer occurring on rc-4. Thanks very much!
