### ISSUE TITLE
[else/keyboard] issue under GOP - Pd 0.52.1 / Ubuntu 22.04

### ISSUE THREAD

**Issue by joe-rouen** [porres/pd-else#1368]
Hello Alexandre,

Congratulations for your Cyclone 0.6-1 and Else 1.0-0 rc-4 libraries / externals.
I hope that the Purr Data 2.17 / Pd-L2Ork 2.16 developers will integrate them both into their applications.
Their current very old Cyclone library since years is just a dinosaur version!

For a new MIDI project under Pd 0.52.1 / Linux Mint 21 (Ubuntu 22.04 base) I have a major issue with the [else/keyboard] object.
This great object is working as expected when used into a patch but not when displayed in a GOP where all the keys are silent.
If in the GOP you toggle between the 2 zoom levels you get a one shoot refresh of the played notes (from [seq] or external MIDI devices), but nothing in real-time.

Q: Are you aware about this issue ? Any workaround ? Am I doing something wrong?

Thank you.
Joseph

**Comment by porres** [comment]
> I hope that the Purr Data 2.17 / Pd-L2Ork 2.16 developers will integrate them both into their applications.

I gave it up hoping for that :) 

> Are you aware about this issue ? 

no and I still don't get it. Please send a minimal patch that shows the behaviour.

**Comment by joe-rouen** [comment]
Here attached 3 animated GIFs (1 capture each second) of my MIDI patch demonstrating my issue.
Thank you.

![1-keyboard pd still gop](https://user-images.githubusercontent.com/56611993/199869409-6453b255-2faf-4c23-a748-515ad73dbb93.gif)
![2-keyboard pd toggled gop](https://user-images.githubusercontent.com/56611993/199869438-4c527b38-9223-46dc-b2a1-727db936247a.gif)
![3-keyboard pd patch with gop](https://user-images.githubusercontent.com/56611993/199869468-c640ef2e-9473-47ae-b65c-48fefd2b15be.gif)

**Comment by porres** [comment]
hi, I need a minimal patch so I can test, not a gif, I mean the actual file. But make it really really simple, don't send me a complicated complex patch, just a minimal patch that shows the behaviour.

**Comment by joe-rouen** [comment]
Hello Alexandre,

Please find here-attached my Pd patch.

Thank you.
Best, Joseph

= = = = = = = = = =

Le 04/11/2022 à 15:06, porres a écrit :

**Comment by joe-rouen** [comment]
Hello,
Well, I have sent you be email my "simple-midi-player-0120.pd" patch.
Best, Joseph

**Comment by porres** [comment]
cant find in my email, you can upload zipped files here on the comments, it's bewst if you do that

**Comment by joe-rouen** [comment]
The Email system of GitHub is very confusing, at least for me.
So here-attached the ZIP file of my Pd patch.

[simple-midi-player-0120.pd.zip](https://github.com/porres/pd-else/files/9941582/simple-midi-player-0120.pd.zip)

**Comment by porres** [comment]
this is not what I consider a minimal patch :) we just need [keyboard], right? you basically just sent me the patch

**Comment by porres** [comment]
you also have many objects that could be replaced by better alternatives from ELSE and reduce the number of dependencies

**Comment by joe-rouen** [comment]
Here a minimalist but useful patch. Just load a MIDI file and PLAY it!
I just discovered your Else library few days ago!

[else-keyboard-gop-issue.pd.zip](https://github.com/porres/pd-else/files/9943818/else-keyboard-gop-issue.pd.zip)

**Comment by porres** [comment]
have a look at else/midi then ;)

**Comment by porres** [comment]
here's my minimal patch :) 

[keyboard-bug.pd.zip](https://github.com/porres/pd-else/files/9943901/keyboard-bug.pd.zip)

**Comment by porres** [comment]
Anyway, I can reproduce it... incoming notes are not visually updated in a GOP and I'll try to fix it right away. You'll have to wait a while until an update though, around christmas.

**Comment by joe-rouen** [comment]
[else/midi] is an improved version of [cyclone/seq], but it seems missing at least [append( and the Text edit windows.

Thank you for taking care about [else/keyboard] in GOP!

**Comment by joe-rouen** [comment]
[else/keyboard]: Great! Thank you very much!
I will test it asa your update will be publicly available.
This object was really missing for all MIDI users.

**Comment by joe-rouen** [comment]
1- [else/midi]: Based on your suggestion, in my current SMS Vanilla project I have replaced [cyclone/seq] by this one.

2- Unfortunately the 'text' structure is different between the 2 objects: TimeCode + 3 bytes vs TimeCode + 4 bytes. So the .txt files used with [seq] cannot be reused with [midi].

The MIDI .txt files are in my case very useful. One of the application is for my students (from all ages) who are learning MIDI basics. With this approach you can simply create a MIDI file from scratch, no need for external MIDI devices, including every messages and also playing with hex-to-decimal conversion.

3- [append( -> [seq] as per above is very useful. You can build a full MIDI song/file step-by-step either .txt or .mid.

4- [dump( -> [else/midi]: It's not working, no output in the Pd Console.

Thank you.
