### ISSUE TITLE
aubio?

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1371]
@timothyschoen :)

for reference --> https://puredata.info/downloads/aubio/?searchterm=aubio and https://github.com/aubio/aubio

have alternatives for ELSE, maybe...

so, pitch detection, onset detection, beat detection is all nice... slicing audio files in beats is also great

I wonder if this can extract loop region information from audio data, I've been wanting to do that for a while now (actually I was hoping we could do it in Vanilla)... and can this also help loading mp3 and other sound files? that would also be good to have in vanilla (readsf~ and soundfiler)

**Comment by timothyschoen** [comment]
I'd love to see this, you probably have to do some work for loop extraction, but this does give you the tools you'd need for it I suppose.

**Comment by porres** [comment]
some files have loop regions metadata, I would like just that

**Comment by porres** [comment]
there's also a github repo for this https://github.com/aubio/pd-aubio

**Comment by timothyschoen** [comment]
Code looks pretty clean as well, so we could copy-paste this in I guess. Then we only need to check the interface, create helpfiles in the ELSE style, and done.

**Comment by porres** [comment]
yup, should be easy, kinda like using fluidsynth, we just call the functions... the problem is having it as a dependency but you can deal with that :)

**Comment by porres** [comment]
I will definetly rewrite the wrapper and change objects' names and stuff too... make some different design choices later one

**Comment by timothyschoen** [comment]
I've included aubio in projects before, it's very simple

**Comment by porres** [comment]
let's start with 

onset~ detect onsets
pitch~ detect pitch
beat~ detect tempo (beat tracking)

then I'll see other things in aubio we can use

**Comment by porres** [comment]
objects above would be renamed from 

aubioonset~ detect onsets
aubiopitch~ detect pitch
aubiotempo~ detect tempo (beat tracking)

**Comment by porres** [comment]
I guess aubio is part of pd-l2ork or pd-ceammc too maybe?

**Comment by porres** [comment]
yup... ok, we gotta do this now :) ceammc is ELSE's main nemesys, I have to beat them :) hahahhahaha

![Screen Shot 2022-11-04 at 13 46 49](https://user-images.githubusercontent.com/5360142/200030494-c17e99cc-29f2-44d1-9b6b-b3402d28c735.png)

**Comment by porres** [comment]
this is interesting too... getting onset points from arrays

![Screen Shot 2022-11-04 at 13 51 35](https://user-images.githubusercontent.com/5360142/200031607-b00999d7-be74-43cf-ad19-e460de43f6d9.png)

**Comment by timothyschoen** [comment]
> yup... ok, we gotta do this now :) ceammc is ELSE's main nemesys, I have to beat them :) hahahhahaha
> 
> ![Screen Shot 2022-11-04 at 13 46 49](https://user-images.githubusercontent.com/5360142/200030494-c17e99cc-29f2-44d1-9b6b-b3402d28c735.png)

Heh, so if ELSE competes with ceamlib, PlugData is like the ELSE version of pd-ceammc. They don't stand a chance!

**Comment by porres** [comment]
>  PlugData is like the ELSE version of pd-ceammc

exactly :) I'm aware of that :) I'm actually writting about it in a paper I should have written last year

**Comment by porres** [comment]
anyway, can I just expect a PR including aubioonset~ / aubiopitch~ / aubiotempo~ and I take it from there?

**Comment by timothyschoen** [comment]
> exactly :) I'm aware of that :) I'm actually writting about it in a paper I should have written last year

Very nice, look forward to reading it!



> anyway, can I just expect a PR including aubioonset~ / aubiopitch~ / aubiotempo~ and I take it from there?

Yeah sure, I'll have some time later this week.

Btw, I've also found the first bug caused by the naming issues in ELSE/cyclone: [seq] crashes in PlugData when it gets the "read" message, because it uses ELSE's panel_open function instead of cyclone's. I'll probably work on fixing that problem first.

**Comment by porres** [comment]
>  I'll have some time later this week.

👀

**Comment by timothyschoen** [comment]
Hi, sorry, I've been very busy with getting the C++/Daisy exports from PlugData to work, so it's gonna take me a bit longer :(

**Comment by porres** [comment]
wow, tell me about that

**Comment by timothyschoen** [comment]
It's actually kind of epic. I use the [hvcc/Heavy](https://github.com/Wasted-Audio/hvcc) compiler to convert Pd patches to C++ patches for various targets (2 for now, but more are to come). So as long as you use a limited selection of vanilla objects, you can export your patches to code that behaves pretty much identically, it's kinda similar to Max/RNBO. There's a compatibility mode you can enable, that will warn you when you have an unsupported object anywhere in your patch.

I've created a way for installing all the necessary compiler crap with one click, totally noob friendly. Setting this up across 3 operating systems was taking me a long time, but it works! And then it can use that to compile Pd to daisy, and someday also audio plugins and more.

<img width="1054" alt="Screenshot 2022-11-15 at 00 43 03" src="https://user-images.githubusercontent.com/44585538/201791629-968ada1c-c8b4-46b2-bfd2-82628b5b10f6.png">

<img width="1054" alt="Screenshot 2022-11-15 at 00 44 35" src="https://user-images.githubusercontent.com/44585538/201792142-30bb57db-717f-4ab6-abd1-f13db51ff26e.png">

<img width="1054" alt="Screenshot 2022-11-15 at 00 45 02" src="https://user-images.githubusercontent.com/44585538/201792179-f0f04db8-a7d6-4f05-a1da-5e7c78484c92.png">

**Comment by porres** [comment]
wow, I wish I had any idea :)

I thought it could be much simpler to export pd as in libpq (written in C) to a C++ project...

**Comment by porres** [comment]
and them we could use all of vanilla and externals like else/cyclone

**Comment by timothyschoen** [comment]
Yeah, the problem is that that won't work on embedded platforms, which I think is actually a very cool target for Pd. It will also be a but faster than libpd.

I'm also hoping to add plugin and executable exports to PlugData that will just ship a version of PlugData that automatically loads your patch at startup and has no other controls. That will have full vanilla/ELSE/cyclone support of course :)

**Comment by alfonso73** [comment]
Hi guys! Any advancement in including aubio in ELSE and PlugData? Thanks for all your great work!

**Comment by porres** [comment]
dude, this feels like stalking and pressuring :) 

it will happen when it happens ;)

**Comment by porres** [comment]
i'd rather this channel would be restricted to technical discussions

**Comment by alfonso73** [comment]
> dude, this feels like stalking and pressuring :)
> 
> it will happen when it happens ;)

Oh sorry...no pressure at all...just curious.

**Comment by porres** [comment]
> it will happen when it happens ;)

and not happen as well, life is a mystery!

**Comment by porres** [comment]
ok, aubiotempo~ is included as 'beat~' now

**Comment by porres** [comment]
ok, added beat~, now I'm gonna close this and reboot
