### ISSUE TITLE
"Problem" with [scala]

### ISSUE THREAD

**Issue by bazilmuzik** [porres/pd-else#1378]
I don't know how much you explored the scala archieve files, but as you can probably guess it can get a bit messy, not every files have the exact same format (pitches given as ratios, cents, or a mixture of both, etc.).

Well in some cases there are some comments AFTER the tuning definition (line starts with a "!"), and in this specific case [scala] gets confused when outputting the scale. It happens quite frequently with the files beginning with "dudon_" 

Anyway, I attached such a .scl file so you can better see the issue. 

[example.zip](https://github.com/porres/pd-else/files/10013999/example.zip)

**Comment by porres** [comment]
> I don't know how much you explored the scala archieve files

quite poorly :)

**Comment by porres** [comment]
see if my fix takes care of this
