### ISSUE TITLE
[else/keyboard] issue with Pd Max. Zoom - Pd 0.53.1 / Ubuntu Studio 22.04 - Linux Mint 21

### ISSUE THREAD

**Issue by joe-rouen** [porres/pd-else#1395]
Hello Alexandre,

Thank you for your last release v.1.0.0 RC5 fixing GOP and Zooming issues for [keyboard] (#1279 and #1368). It's now working great !

But, I just updated Pd Vanilla to v.0.53.1 and Else library to v.1.0.0 rc5 (Deken) and now I have two new bugs when Pd is in Max. Zoom both in the patch awa in the GOP:
1- [keyboard] is no more responding to mouse entry (this a regression vs rc4) but only to pitch/velocity on its inlets (both max. and min. zooms).
2- Right click on [keyboard] then on Help opens the 'help-intro.pd' file and not the 'keyboard-help.pd' file (this is also a regression), but when with min. zoom it's okay.

Best,

**Comment by porres** [comment]
hi, I need minimal examples to try and reproduce it ;)

**Comment by porres** [comment]
I can see [keyboard] malfunctions when in zoomed mode with mouse click input... should be easy to fix, but it'll take ages for a new release now :) march/april the soonest

**Comment by joe-rouen** [comment]
1- The best minimal example is your 'keyboard-help.pd' file.
2- Well, end of March is my birthday. If your next release will be ready by the beginning of Spring, it will be a nice gift for my 71st anniversary!
Thank you
