### ISSUE TITLE
[keyboard] New feature request

### ISSUE THREAD

**Issue by joe-rouen** [porres/pd-else#1420]
Currently there is only one color (~ red) for the keys (in add to the ~ blue for the central C).

It would be nice to be able to have a different color (fixed or settable) for each MIDI channel (1-16).

Thank you.

**Comment by porres** [comment]
keyboard is unaware of MIDI channel

**Comment by joe-rouen** [comment]
Well, so let me change my request...
I have already a channels filter/selector (All / 1 to 16) at the entry of [keyboard] using [midiparse] and some glue.
It would be useful to be able to dynamically change the color of the keys, but no 'color flag' or similar is available.

Q: Would it be possible to add something like [color $1( to the Inlet 0 of this object?

Note1: the Ceammc's [ui.keyboard] has this capability with [@active_color x y z( but the usage of this external, mainly under GNU/Linux, is not obvious.

Note2: In fact, I'm looking +/- for the kind of behavior of VMPK (Virtual MIDI Piano Keyboard); i.e. one color for one channel.

Thank you.

**Comment by porres** [comment]
> I have already a channels filter/selector (All / 1 to 16) at the entry of [keyboard] using [midiparse]

why do you need midiparse? why not the objects from ELSE like [note.in]?

> Would it be possible to add something like [color $1( to the Inlet 0 of this object?

so you just set the color in general and not for each channel, right?

> [ui.keyboard] has this capability with [@active_color x y z(

Does this ser color in general? What is 'x', 'y' and 'z'?

> I'm looking +/- for the kind of behavior of VMPK (...); i.e. one color for one channel.

that was clear in the first request, but how since the object isn't aware of midi channels? Being able to set the color in general isn't the same thing.

**Comment by joe-rouen** [comment]
So, let's try to rephrase it.
Whatever you use [midiparse] or [note.in] (which is a part of [midiparse]), the principle is the same.
in the Ceammc [ui.keyboard], the x,y and z list is defining the RGB color.

You said: "That was clear in the first request, but how since the object isn't aware of midi channels? Being able to set the color in general isn't the same thing."

So I repeat. I filter the Notes/Channel ([note.in] or [midiparse]) before sending their Pitch/Velocity for a given channel to [keyboard]. Of course as you stated it, this object is not aware about any channel. I'm taking care of it.

If I can change dynamically/live the general key color of the KB, I ask [keyboard] to change its general color to a specific one accordingly to the current selected/chosen channel(s).
16 specific channels + 1 all channels (if channels differentiation is not needed) = 17 general key colors
CH All = default key color or much better a mix of all the 16 colors
CH 1 = color 1 ... CH 16 = color 16

A simplified implementation could be like this one:
[pitch/velocity/channel] from [midiin] or [else/midi] or [cyclone/seq] or others
|
[midiparse] or [note.in] or others
|
[glue for Channels Filter/Color]
|
[color $1 $2 $3( <= subject of my demand depending how it could be implemented in the KB object
|
|/ [list <f, f>(  MIDI Note & Velocity values
|
[else/keyboard]

**Comment by porres** [comment]
> Whatever you use [midiparse] or [note.in]

I ask why you prefer this, if there's a special functionality

I can add colors, but it would be in general, if you have a note playing in channel '4' and you play another on '6', colors will change and both channel '4' and '6' will be of the same color. Unless we make it so that changing the color doesn't affect what's currently being played (which feels weird to me).

**Comment by joe-rouen** [comment]
Why adding something like [color $1 $2 $3( to [keyboard] inlet will affect what's currently played?
It's just changing the color of the keys and not the pitch/velocity values, this is my reading at least.
Am I missing something or is there constraints on [keyboard] side?

[keyboard] Input
Yes, Color will be in General for the whole [keyboard], I understand and I'm taking it in consideration, but if the General Color can be changed dynamically among let say 17 different colors...
I can take care about Channels before by transforming Channel Nbs into Color nbs which, and if added to [keyboard], will make the job.
The Color will be defined by the Channel/Note, not only the note, and if 2 notes or more have the same pitch on 2 or more different channels then only the last used Channel/Note will be displayed at a given time (this is already the case today with one single default color).
So changing the color, in my case, is not affecting what is received on the Input of [keyboard] and then displayed / played on/thru it.
It's how VMPK is working on OMNI mode (one possibility among a total of 7 channel setups).

[keyboard] Output
Now regarding the Output of [keyboard] you are right. If you pressed a key or more (shift) this object doesn't know on which channel.
As I have no access to the inside of this object, the key color will be always the General default Color.
For the notes going through [keyboard], no change versus today behavior.

In one of my projects, I'm managing both the Channel Input and Output of [keyboard] with external glue. So I can define [keyboard] to play Internally (CH -> Color) or Externally (CH) on CH1 to CH16 or on All CHs (OMNI).
It's also used to send the MIDI messages (Note's Pitch & Velocity, PC, PB, AT, CC) to [else/sfont~].

If your are suspicious, in add to [color $1 $2 $3( or whatever else, you could also add a color switch or a [color 0( for freezing any color change Received by [keyboard] (which will be the today behavior).

I hope this clarifies a little bit my demand. :)

**Comment by joe-rouen** [comment]
So to rephrase my request in one sentence:
_If you can easily add the possibility to change on demand / live the general key color of [keyboard], please do it._
Then the users can decide how and for what they can use it in their patches.
Thank you.

**Comment by porres** [comment]
> Why adding something like [color $1 $2 $3( to [keyboard] inlet will affect what's currently played?

why wouldn't it? I have to check the code and see how to not do that as I bet all keys are bound to the same color variable, simple as that. Have you seen the code? Can you really set different colors in ceammc? Anyway, I proposed the idea one could set colors for future active notes but don't really know how easy it would be, and setting general colors is not what you're asking.

**Comment by porres** [comment]
please answer or I'll have to close this

**Comment by joe-rouen** [comment]
In your post -n2 you should be right.
Nevertheless I'm currently testing my, seem to be crazy, idea with Pd Ceammc (Pd 0.51.4 / ceammc 0.9.4) installed as a snap.
I will be back to you during this week-end.

**Comment by joe-rouen** [comment]
Well... [ceammc/ui.keyboard] is not enough clever to keep in memory (latch) the keys color for the previous notes received on one channel when receiving new ones on an other channel. And there is no color / channel management.

You can only change the default keys color. :(
[glue] for filtering the Notes / Channels
| 
[@active_color $1 $2 $3 $4(  with List of Red, Green, Blue values in 0-1 range
|
[ui.keyboard]

Red: 1 0 0 1
Green: 0 1 0 1
Default: 0 0.75 1 1 (light blue)
Blue:  0 0 1 1

So, the decision is yours to close or not this thread. Thanks

**Comment by porres** [comment]
well, I already have it in my list to add the possibility of color change for a while... but it's never a priority, I will close this in favor of that
