### ISSUE TITLE
md files from plugdata

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1434]

**Comment by tomara-x** [comment]
totally recommend! some cool folks did good work there ;)
however, they're still missing a few things i'm planning to do (probably after cyclone) like making sure they all have their method section, and making sure everything is correct and displays right.
currently i fix things as i find them while patching, but that's slow :)

**Comment by tomara-x** [comment]
i think they're looking decent now. where do you wanna put them? i can make a pr in cyclone too if you want

**Comment by porres** [comment]
Anywhere:)

**Comment by tomara-x** [comment]
you can close this now ;)
