### ISSUE TITLE
Missing [bl.imp2~] abstraction

### ISSUE THREAD

**Issue by alfonso73** [porres/pd-else#1439]
Hi! [bl.imp2~] abstraction seems to be missing in else (in vanilla and PlugData to so i guess is missing from the latest ELSE).
best

**Comment by porres** [comment]
this was intentionaly removed as we don't have a decent algorithm for a compiled bandlimited version yet, see https://github.com/porres/pd-else/issues/1288

**Comment by porres** [comment]
hey, actually we got a new compiled [bl.imp2~] object!!!

**Comment by alfonso73** [comment]
That's great! thx!
