### ISSUE TITLE
else/pad doesn't send click 0 messages when behind canvas

### ISSUE THREAD

**Issue by jyg** [porres/pd-else#1459]
I need to intercept mouse messages behind a canvas. When I use else/pad, it doesn't output "click 0" messages when there is a canvas in foreground.
![image](https://user-images.githubusercontent.com/1431894/215790632-c53c6ff8-e08c-4b15-834e-d7799a364717.png)
pd vanilla 0.53.0,  linux

**Comment by porres** [comment]
Upload a patch please

**Comment by porres** [comment]
duplicate of https://github.com/porres/pd-else/issues/918
