### ISSUE TITLE
update to pd-lua 0.11.5

### ISSUE THREAD

**Issue by agraef** [porres/pd-else#1477]
You're still shipping 0.11.3 which has a serious bug. Please update to 0.11.5 (current master).

**Comment by agraef** [comment]
Hmm, why the plugdata label? I've already updated pd-lua to 0.11.5 there. You need to update *your* bundled source. If you still had pd-lua as a submodule, that would be easy as pie, but it shouldn't be too hard anyway. I really urge you to do this asap, because you're shipping a broken version now!

**Comment by porres** [comment]
> why the plugdata label?

to remind me I need to do this before pulgdata's next release in a couple of weeks

**Comment by agraef** [comment]
So you intend to update your pd-lua copy in a few weeks?? After I just told you that the version you have has a critical bug?

That's not great. It shouldn't have taken you more than a few minutes to update your copy. If it wasn't important, I wouldn't have bothered to report it at all.

**Comment by agraef** [comment]
Also, please note again that if you update pd-else for the next plugdata release, this will have no effect whatsoever on the pdlua version that's linked into plugdata right now, because I *already updated that version days ago* (you can see that if you try one of the CI builds from plugdata's develop branch). But it's the ELSE version available right here (and presumably going into Deken at some point) that will be affected.

Anyway, I hope that you reconsider and update your pd-lua copy in a more timely manner going forward. If you can't adjust your workflow so that you update whenever a new pd-lua version comes out, then I'm afraid that our plans to eventually switch plugdata to the ELSE version of pdlua will be infeasible.

**Comment by agraef** [comment]
**Bump.** This is urgent, please fix. Alexandre, I hate that I have to do this, but you keep ignoring me. I'm not going away. This needs to be fixed. Yesterday.

**Comment by porres** [comment]
sorry, didn't mean to ignore, I honestly missed this last message. I blame it on my summer love story and the weekend we had :)

**Comment by porres** [comment]
to be honest, I thought I'd get into lua scripting and maybe offer a new incompatible design like I did with other similar things (like fluid~) - but that seems unlikely to happen and you seem pretty commited and watching this closely. It really just makes sense to get this out of ELSE and we make sure deken has the latest pdlua version... not something we need to do any time soon anyway.

it seems I should have something in ELSE maybe for including a new lua scripting object based on what ofelia offers, that's make sense

**Comment by agraef** [comment]
> It really just makes sense to get this out of ELSE

I'm sure glad that you came to realize this yourself, and I fully agree. In fact I didn't think that the two are such a great match in the first place, so let's get them divorced now before it's too late. ;-) It just complicates things in ELSE and means additional maintenance burden for you, when you should be concentrating on ELSE's core which, honestly, is awesome enough by itself! :1st_place_medal: The only tangible benefit of including pd-lua with ELSE was that it provided a pathway to get pd-lua into Deken, but there other ways to achieve that.

Yes, you merged the latest changes from pd.lua and pdlua.c now, which fixes the most glaring issues, but those files suddenly have the executable bit set which isn't good (and isn't in upstream to be sure). And you entirely missed the tutorial updates in pdlua/tutorial/pd-lua-intro.pdf and tutorial/pd-lua-intro.* going from 0.11.3 and 0.11.5.

With the pd-lua source botched like this, I can't help but recommend, very strongly, that you get this out of ELSE asap. ;-) We just have to remember that we then also need to revert the pd-lua docs to the stuff from the pd-lua submodule in plugdata when plugdata updates its ELSE sources after removal of pd-lua from it.

I'll be glad to provide you with a PR to remove every trace of pd-lua from ELSE (there are also bits and bobs in the toplevel Makefile that need to go). Stay tuned.

**Comment by porres** [comment]
The thing is that I think @timothyschoen needs to get involved in this decision before anything as well. I'm glad to keep it if he thinks it's best, then we work on getting things right instead.

**Comment by agraef** [comment]
We can just point him to https://github.com/porres/pd-else/issues/1477#issuecomment-1429119741 and he should understand. It's not that plugdata will loose anything from this. If anything, the maintenance burden is removed there as well.

> I blame it on my summer love story and the weekend we had :)

Nice, no worries, I understand. But let's get pd-else and pd-lua divorced asap. :)

**Comment by agraef** [comment]
There you go, #1503.
