### ISSUE TITLE
new objects for 'mp3' and other files

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1480]
like [soundfiler]  / [readsf~]

**Comment by porres** [comment]
@timothyschoen already worked on a [readsf~] replacement, which is now [play.file~].

We now need to create a [soundfiler] version to import files to arrays

**Comment by porres** [comment]
I'll just reboot this so it's up on the issue list

**Comment by timothyschoen** [comment]
wow, so this was already planned!

**Comment by porres** [comment]
sure, but now... ---> https://github.com/porres/pd-else/issues/2119
