### ISSUE TITLE
new linux compilation for [sfont~]

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1499]
prior discussion in https://github.com/porres/pd-else/issues/1496

**Comment by porres** [comment]
So, compiled versions I use just to copy when making a new deken release are found here --> https://github.com/porres/pd-else/tree/master/sfont~/sfont-compiled

If I get it correctly, I need a new version for Linux 64 bits, right? Note, I am just supporting now 64 bit versions of macOS/Win/Linux in deken, no more 32 bit versions. And I am also shipping a couple of raspberry pi options. So I'd need a new Linux 64 bits compilation to replace what e have in that folder.

Can you help me with that @reduzent ? Or maybe @agraef  and @joe-rouen?

**Comment by porres** [comment]
Ok, I'm unsure of which raspberry pi versions we're offering and who helped me with that, if @emviveros  or someone else. We should ship compiled versions for amrv6 and armv8, currently I'm supporting these for ELSE - no more armv7

It seems I only have one arm version and I have no idea which one it is...

One way or another we need to recompile and I should update the compiled versions for all supported linux versions in deken: 64 bits, armv6 and armv8

**Comment by porres** [comment]
>  worst case scenario I'll just ship the same version not suited for manjaro.

along with the whatever version I'm shipping for raspberry pi

**Comment by porres** [comment]
the thing is that I use a script @emviveros gave me that runs on a virtual machine. The VM is on linux and I use it to compile and cross compile for windows. And I believe I can't use it to compile sfont~ with the complicated configuration we need, its scripts and all...

or can I? it'd be great if I didn;t depend on anyone 'else' for this

**Comment by agraef** [comment]
Let me chime in here...

> ok, just wanted to say that ELSE rc7 is ready to go

Whatever you do, please remove pd-lua from ELSE *first*. We already discussed this in another PR, and I've done all the work for you, you only need to merge https://github.com/porres/pd-else/pull/1503. Let me just say that I'll be not amused at all if the pd-lua you currently bundle (in the sad inconsistent state it is in) is included in rc7.

> or can I? it'd be great if I didn;t depend on anyone 'else' for this

Sure you can! I'm building not just ELSE, but the entire purr-data (which, on the pd-else branch, also includes all of pd-else) right here on GitHub. You just need to configure GitHub Actions. You could probably use a similar setup to what I have in upstream pd-lua, check my https://github.com/agraef/pd-lua/blob/master/.github/workflows/makefile.yml for starters. pd-lua uses pd-lib-builder, just like pd-else, so it shouldn't be too difficult to port this over.

This would give you readily compiled packages for Linux (Ubuntu 22.04 LTS, x86_64), Mac (universal arm64 + x86_64) and Windows (x86_64), which is a good start. For the Raspbian builds, you'll have to go somewhere else, as GH doesn't offer runners for these. I'm doing my Raspbian packages for purr-data on SUSE's OBS (Open Build Service), but there might be easier options out there. Maybe someone who is more into build farms for Raspberry Pi else can help you out with these.

**Comment by agraef** [comment]
> Mac (universal arm64 + x86_64)

I should add that I'm not entirely sure whether the setup that I use there in the macos-build for pd-lua would work for pd-else, since you probably have dependencies (sfont~ comes to mind), and Homebrew isn't great when building universal binaries or for cross-compiling to arm64. So you might just have the option to build for x86_64 on the Mac, I'm afraid. At least that's what can be done easily on the Mac runners that GH offers, which are all Intel-based AFAICT. I'm sure that this can be solved as well, but it's surely more tricky than what I can do right now.

**Comment by emviveros** [comment]
Ok.. I think the best way to go is using docker. But we need to find docker images suitable for each arch and like run the compiler in yml script.

With docker images is posible setup github action to compile all releases and setup it to make test compilation inside your production machine if convenient.

I dont have much time to setup it, but I will see it in my time. If we have anyone with some experience with it, we can deliver it a little fast

**Comment by porres** [comment]
the thing is that sfont~ uses a complicated script to copy all dynamic libs to specific folders, not sure if we could do it with github (but then what do I know?).

**Comment by emviveros** [comment]
Probably you can. This kind of envyronment is for this kind of problem

**Comment by porres** [comment]
well, I can't try and learn this right now, would need help, I'm busy with cyclone now while I also enjoy last days of beach before carnival :)

**Comment by porres** [comment]
and next week I'll release new versions of else and cyclone, so I won't be able to work on this and I wonder if others can help me, thanks

**Comment by agraef** [comment]
> the thing is that sfont~ uses a complicated script to copy all dynamic libs to specific folders, not sure if we could do it with github (but then what do I know?).

Sure you can run such a script in the github ci. Pretty much everything you can do on a computer after a fresh install of Ubuntu/Mac/Windows, you can do in the runner.

**Comment by charlesneimog** [comment]
I was playing around with github  with Actions, I will try to make it!

**Comment by porres** [comment]
I guess I need to grant someone access and divine power of the repository to help me set it up, right?

**Comment by tomara-x** [comment]
> I guess I need to grant someone access and divine power of the repository to help me set it up, right?

no need. if you're messing with actions everyone can run them in their own fork and send you a pr of the workflow

**Comment by charlesneimog** [comment]
@porres, you did the `localdep_linux` script? 

I was able to compile all pd-else objects for Linux inside Github Actions, but the script is not copying the dynamic libraries, I believe that is because, on Linux of Github Action, the `.so` are inside `/lib/x86_64-linux-gnu/` not just `/lib64`. I am trying to understand `localdep_linux` but could be easier with some help rsrs...

**Comment by porres** [comment]
> you did the localdep_linux script?

nope, those are from IOhaness and original code is on some repository of his, but I remember people did changes to it, @reduzent is the one to shed light here

**Comment by reduzent** [comment]
> @porres, you did the `localdep_linux` script?
> 
> I was able to compile all pd-else objects for Linux inside Github Actions, but the script is not copying the dynamic libraries, I believe that is because, on Linux of Github Action, the `.so` are inside `/lib/x86_64-linux-gnu/` not just `/lib64`. I am trying to understand `localdep_linux` but could be easier with some help rsrs...

Frankly, I don't know what exactly Github Actions do or how they work, respectively what system they use to install all the stuff and perform the compilation. It don't think it is related to stuff being in `/lib/x86_64-linux-gnu`  or `/lib64`. The `localdeps.linux.sh` sripts will include all libraries from any location unless they are specifically mentioned in `exclude_path`. The more likely reason is that not all dependencies of the script are installed on the build systems. I'm pretty confident a log would show the exact reason. Can someone point me to a log of a failed Github Actions run?

**Comment by charlesneimog** [comment]
I do not remember anymore what I had change, but this is already fixed. The problem seems just with `libpcre`. This should be fixed in #1615 .

In this [link](https://github.com/porres/pd-else/actions/runs/4736680391) is the `.zip` with sfont~ working (I believe).

**Comment by reduzent** [comment]
Oh, good to know. I am clearly not up-to-date, then :-)

**Comment by porres** [comment]
I'm lost again, but this seems solved and I'm closing it, right?

**Comment by charlesneimog** [comment]
sim!
