### ISSUE TITLE
Request - method for save/see all parameters of plaits~

### ISSUE THREAD

**Issue by charlesneimog** [porres/pd-else#1514]
Hi, 

I was looking at the plaits~...

And for me, it will be great if a method was added to print all the parameters or save them somehow, I think that would be super useful.

**Comment by porres** [comment]
this will be available when I start making modules out of objects in Pd and in these modules I'll use things like [savestate] and [presets], but you can do that yourself with an abstraction. Not sure I need to build this inside the object or make it output more stuff, but a 'dump' message wouldn't be hard.

**Comment by charlesneimog** [comment]
Yes, I dump message it is enough. Just to see all parameters once.

**Comment by porres** [comment]
ok, dump and print (so it prints on the terminal instead)
