### ISSUE TITLE
adsr flag in help file

### ISSUE THREAD

**Issue by tomara-x** [porres/pd-else#1518]
says in your roadmap: default is now 'log', and log message flag now removed for a new 'lin' method
but the help file is not updated, want me to change that?
![Screenshot_2023-02-19_11-13-11](https://user-images.githubusercontent.com/86204514/219939312-d72f2d5c-0d26-4150-8987-05aeaec5bcf4.png)

**Comment by tomara-x** [comment]
same for asr~
(don't worry, i'm mainly just leaving those here so i remember to do them after i finish the md's)

**Comment by tomara-x** [comment]
bl.vsaw~ has midi method, but not soft. is that a mistake in the help file?

**Comment by tomara-x** [comment]
do all the ones that have the midi and soft sync methods also have them as -m and -soft flags? a bunch of them are missing those in the help files

**Comment by porres** [comment]
> but the help file is not updated, want me to change that?

yes :)

**Comment by porres** [comment]
or just let me handle these

**Comment by porres** [comment]
> do all the ones that have the midi and soft sync methods also have them as -m and -soft flags?

yes

**Comment by porres** [comment]
I guess I fixed these all, please help me revise

**Comment by tomara-x** [comment]
great! will do. push the edits you've made and i'll take a good look at them
