### ISSUE TITLE
Can't use keyboard object

### ISSUE THREAD

**Issue by MR-T77** [porres/pd-else#1522]
I'm using Pd 0.53-2 and have installed else 1.0-0 rc-3. I'm on macOS 13.2.
I have a simple patch with the keyboard object but keep receiving the "... couldn't create" error message.
Else is correctly identified in the path and as a startup library.
Any idea on what may be causing this?

**Comment by porres** [comment]
no idea, but looks like something's wrong with your setup and this is not an ELSE issue

can you create other objects from ELSE?

please get the latest rc6 release btw

**Comment by porres** [comment]
I'm closing this as it seems it's not a real issue and you're not responding fast, but please respond and I'll try to help you then and we can eventually reopen this if it turns out there's a real ELSE issue

**Comment by MR-T77** [comment]
Sorry for the lack of response. It is solved: it was not a else issue, it was just the path. Thank you.
