### ISSUE TITLE
feature request: else/bicoeff have a way of setting the background color

### ISSUE THREAD

**Issue by esaruoho** [porres/pd-else#1565]
hi, i've tried to set this certain type of labeling for each of the 16 loopers, and it would be really nice if these [else/bicoeff] devices (see below screenshot) could have visual differentiation (they're now defaulting to gray for each, so i had to put in toggles with a large number with a certain colour to differentiate them:
<img width="1436" alt="Screenshot 2023-03-12 at 23 30 43" src="https://user-images.githubusercontent.com/4966687/224574862-ae8a6d30-698d-4bb3-b075-aa461cf6fff3.png">

since i'm not sure that was enough, i also added canvases on top of the [else/bicoeff] devices. to, well, "help".
<img width="1184" alt="Screenshot 2023-03-12 at 23 31 44" src="https://user-images.githubusercontent.com/4966687/224574910-b4b7bb8f-4243-4139-b766-f3c8513637b1.png">

but if the bicoeff device itself could be set to a specific colour when initializing, that'd help quite a bit

**Comment by porres** [comment]
closing in favor of https://github.com/porres/pd-else/issues/1364
