### ISSUE TITLE
"play" argument doesn't work on [player~]

### ISSUE THREAD

**Issue by H-MLim** [porres/pd-else#1569]
hi, it seems `play` function doesn't work with only start time like `play 500`-`player~` (as in help file). when only the starting time is set, `player~` plays the whole soundfile no matter which floats I set. (but it still works when set both start and end ms. time) maybe just a bug of object or must it be set with both start/end time?

**Comment by porres** [comment]
that help file example is wrong but the actual documentation and the other messages explain it well, I'm just removing this message
