### ISSUE TITLE
free.rev~ does not accept messaged damp-decay-width-wet settings

### ISSUE THREAD

**Issue by esaruoho** [porres/pd-else#1570]
0.50-2
0.53-2
macOS Monterey 12.6.3, Apple Silicon ARM M1 laptop

<img width="452" alt="Screenshot 2023-03-18 at 23 46 15" src="https://user-images.githubusercontent.com/4966687/226141866-6354616c-6747-4c3b-8696-7a0098f4a146.png">

```
inlet: expected 'signal' but got 'damp'
inlet: expected 'signal' but got 'decay'
inlet: expected 'signal' but got 'width'
inlet: expected 'signal' but got 'wet'
```

**Comment by porres** [comment]
What's the library version? I can assure you this isn't happening in the latest. I already gave you a screenshot on the other issue you opened proving you so and telling you about this (I also said we could use the same closed issue for further discussing it, not to open a new one). Please refer back to that other closed issue.
