### ISSUE TITLE
request: spectrograph~ config for width-height setting upon loading object

### ISSUE THREAD

**Issue by esaruoho** [porres/pd-else#1573]
my usecase is that i have 16 [else/bicoeff] devices in use in my script, and they're set to a smaller width.. 
<img width="1208" alt="Screenshot 2023-03-19 at 15 14 46" src="https://user-images.githubusercontent.com/4966687/226177521-8a2652f2-2064-4cf3-8a71-212241d42a16.png">

so if there was a way to resize spectrograph~ height+width, that'd help. for now, i'm just making my bicoeff objects match the size of spectrograph so i can have the spectrograph underneath the bicoeff and that way see what i'm dealing with :)

**Comment by porres** [comment]
"dim" message or flag in the help file... c'mon, you read it and even corrected the help file :) what's wrong?
