### ISSUE TITLE
request: spectrograph~ add a flag so that if one clicks on a bicoeff that is on top of the spectrograph~ - the spectrograph~ does not act like you clicked the array

### ISSUE THREAD

**Issue by esaruoho** [porres/pd-else#1574]
currently if i use a spectrograph~ underneath a bicoeff - if i click-and-drag around in the bicoeff, the spectrograph~ acts like i've clicked content inside the array.
![spectrograph~ bicoeff](https://user-images.githubusercontent.com/4966687/226181167-088561de-adf5-4bc8-94e4-862b286d7165.gif)

is there a possibility of omitting this type of "drawing" from leaking into the spectrograph~ device? or being shown in the spectrograph~ device

**Comment by porres** [comment]
why is it underneath?

**Comment by esaruoho** [comment]
> why is it underneath?

because while it is underneath, it allows me to see what the results are
![EQ + spectrograph](https://user-images.githubusercontent.com/4966687/226205048-33e24473-e8d7-44b2-8424-b178151685f5.gif)

i.e. i'm using the spectrograph~ below the bicoeff to show me the results of the eq..

**Comment by porres** [comment]
that looks cool

**Comment by esaruoho** [comment]
> that looks cool

thanks! unfortunately, having 16 of them results in the updates getting in very slowly. when i delete all 16 of them and just have one running at 1ms and 128 fft chunk, it is "realtime-feeling", but compared to having 16 of them - 16 results in them being very, very, very sluggish (like in the gif).
yeah, this kind of "peak eq + spectrum analysis" is kinda really what i'm after, as it really helps with figuring out which bits to notch up and down
