### ISSUE TITLE
rad2hz is bugged

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1584]
@timothyschoen does this work in plugdata? what happens is that I get a number that is 4x higher! For some weird reson, divifing 2 pi by 2 pi in my code in the convert function gives me 4 instead of 1, I think only you can figure out what's wrong

**Comment by tomara-x** [comment]
cause it's a macro, so it's just a textual find and replace, so it doesn't care about pemdas. so for example `4 / twopi` will become
```
4/pi*2 = 2.54648    //four divided by pi first, then the result multiplied by 2
```
when in reality you want
```
4/(2*pi) = 0.63662    //four divided by 6.28318...
```

macros are evil

**Comment by porres** [comment]
thanks, I figured it was something like that
