### ISSUE TITLE
numbox~ - possibility to enable 6 or 7 font size?

### ISSUE THREAD

**Issue by esaruoho** [porres/pd-else#1592]

**Comment by porres** [comment]
Why? It's barely readable with font size 8 already...

**Comment by porres** [comment]
you see, pd's font size is 12 and I find it the smallest size acceptable. And Pd's font minimum is 8 already. This is why the font size of numbox~ is also 8 and I already think it's way too small and usable, but at least is of the same size as the minimum allowed font size in Pd... I don't think it makes sense to allow a font size that is smaller than what's possible in Pd...

**Comment by esaruoho** [comment]
ok
