### ISSUE TITLE
feature request: bicoeff could receive control information of EQ gain and location

### ISSUE THREAD

**Issue by esaruoho** [porres/pd-else#1623]
hi, so i'm trying to get circle to talk to bicoeff, but bicoeff only receives messages like Eq or Peaking. would be great if bicoeff could receive control info? :)
i.e. the same kind of data that bicoeff throws out (was it 4 or 6 entries in a list on every movement)
@porres i hope this is the right place

**Comment by porres** [comment]
already listed in the to do list here https://github.com/porres/pd-else/issues/1332

**Comment by porres** [comment]
i know bicoeff needs more attention but right now I am including a knob so there's no much time for this, maybe in the next release
