### ISSUE TITLE
[revdelay~] clicks

### ISSUE THREAD

**Issue by educarvalhu** [porres/pd-else#1631]
There are clicks on [revdelay~]. I think a fade at the beginning and end of reading the file can do the trick.

**Comment by porres** [comment]
foda que é baseado no ffdelay~ então complica, teria que inventar outra coisa

**Comment by porres** [comment]
renomeei o objeto

**Comment by porres** [comment]
closing in favor of https://github.com/porres/pd-else/issues/1636
