### ISSUE TITLE
github actions for mac and change linux's extension

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1640]
@charlesneimog rola mudar a extensão do linux e o que tem que fazer pra rolar o macos tb?

**Comment by charlesneimog** [comment]
Mas pra qual extensão é pra mudar?

O mac eu tive um problema com a compilação do `plaits~`.  

``` bash
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libc++.tbd, missing required architecture i386 in file /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libc++.tbd (3 slices)
ld: warning: ignoring file /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libc.tbd, missing required architecture i386 in file /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libc.tbd (3 slices)
ld: warning: ignoring file /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd (3 slices)
ld: dynamic executables or dylibs must link with libSystem.dylib for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [plaits~.m_darwin] Error 1
```
Vou dar uma olhada de novo.

**Comment by porres** [comment]
> [EDIT] vi que vc ja resolveu isso no makefile.

how so? not really, see https://github.com/porres/pd-else/issues/1556

**Comment by charlesneimog** [comment]
I was wrong, I thought that [this](https://github.com/porres/pd-else/blob/08501ea0de4e29a6b34f91f202cf2d467b1d7628/Makefile#L11) would solve the problem.

**Comment by charlesneimog** [comment]
I added the `else` builder for Mac Inlet, GitHub actions do not provide `M1` or `M2` for now. If possible, let me know if it works (I don't have Mac).

I needed to change two things:

1. update the `pd.lib-builder` for 0.6.0;
2. add this in the makefile of `plaits~`;

``` makefile
define forDarwin
  cflags += -I /usr/include/c++/v1 -stdlib=libc++ -mmacosx-version-min=10.9
endef

```

You can download it here: https://github.com/charlesneimog/pd-else/actions/runs/4953209351

**Comment by porres** [comment]
nao achei onde baixar

**Comment by charlesneimog** [comment]
Hmmm, acho que so eu posso ver... Vou fazer o PR e daí vc da uma olhada se deu boa.

**Comment by porres** [comment]
@charlesneimog eu queria que o linux viesse com a extensão .l_amd64

**Comment by porres** [comment]
> Vou fazer o PR e daí vc da uma olhada se deu boa.

deu boa e veio com a extensão .d_amd6, o que é legal até... agora tem que rolar o M1 com a outra extensão. Tem que ter como cara... como assim o github actions ainda não faz?

**Comment by charlesneimog** [comment]
Não tem, esse aqui é o roadmap do github:

https://github.com/actions/runner-images/issues/2187 

tava tentando ver como o pessoal do plugdata faz, mas não entendi não AHAHAH.

**Comment by porres** [comment]
justamente, lá rola...

**Comment by charlesneimog** [comment]
@wkc1986 could you test if this compilation works on Mac M1?

[plaits-github-actions.zip](https://github.com/porres/pd-else/files/11518164/plaits-github-actions.zip)

**Comment by porres** [comment]
@charlesneimog to pedindo pra um aluno testar, já tá rolando pra todos os objetos?

**Comment by porres** [comment]
@charlesneimog meu aluno testou e rolou! Cadê o resto? rsrs

**Comment by charlesneimog** [comment]
Cara, eu só não sei com os que usam bibliotecas dinâmicas externas, pq ele reclama que estamos usando uma coisa compilada para Intel para compilar para M1 (só sfont~) - quando faz os links.

**Comment by charlesneimog** [comment]
Vou beber agora AHHAHA, quando voltar acabo de fazer pro resto!

**Comment by porres** [comment]
o sfont~ pode ficar de fora por enquanto

**Comment by porres** [comment]
bom, rola fechar isso e só ver de compilar o sfont~ no M1!
