### ISSUE TITLE
Incorrect connection in [note2pitch] >=v1.0-rc7

### ISSUE THREAD

**Issue by xcentricdiff** [porres/pd-else#1644]
I think there is an incorrect connection in [note2pitch] starting with rc7.

The [else/iterate] -> [list fromsymbol] output goes to two [else/slice -1] objects. In the rc7 abstraction, the input to [list tosymbol], and eventual [text search $0-notes], comes from the left output of the second [else/slice -1] object. Thus C#4 becomes [67 35 52], gets sliced once to [67 35] and [52], then the [67 35] gets sliced a second time to [67] and [35]. 

The [list tosymbol] should get [67 35] to correctly generate [symbol C#]. Instead it gets the left output of the second slice and receives just [67]. This incorrectly generates [symbol C].

Since Issues won't accept *.pd files, I have attached a Pd file with the corrected patch disguised as "note2pitch-bugfix.txt
[note2pitch-bugfix.txt](https://github.com/porres/pd-else/files/11481261/note2pitch-bugfix.txt)

**Comment by porres** [comment]
You can send zipped files

**Comment by xcentricdiff** [comment]
<insert>sound of slapping forehead</insert>
Of course. Thanks!!

Mitch

**Comment by porres** [comment]
you could have also sent a PR :)
