### ISSUE TITLE
else/circle (erro size)

### ISSUE THREAD

**Issue by educarvalhu** [porres/pd-else#1646]
Porres, após atualizar a ELSE o circle não está mais respondendo corretamente quando altero o _size_ para qualquer valor além do padrão 127.

https://github.com/porres/pd-else/assets/103229508/d164d050-a6ab-4361-b573-f90f60036e11

**Comment by porres** [comment]
caguei tudo mesmo

**Comment by porres** [comment]
baixa de novo

**Comment by educarvalhu** [comment]
Mano, já baixei e tem otro detalhe nno circle. Apesar de ser o mesmo obj é outro detalhe. Logo aparece aqui com o vídeo.
