### ISSUE TITLE
oldrescale.d_fat seems to be missing in build

### ISSUE THREAD

**Issue by ben-wes** [porres/pd-else#1648]
I just tried to create `[else/slider2d]` with the latest build (rc8) from Deken and get the error that `[else/oldrescale]` couldn't be created.

When I check in the else folder, I can see that there are 3 binaries:
```
oldrescale.d_amd64
oldrescale.l_amd64
oldrescale.m_amd64
```

... but an `oldrescale.d_fat` doesn't seem to exist which is obviously the reason why it won't work on this M2 here.

**Comment by ben-wes** [comment]
just adding to this: when I build it myself here via `make pdincludepate=...`, I get a working `oldrescale.pd_darwin`.

**Comment by porres** [comment]
damn

**Comment by porres** [comment]
I'm deleting this object anyway, I made changes to recale and there was a bug I just fixed, I can use it now

**Comment by porres** [comment]
this binary I mean, it is not an official object
