### ISSUE TITLE
slider2d loses init flags when duplicated or when patch is reloaded

### ISSUE THREAD

**Issue by ben-wes** [porres/pd-else#1649]
Created some slider2ds here with `[else/slider2d -range -1 1]` and found that all parameters are reset to the (obviously default) `127 127 0 127 0 127 ...` when duplicating the object or when the patch is reloaded.

I found that I can use this parameter syntax to fix it for me via `[else/slider2d 127 127 -1 1 -1 1]`, but think it would be great to have this working also for the flags syntax which is mentioned in the help file ... or am I doing sth wrong here maybe?

**Comment by porres** [comment]
yeah, I can reproduce

**Comment by porres** [comment]
actually, the init thing is just wrong

**Comment by porres** [comment]
closing in favor of https://github.com/porres/pd-else/issues/1697
