### ISSUE TITLE
compile [sfont~] and [sfz~] via github actions

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1660]
@charlesneimog ajuda nóis, referência >>> https://github.com/porres/pd-else/issues/1640

**Comment by porres** [comment]
@charlesneimog tá dando uns erros novos que nao tenho ideia, ajuda?

**Comment by charlesneimog** [comment]
Mas oq é?

**Comment by porres** [comment]
Eu que pergunto rsrs não sei

**Comment by charlesneimog** [comment]
Ahhh, e por que você tá usando coisas do Pd 0.54 e ele ainda não está no brew nem no do windows... Quando o pessoal atualizar ele vai parar de dar erros.

**Comment by porres** [comment]
> Quando o pessoal atualizar ele vai parar de dar erros.

já saiu oficialmente o .54, o q falta?

**Comment by porres** [comment]
quem será que coloca o pd nesses lugares @charlesneimog pra quem que eu peço? rs

**Comment by charlesneimog** [comment]
Parece que o Pd para MAC (no brew) já está na versão 0.54 (pelo menos aqui na minha máquina virtual). Já o pd para windows é com o Choco... Parece que é com esse Sanshiro, mas não tenho ideia quem seja.

https://community.chocolatey.org/profiles/Sanshiro 

Para linux nao tem problema....

**Comment by porres** [comment]
mac ainda tá falhando

**Comment by charlesneimog** [comment]
Estranho, ele ainda está instalando o pd0.53-2. Mas aqui já está o 0.54...

![image](https://github.com/porres/pd-else/assets/31707161/ab0e959e-344c-4627-b90f-6ef5295a00dc)

acho que tem que esperar mesmo!

**Comment by porres** [comment]
> acho que tem que esperar mesmo!

CARALHO NAO AGUENTO MAIS ESPERAR

**Comment by porres** [comment]
outra coisa, temos um novo objeto cheio de treta, o [sfz~]!!!!

**Comment by porres** [comment]
e tem esse lance de agora incluir o sfz~ no build, vc ajuda meu amigo @charlesneimog brown?

**Comment by charlesneimog** [comment]
> mas o mac ainda tá zicado tb! ![Screen Shot 2023-07-10 at 13 33 24](https://user-images.githubusercontent.com/5360142/252406256-5e4d99c4-65e6-487c-9aa6-e882d1d58994.png)

Você olhou no seu Mac se quando vc usa o brew qual pd que instala... Esse erro n não estou entendendo, por que na minha máquina virtual o pd que está instalando pelo brew já o 0.54, mas alí ainda é o 53.2

**Comment by porres** [comment]
não vi, mas o que meu mac tem a ver, o github actions vai por conta né?

**Comment by charlesneimog** [comment]
sim, mas no seu mac qual pd instala usando o brew? (pra tentar  resolver).

**Comment by porres** [comment]
eu nem sei instalar pd via brew, bro

**Comment by charlesneimog** [comment]
ahhhhh eu não sei Mac, não sei oq fazer AHAHHAHAH...

O windows o Lucarda vai ter que fazer um PR primeiro... Acho que ele até comentou sobre na lista de emails....

**Comment by porres** [comment]
rolou então de compilar tb o sfont~ pra M1? lembro que faltava isso...

**Comment by charlesneimog** [comment]
Não, estou copiando os arquivos que estão compilados.

**Comment by porres** [comment]
mas o sfz~ rolou né? enfim, mantendo entao esse issue aberto, o que falta pra rolar o sfint~ no M1?

**Comment by charlesneimog** [comment]
Isso, até final do ano o github deve suportar os M1 ahaha

**Comment by charlesneimog** [comment]
Mas tem que testar o sfz~ em um m1

**Comment by porres** [comment]
@charlesneimog do nada o arm mac deu erro e nao acha os lance do 0.54

**Comment by porres** [comment]
parece q voltou do nada tb

**Comment by charlesneimog** [comment]
Tinha instalado o pd53-2. Acho que o pd54 não está em todos os servidores ainda AHAHHA. Sei lá!

**Comment by porres** [comment]
@charlesneimog eu nem sei mais pq esse issue ta aberto, mas enfim, to usando prea outras coisas, hehe, agora tá dando pau no linux... e eu nao consigo entender pq

**Comment by charlesneimog** [comment]
Mas já tá funcionando! Não entendi!

**Comment by porres** [comment]
Nem eu, pode fechar então?

**Comment by charlesneimog** [comment]
Sim, tirando o sfont pra M1 tudo funciona

**Comment by porres** [comment]
então, recapitulando, o que falta mesmo, o fluidsynth atualizar isso pro m1?

**Comment by charlesneimog** [comment]
Isso, precisa compilar ele dos srcs para M1. Se não não e possível fazer o link entre as bibliotecas dinâmicas e o objeto
