### ISSUE TITLE
Couldn't create knob

### ISSUE THREAD

**Issue by apprentiLAB-Suzanne** [porres/pd-else#1661]
Hi ! 
knob doesn't seem to work, at least on Ubuntu 22.10 : 
```
 else/knob
... couldn't create
```
I'm specifying my OS because I know moonlib/mkob works fine in MacOS and doesn't in Ubuntu, not sure if that's relevant.
If I can do anything to investigate this, just tell me :)

**Comment by porres** [comment]
it really seems you dont have the knob installed, there's no error!

**Comment by porres** [comment]
can you create other objects from else?

**Comment by porres** [comment]
i have to close because of no answer to follow up on your issue, please reopen if you can check things and give more information. Again, I just suspect you didn't correctly install ELSE but you can prove me wrong
