### ISSUE TITLE
Windows 11 + pd 0.54 + else1.0rc8 - Unhandled error

### ISSUE THREAD

**Issue by zepadovani** [porres/pd-else#1677]
Oi Porres,

I'm heating the Windows 11 partition of my dual boot machine (so that I can help my students) and just installed Pd 0.54 and else. When starting Pd I get this error in my console:
"-----------
UNHANDLED ERROR: invalid command name ".popup"
    while executing
"$mymenu add separator"
    (procedure "category_menu::create" line 3)
    invoked from within
"category_menu::create .popup"
    ("uplevel" body line 115)
    invoked from within
"uplevel #0 $tclcode"
FAILED TO LOAD C:/Users/zepad/Documents/Pd/externals/else/else-browser-plugin.tcl
-----------"

Please tell me if I can help debug.

**Comment by porres** [comment]
cara, já tá resolvido no "current master", talvez eu lance uma prévia compilada pra quem quiser usar o 0.54, já tenho umas 2 dúzias de objetos prontos pra multicanais mesmo :)

**Comment by porres** [comment]
ps. aqui não dormimos no ponto, rs

**Comment by zepadovani** [comment]
Sim! Tá super útil! Parabéns!

Em qua., 5 de jul. de 2023 11:32, porres ***@***.***>
escreveu:
