### ISSUE TITLE
"cleanup note"

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1678]
see discussion in https://github.com/pure-data/pure-data/issues/2043#issuecomment-1622353993

note that cyclone has the same issue with 'comment'

asking the help of @timothyschoen

**Comment by porres** [comment]
@Lucarda, I'm about to finish the release now and I'm still completely lost about this thing, can you help? you were part of the original discussion in puredata and you're the windows expert.

I'm also requiring the help of PlugData people to see how they're dealing with this over there (hey @timothyschoen , @alcomposer , @tomara-x )

Thanks

**Comment by porres** [comment]
This also concerns Cyclone by the way... and I also need to update it and work on a 0.7.1 release, see https://github.com/porres/pd-cyclone/issues/627

I am using the  "u8_dec" function that Pd Vanilla also uses and I wanna make sure that it works and that I am declaring this symbol correctly...

**Comment by Lucarda** [comment]
I think is best to do what Christof is saying in https://github.com/pure-data/pure-data/issues/2043#issuecomment-1622353993

**Comment by tomara-x** [comment]
i'll look at this if i have time later today

**Comment by porres** [comment]
Thanks @lucarda, I see.... so we use local copies of s_utf.h and s_utf.c and prefix it with else_, e.g. else_u8_dec.

Then we do the same for cyclone and use a different name there, correctly? 

And I should ALWAYS declare s_utf.h and not just for windows, right?

**Comment by porres** [comment]
> i'll look at this if i have time later today

cool, I guess if we figure this out here and you just use ELSE and Cyclone as a submodule, then it should be fine, but I'd hope you could check things out eventually before the next plugdata release

**Comment by Lucarda** [comment]
> Thanks @Lucarda, I see.... so we use local copies of s_utf.h and s_utf.c and prefix it with else_, e.g. else_u8_dec.

> Then we do the same for cyclone and use a different name there, correctly?

> And I should ALWAYS declare s_utf.h and not just for windows, right?

yes, yes and yes :)

PS: I think it's less prone to errors if `s_utf.h` and `s_utf.c` are renamed per repo. something like `else_utf.h` and `else_utf.c` (`cyc_utf.h` and `cyc_utf.c`). this way there should never be a clash with the files in `pd/src`.
