### ISSUE TITLE
rename sfz folders and files

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1682]
![Screen Shot 2023-07-07 at 16 05 57](https://github.com/porres/pd-else/assets/5360142/c13cab33-030b-4223-abf5-26b9ed38e15b)
![Screen Shot 2023-07-07 at 16 06 11](https://github.com/porres/pd-else/assets/5360142/dac08af6-c136-40be-8a75-32225a4ef88c)
@Lucarda

**Comment by Lucarda** [comment]
i think this will be a better pattern with one sfizz~ folder

```
pd-else/
   ├──sfz~/
      ├──sfizz~/
      ├──example.sfz
      ├──Makefile
      ├──sfz~.c
      ├──sfz~install.sh
      ├──sfz~make.sh
      ├──sfz~-help.pd
```

note we can do a rename for `sfz~.c `

is this ok for you?

i'll wait for your answer.

**Comment by porres** [comment]
the subfolder named "sfizz~" is also weird, maybe just "sfizz"

**Comment by porres** [comment]
the sfizz_puredata.c file should also be renamed to "sfz~.c"

**Comment by Lucarda** [comment]
> the sfizz_puredata.c file should also be renamed to "sfz~.c"

yes as i proposed above.

i'll have to leave home and not sure if I get this done in the weekend. may be.

**Comment by porres** [comment]
ok, I updated the code

**Comment by Lucarda** [comment]
i'm ready to start the PR. I prefer to do it while your not working on else.

i'll be awake 8hrs more. it wont take me long. tell me when to start.

:)

**Comment by porres** [comment]
go ahead, I'm done :)

**Comment by Lucarda** [comment]
i'm done with https://github.com/porres/pd-else/pull/1686

**Comment by porres** [comment]
what changed now, how do I build this?

**Comment by porres** [comment]
Alexandres-MacBook-Air:pd-sfizz porres$ make sfizz
make: Nothing to be done for `sfizz'.
Alexandres-MacBook-Air:pd-sfizz porres$ make sfz~
cc     sfz~.c   -o sfz~
sfz~.c:11:10: fatal error: 'm_pd.h' file not found
#include <m_pd.h>
         ^~~~~~~~

**Comment by Lucarda** [comment]
> Alexandres-MacBook-Air:pd-sfizz porres$ make sfizz

why are you standing at `pd-sfizz` instead of `pd-else` ?

**Comment by porres** [comment]
I tried changing pd-sfizz and it all got ruined

**Comment by porres** [comment]
maybe you can also change things at pd-sfizz and give me instructions for both

**Comment by Lucarda** [comment]
oh no, :) yo should be able to figure how to update `pd-sfizz` yourself :)

**Comment by porres** [comment]
> you should be able to figure how to update pd-sfizz yourself :)

I ruined it for good now, it's useless

**Comment by porres** [comment]
anyway, I really have no idea how to build this now with the changes, please help :0

**Comment by porres** [comment]
also, why do we have these copied files?
![Screen Shot 2023-07-10 at 01 23 41](https://github.com/porres/pd-else/assets/5360142/49fc825b-844e-4a62-9778-24fabbd4594a)

**Comment by Lucarda** [comment]
those files are in the original repo https://github.com/sfztools/sfizz-ui/tree/develop/plugins/puredata and i think we should leave them or the build will fail, dunneo, try it.

**Comment by Lucarda** [comment]
> anyway, I really have no idea how to build this now with the changes, please help :0  

standing at `pd-else`:

build:

`make sfizz`

install (always needed)

`make sfizz-install objectsdir=./out extension=d_amd64`

you can also do both (better)

`make sfizz && make sfizz-install objectsdir=./out extension=d_amd64`

the object is placed: `pd-else/out/else`

clean:

`make sfizz-clean`

**Comment by porres** [comment]
cool, I guess we can forget about pd-sfizz
