### ISSUE TITLE
add 'elsefile' dependency to 'sfz~'

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1683]
I wanna use it to enable click to open the soundfont, like I do with [sfont~]

I don't know how to do this in the current makefile

help @Lucarda

**Comment by porres** [comment]
I tried adding it to the code and I got this

![Screen Shot 2023-07-08 at 12 48 14](https://github.com/porres/pd-else/assets/5360142/66d89711-7129-49e4-a645-b37555a80fb8)


weird, because the path is correct and works for sfont~

**Comment by porres** [comment]
works inside "<>"

**Comment by porres** [comment]
doesn't work inside "<>" either

c:12:10: fatal error: 
      '../shared/elsefile.h' file not found
#include <../shared/elsefile.h>

**Comment by porres** [comment]
and for sfont~ and others, I also have to add this to the 'makefile' so I don't know how to deal with this at all

**Comment by porres** [comment]
hope you can help me with this too @Lucarda

**Comment by Lucarda** [comment]
i think i have un ugly idea for this (maybe the only way right now) but i'll first work on https://github.com/porres/pd-else/issues/1682

**Comment by Lucarda** [comment]
the only idea i have about this is that you include all code from `pd-else/shared/elsefile.c` and `pd-else/shared/elsefile.h` into `pd-else/sfz~/sfz~.c`.

**Comment by porres** [comment]
What about copy the files under the folder?

**Comment by Lucarda** [comment]
the problem is that i have no idea how to tell `cmake` to also use this files when making `sfizz~` object.

**Comment by Lucarda** [comment]
may be we have to include all relevant `elsefile` functions but not the "setup" function.

**Comment by Lucarda** [comment]
we also will need a local copy of `g_canvas.h` that we should copy to 
`pd-else/sfz~/sfizz/plugins/puredata/external/pd/include/`

**Comment by porres** [comment]
maybe @timothyschoen can help

**Comment by Lucarda** [comment]
:+1:

**Comment by porres** [comment]
@timothyschoen is this a good time to ask for your help?

**Comment by alcomposer** [comment]
This is a quick fix: https://github.com/porres/pd-else/pull/1764
The current build system copies the sfz~.c to another directory.
So we can change the include path in the copied sfz~.c file to new path

**Comment by porres** [comment]
thanks!
