### ISSUE TITLE
sfz~ fix load scalastring

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1684]
There's code copied from ceammc's sfizz~ that doesn't work. All we need is a string into a built in sfizz_load_scala_string function. The string is tuning name, number of steps and steps in cents in this format "weird\n4\n155\n555\n777\n1111\n" 

So I am trying to build this string from a list of intervals in cents and it is failing, but trying the string above works! The code from ceammc's sfizz~ uses this structure below and if I print the string in the code I do get something that looks exactly like a string that gets accepted, but trying to build this string this way fails somehow (while it must work for ceammc maybe, haven't tested)

    char scale[2048] = "autogenerated scale\n";

    char* pscale = &scale[0] + strlen(scale);

    pscale += sprintf(pscale, "%d\n", ac);

    for(int i = 1; i < ac; i++)

        pscale += sprintf(pscale, "%f\n", atom_getfloat(av+i));

see https://github.com/porres/pd-else/blob/master/sfizz~/sfizz_puredata.c#L107

**Comment by sebshader** [comment]
In order to print an actual backslash character you have to escape it with an additional backslash I think

**Comment by sebshader** [comment]
have you tried adding an additional backslash character before the ```\n```s?

**Comment by porres** [comment]
> it would also help if you point to the original file you're working from on github

https://github.com/uliss/pure-data/blob/d627d8775a5655555b36d58ee0cf810b655cc215/ceammc/ext/src/misc/sfizz_tilde.cpp#L531

**Comment by porres** [comment]
> have you tried adding an additional backslash character before the \ns in the sprintfs?

didnt see why it'd work and it didn't :/

**Comment by sebshader** [comment]
@porres yeah idk thought it might be some weird escaping thing the file format expected or something.

**Comment by porres** [comment]
by the way "weird\n4\n155\n555\n777\n1111" also works (without ending with "\n")

**Comment by sebshader** [comment]
does it work with "weird\n4\n155.0\n555.0\n777.0\n1111.0"?

**Comment by porres** [comment]
good question, it actually works even better!

**Comment by sebshader** [comment]
sorry I'm not on my dev computer rn, what message do you test it with that it fails with?

**Comment by porres** [comment]
i think i see the issue now

**Comment by porres** [comment]
the number of steps in the scale was 1 too many higher :) thanks!

**Comment by eeropic** [comment]
> > to me it looks like the for should start at int i = 0
> 
> It should maybe, but it doesn't, the way I specify scales in cents is that it always starts with "0" cents and this firs one needs to be ignored. Anyway, it's intentional

Should you -1 from ac?

**Comment by porres** [comment]
exactly, that fixed it :)
