### ISSUE TITLE
fix make for sfz~ sfont~ and plaits~

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1688]
@lucarda I moved the folder, I bet it ruined things, can you fix the 'make'  stuff?

thanks

**Comment by porres** [comment]
for sfz~ mostly, of course

**Comment by Lucarda** [comment]
in:

https://github.com/porres/pd-else/blob/master/Makefile?plain=1#L389C1-L390C35

add `Code_source/`

```
plaits:
	$(MAKE) -C Code_source/plaits~ $(plaitsflags)
```

do the rest on every subsequents `$(MAKE) -C`

try it I'm working on other stuff now

**Comment by porres** [comment]
I had tried exactly this before asking for help and it didn't work... I just did it in the commit above and here's what I get

Last login: Tue Jul 11 08:20:48 on ttys000
Alexandres-MacBook-Air:pd-else copy porres$ make sfizz && make sfizz-install objectsdir=./sfz~
++++ info: using Makefile.pdlibbuilder version 0.6.0
++++ info: making target sfizz in lib else
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C Code_source/Compiled/sfz~ system=Darwin 
./sfz~make.sh Darwin
CMake Warning:
  Ignoring empty string ("") provided on the command line.


CMake Error: The current CMakeCache.txt directory /Users/porres/Desktop/Git/pd-else copy/Code_source/Compiled/sfz~/sfizz/build/CMakeCache.txt is different than the directory /Users/porres/Desktop/Git/pd-else/sfz~/sfizz/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/Users/porres/Desktop/Git/pd-else copy/Code_source/Compiled/sfz~/sfizz/CMakeLists.txt" does not match the source "/Users/porres/Desktop/Git/pd-else/sfz~/sfizz/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
CMake Error: The source directory "/Users/porres/Desktop/Git/pd-else/sfz~/sfizz" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
make[2]: *** [cmake_check_build_system] Error 1
make[1]: *** [all] Error 2
make: *** [sfizz] Error 2
Alexandres-MacBook-Air:pd-else copy porres$

**Comment by Lucarda** [comment]
I just pulled [6bf10b3](https://github.com/porres/pd-else/commit/6bf10b31ccd2863c3ec9efcb7d123fa06c6ddc00) and its working for me.

>Alexandres-MacBook-Air:pd-else copy porres$ make sfizz && make sfizz-install objectsdir=./sfz~

whats "pd-else copy" ?

also check that the folders on your computer match the ones this repo. I had to delete `sfz~` and `lua` folders. but i did after a succesfull build (i only built sfiz~)

**Comment by porres** [comment]
I see, thanks. Will try again when I get home

**Comment by porres** [comment]
ok, at home, trying it in the right folder, I also get an error



Last login: Tue Jul 11 08:32:50 on ttys001
Alexandres-MacBook-Air:pd-else porres$ make sfizz && make sfizz-install objectsdir=./sfz~
++++ info: using Makefile.pdlibbuilder version 0.6.0
++++ info: making target sfizz in lib else
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C Code_source/Compiled/sfz~ system=Darwin 
./sfz~make.sh Darwin
CMake Warning:
  Ignoring empty string ("") provided on the command line.


CMake Error: The current CMakeCache.txt directory /Users/porres/Desktop/Git/pd-else/Code_source/Compiled/sfz~/sfizz/build/CMakeCache.txt is different than the directory /Users/porres/Desktop/Git/pd-else/sfz~/sfizz/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/Users/porres/Desktop/Git/pd-else/Code_source/Compiled/sfz~/sfizz/CMakeLists.txt" does not match the source "/Users/porres/Desktop/Git/pd-else/sfz~/sfizz/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
CMake Error: The source directory "/Users/porres/Desktop/Git/pd-else/sfz~/sfizz" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
make[2]: *** [cmake_check_build_system] Error 1
make[1]: *** [all] Error 2
make: *** [sfizz] Error 2
Alexandres-MacBook-Air:pd-else porres$

**Comment by porres** [comment]
just cleaned and recloned, it works :)

**Comment by Lucarda** [comment]
:thumbsup:
