### ISSUE TITLE
Error when loading browser on pd 0.54

### ISSUE THREAD

**Issue by Drugo23** [porres/pd-else#1689]
I get this error when I open pd 0.54.0. I'm on windows 11

-----------
ERRORE NON GESTITO: invalid command name ".popup"
    while executing
"$mymenu add separator"
    (procedure "category_menu::create" line 3)
    invoked from within
"category_menu::create .popup"
    ("uplevel" body line 115)
    invoked from within
"uplevel #0 $tclcode"
IMPOSSIBILE CARICARE C:/Users/Paolo/Documents/Pd/externals/else/else-browser-plugin.tcl
-----------

**Comment by porres** [comment]
known and fixed in current master
