### ISSUE TITLE
rescale and rescale~ bug when first argument is higher then the second

### ISSUE THREAD

**Issue by Drugo23** [porres/pd-else#1690]
if I send a float rescale outputs the first argument countinously when first argument is higher then the second

I'm on pd 0.54.0 , but I get the same error on previous versions too. I'm on Windows 11.

![Screenshot (5)](https://github.com/porres/pd-else/assets/75536565/fdca7430-6371-4268-9d81-1a384dffbefa)

**Comment by porres** [comment]
confirmed
