### ISSUE TITLE
github actions fluidsynth~ fail on linux

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1693]
@charlesneimog

**Comment by charlesneimog** [comment]
Alexandre, to consertando as coisas por aqui, mas como esse sfizz funciona, eu to compilando, ele me da um sfizz.pd_darwin e sfizz.pd_darwin... Mas no help file tem um sfz~?

Como que é esse negocio?

**Comment by porres** [comment]
o negócio é vc ter um objeto sfz~ rsrs

**Comment by charlesneimog** [comment]
pois é, vou renomear

**Comment by porres** [comment]
make sfz && make sfz-install objectsdir=./

**Comment by porres** [comment]
@charlesneimog tem que copiar esses arquivos também 

![Screen Shot 2023-07-23 at 02 28 59](https://github.com/porres/pd-else/assets/5360142/75ae1007-9a1e-49a1-87b6-978e86dbdc5b)

**Comment by porres** [comment]
tá falntando tb a pasta "sf", com arquivos como "sf/Theremin.sf2"

**Comment by porres** [comment]
seria maravilhos tb copiar o tutorial 
![Screen Shot 2023-07-23 at 02 32 34](https://github.com/porres/pd-else/assets/5360142/d4398f02-ba96-46fa-865e-e4bf3615c85a)
