### ISSUE TITLE
github actions for windows

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1703]
@charlesneimog it seems @Lucarda fixed it :) check it out. So, should I be aware of anytihing when 0.54-1 comes out?

**Comment by Lucarda** [comment]
hopefully when 0.54-1 comes out the new Windows installer won't fail to be silent and the Winget package will work again. I think we should then re-implement [choco install](https://github.com/porres/pd-else/blob/0f5ab59917e782dbf514d6227398f32c8b6c036d/.github/workflows/c-cpp.yml#L128C1-L131C39).

this was just a temporary fix so we get the latest Pd into the CI.
