### ISSUE TITLE
avoid heap allocation

### ISSUE THREAD

**Issue by Spacechild1** [porres/pd-else#1704]
Take the following as an example (there are probably more):
https://github.com/porres/pd-else/blob/958c39e7c81aedec88e76f88033bbb2319aa2431/Code_source/Compiled/control/merge.c#L34-L48

You are always allocating the output message on the heap. What you should do instead is allocate on the stack with `alloca` up to a certain limit and only above that fall back to heap allocation. See https://github.com/pure-data/pure-data/blob/c0a7c16c63e86ccc8ce05c8273ccd8aec7ae044c/src/m_private_utils.h#L22-L68

**Comment by porres** [comment]
another one for @timothyschoen ?

**Comment by timothyschoen** [comment]
Sorry, I'm still gonna be very busy with finishing off the next plugdata for the coming month. I might have some time for ELSE after that!

**Comment by Spacechild1** [comment]
@porres It's not rocket science ;-) Just have a look at the source code for `[list append]`, for example.

**Comment by porres** [comment]
where exactly in [list append]? I know it's embarrassing, but I gotta ask, most of these terms are still alien to me and I could use some help while I'm always busy working with other stuff that I find more urgent :/

**Comment by Spacechild1** [comment]
> where exactly in [list append]?

Search for the `ALLOCA` and `FREEA` macros. Again, see https://github.com/pure-data/pure-data/blob/c0a7c16c63e86ccc8ce05c8273ccd8aec7ae044c/src/m_private_utils.h#L22-L68.

> most of these terms are still alien to me and I could use some help while I'm always busy working with other stuff that I find more urgent :/

If you don't know the difference between heap and stack allocation, google it *now* :)

**Comment by porres** [comment]
done by my personal rocket scientist https://github.com/porres/pd-else/pull/2023
