### ISSUE TITLE
[else/function] doesn't copy / paste it's state

### ISSUE THREAD

**Issue by alcomposer** [porres/pd-else#1720]
When a user copy/pastes an [else/function] object, it doesn't copy over it's state:

https://github.com/porres/pd-else/assets/12004932/cc765e56-cfb2-49a6-b544-78858ce5b2e2

I suggest that all ELSE objects with state have the property `Init` as other PD objects have:

https://github.com/porres/pd-else/assets/12004932/b2b0b055-0957-4c77-ae76-4673459e0c62

**Comment by tomara-x** [comment]
it does have an init, but it doesn't have a properties menu
so if you send it [init 1( message it will work as expected and [init 0( to turn it off

**Comment by porres** [comment]
Yup, it has "init", and I was just able to duplicate from the help file and it worked 

![Screen Shot 2023-08-05 at 16 05 24](https://github.com/porres/pd-else/assets/5360142/5a8aa1ac-526b-4529-90cd-4ff4d3b50f46)
