### ISSUE TITLE
memory leak else/sum

### ISSUE THREAD

**Issue by nuoun** [porres/pd-else#1741]
Seems else/sum never releases (some of?) the memory it uses, confirmed on Windows en Linux on RC8, see attached test patch for example where memory use keeps increasing.
[sumtest2.zip](https://github.com/porres/pd-else/files/12330706/sumtest2.zip)

**Comment by porres** [comment]
is it related to https://github.com/porres/pd-else/issues/1704 ?

**Comment by porres** [comment]
another one that I'd hope to get help from @timothyschoen

**Comment by porres** [comment]
@nuoun try the fix https://github.com/porres/pd-else/pull/2023
