### ISSUE TITLE
[fold] isn't working

### ISSUE THREAD

**Issue by LGoodacre** [porres/pd-else#175]
[fold] doesn't seem to be working at all for me--it just outputs the same value, regardless of its arguments. By contrast, [fold~] works fine.

I'm on Ubuntu 17.04.

**Comment by porres** [comment]
weird, looks fine here on macOS

**Comment by LGoodacre** [comment]
Same with [wrap] :(

**Comment by porres** [comment]
seems both have unnecessary "#include <math.h>"

maybe remove these headers and recompile?

**Comment by LGoodacre** [comment]
It worked. However, now [wrap2] is acting like [fold]! Is this intentional? I was expecting it to act like [mod].

**Comment by porres** [comment]
what? 0.o 

well, let me see what the hell might be going on

**Comment by LGoodacre** [comment]
This should narrow it down:

Whichever one I create first, [wrap2] or [fold], the other one will behave like that. So if I create [wrap2], first, then [fold] acts like [wrap2]. If I restart PD and then create [fold], then [wrap2] acts like [fold].

**Comment by porres** [comment]
yeah, they have the same function name ("convert") :/ I guess I need to make it local somehow, haha

**Comment by porres** [comment]
you'll probably experience this with many other objects, I really have a lot of fixing to do about this

**Comment by porres** [comment]
though for they all work : )

**Comment by porres** [comment]
you can try compiling it now and testing it again, please

https://github.com/porres/pd-else/tree/0024d49f8e6f8c6e9264bc29690682b6f330d456

if this works, I'll fix the other objects that might be affected and will draft a new release

**Comment by porres** [comment]
actually... hold on a bit please

**Comment by LGoodacre** [comment]
Yeah, [wrap2] is still folding...

**Comment by porres** [comment]
what? what happened? you tried compiling that and it still didn't work? really? did you close pd and reopened it?

**Comment by porres** [comment]
anyway, I have a new commit to test https://github.com/porres/pd-else/tree/ec5427af201ceee595dc34f5be074ae6aa6ab7f4

**Comment by porres** [comment]
by the way, cyclone [atodb] and [dbtoa] might have the same problem, can you try that?

**Comment by LGoodacre** [comment]
Yes, this latest commit seems to have fixed it. I'll email the zip now. (I had compiled the one you sent previously before reading your request to hold on, hence my message).

I do seem to have the same problem with the Cyclone objects, ie. they give identical output. Note that I'm on Cyclone 0.3-beta-2.
