### ISSUE TITLE
giga.rev crash with size 0 and spread 0

### ISSUE THREAD

**Issue by tomara-x** [porres/pd-else#1753]
https://github.com/porres/pd-else/assets/86204514/5a04f7ec-bad7-4787-88ff-75127ae9c9bb

the backtrace from plugdata said that it's on this line

https://github.com/porres/pd-else/blob/a07753efd86cbfd0fceef17ae28a1402f3dbe512/Code_source/Compiled/signal/giga.rev~.c#L110

limiting to size 1 fixes it, but i'm not sure what you wanna do with it
```
d->idx = (d->idx + 1) % (d->size > 0? d->size : 1);
```

**Comment by porres** [comment]
if you have a fix, just send it, what should I think about? what's going on? what should I decide? what changes?

**Comment by tomara-x** [comment]
i was thinking:
- maybe you have a better way to do it
- maybe you want to limit the size input in the first place (also maybe document those limits?)
- why is the size an int? shouldn't it be float? (it causes clicks on small sizes)

sent pr for this tho

**Comment by porres** [comment]
I would have to look and start from scratch... inthe middle of more than 500 objects, I don't remember anything about this one... so I trust your judgement, you can change things and check, just try to be descriptive in what you're changing... so...

> maybe you have a better way to do it

or maybe not :)

> maybe you want to limit the size input in the first place (also maybe document those limits?)

no idea what you mean, seems like 0 should be a limit...

> why is the size an int? shouldn't it be float?

I guess it should?

**Comment by tomara-x** [comment]
hehehe yeah i figure you have too much work at your hands right now <3

busy brain here too, and not enough experience with this stuff. i'll try my best, but i can't promise anything lol

and yeah sure, if i fix something i'll describe it in detail
