### ISSUE TITLE
two abstractions with else/multi.vsl - send rename to one, PD crashes.

### ISSUE THREAD

**Issue by esaruoho** [porres/pd-else#1776]
am running PD 0.53-2 and `Version: 1.0-0 rc-8; Released may 16th 2023`.

[multivsl_abstractioncrash.zip](https://github.com/porres/pd-else/files/12402943/multivsl_abstractioncrash.zip)

boot up `multivsl_abstractioncrash.pd` which accesses two `dollar1hz.pd`. i'm just trying to use the dollar1hz.pd as an abstraction to be able to point it to send to specific frequencies.
<img width="971" alt="Screenshot 2023-08-22 at 1 10 19" src="https://github.com/porres/pd-else/assets/4966687/e940c91d-3785-43c4-b2c6-5ff3e79775d5">

what would the solution be for this, @porres

**Comment by porres** [comment]
please try to give me an isolated and pretty simple minimal patch for testing

**Comment by esaruoho** [comment]
I gave it but I guess I can try to limit it even further. I'll repost. Since you closed this as wontfix, do I need to open a new one?

**Comment by porres** [comment]
> Since you closed this as wontfix, do I need to open a new one?

it's not closed, so no

> I can try to limit it even further.

please, this is very very complicated still, I need more significant details and things narrowed down. It's hard to debug other people's patches

**Comment by esaruoho** [comment]
@porres ok here you go. this is as simple as i can figure out how to make it.
[multivsl_abstractioncrash_simplified.zip](https://github.com/porres/pd-else/files/12412216/multivsl_abstractioncrash_simplified.zip)
<img width="435" alt="Screenshot 2023-08-22 at 22 14 59" src="https://github.com/porres/pd-else/assets/4966687/d7100577-0da3-416f-9d19-5eb05e4f4022">
<img width="627" alt="Screenshot 2023-08-22 at 22 15 12" src="https://github.com/porres/pd-else/assets/4966687/c101c0f2-6499-4ed7-9c85-09eb536b99c9">
<img width="955" alt="Screenshot 2023-08-22 at 22 15 28" src="https://github.com/porres/pd-else/assets/4966687/7d09474a-6f52-4e68-837d-b876ffece74e">

and upon loading the contents of the zip, you get these errors on the console
```
warning: hzarraymodr0: multiply defined
warning: hzarraymodr0: multiply defined
```

so i'm trying to start using about 16 of these abstractions, and rename them on loadbang, so they definitely follow the naming scheme, so i can output their settings outside of the abstraction. but when i do the simple rename try, it just crashes.

hope this simplification helps.

**Comment by porres** [comment]
> warning: hzarraymodr0: multiply defined

so you have the same name for both abstractions, this is the problem. Just recreate the objects and be sure to not save the abstraction with the object named equally

**Comment by porres** [comment]
I can't do much more because this is an abstraction and an internal issue... and it'd be nice to see how to reproduce the crash in plain vanilla... if this was a coded object I could improve things more

**Comment by esaruoho** [comment]
i do make it crash on plain vanilla, i'm using pd vanilla. 

the problem seems to be that the object in question (the multi-vsl) inside the abstraction, is named the same name as the other object in the other abstraction. are you saying that i need to put in a $0 into the name of the multi-vsl object and then just use the inlet to send the rename message so that it matches what is required?

**Comment by ben-wes** [comment]
@esaruoho I'm not sure if I can support here since your example doesn't crash for me (testing on Windows 11 with Pd 0.54.0).

But if I get the discussion correctly, the confusion seems to stem from the way you duplicated your `multi.vsl`s with a name (`hzarraymodr0`) already set. Wouldn't it help if you initialized them directly with a name flag (`-name $0-whatever`)? Or the other option should probably be to duplicate them before you set a name via a message (while they still have their internal, unique name).

Also, for whatever reason, your left `multi.vsl` instance seems to be corrupt in a way that the internal array is of length 8 while it has 11 sliders (I get `[buffer]: index out of range` there). I think it might be easiest if you initialized your 16 objects with correct init values like this here?:

```
else/multi.vsl -n 11 -name $0-hzarraymodr0 -dim 140 127 -range 0 1
else/multi.vsl -n 11 -name $0-hzarraymodr1 -dim 140 127 -range 0 1
...
else/multi.vsl -n 11 -name $0-hzarraymodr15 -dim 140 127 -range 0 1
```

**Comment by esaruoho** [comment]
@ben-wes thanks, i'll try that! i'm hoping i can get it going. i'm using the multi.vsl's in abstractions cos i want other details to default to a specific frequency etc (i.e. that's why 222 and 333 are there for the abstraction itself).
but i'll be sure to try this stuff and see how it works. thanks!

**Comment by esaruoho** [comment]
@ben-wes thanks for the suggestions. i ended up just doing the edits using a text-editor:
```
#X obj 700 118 else/multi.vsl 140 137 0 0.5 11 hzarraybangr\\\$1 empty empty 255 255 255 220 220 220 0 0 0 1 0 0 holder holder 0 0 0 0 0 0 0 0 0 0 0;
#X obj 700 272 else/multi.vsl 140 127 0 6 11 hzarraymodr\\\$1 empty empty 255 255 255 220 220 220 0 0 0 1 0 0 holder holder 0 0 0 0 0 0 0 0 0 0 0;
```

and now it works without crashing. thanks for the assists!
