### ISSUE TITLE
[knob] weird int/float issues

### ISSUE THREAD

**Issue by nuoun** [porres/pd-else#1794]
![Untitled](https://github.com/porres/pd-else/assets/10226424/fdcf8996-d9e2-4e5b-80b9-5a201091b9a4)
Hoping the screenshot showcases the issue well enough how the output of these otherwise identical knobs is weirdly different depending on if they're dragged from bottom or top in down or up direction and what range they're in. Also [int] rounding down some values Pd thinks are integers anyway seems really bizarre even.

I don't really have an explanation for this but I guess it has to do with the fact that these size 50 knobs actually have 101 steps rather than just 100 and that this somehow does not result in equal steps even with 0-100 min/max values.

Tested on RC8 & RC9 on Win and linux with same issue everywhere.

**Comment by porres** [comment]
of course it's 101 steps... for 100 steps you need a 0 - 99 range.... so what's wrong?

**Comment by nuoun** [comment]
But it's not the min/max value that determines the number of steps, it's the graphic size of the knob. A size 60 knob from 0 - 1 range would still be 121 steps, with floats for every other value but any range that aims to get just integers does not seem to work.
Take a look at what [int] does to these integers or how inconsistent the output values are, something just seems to break.

**Comment by porres** [comment]
Can you upload a minimal zipped patch with comments and stuff?

**Comment by nuoun** [comment]
[knobdemo.zip](https://github.com/porres/pd-else/files/12440827/knobdemo.zip)

**Comment by porres** [comment]
I don't know what the real issue is, if it is the fact that [int] gives a seemingly wrong and unexpected value, this has a very clear explanation, rounding errors because of the float precision. You can just use [rint] instead.

if so, I can just close this issue, as to [knob] giving a "precise" integer output, I guess this will work better when we have 64 bit precision instead.

**Comment by nuoun** [comment]
It just seems weird to me that it's basically impossible to have a slider do these weirdly hidden extreme floats while knob is kinda all over the place with them but I'll just shut up about that. Also rint is really neat.

One final thing, since discrete mode really seems the best solution to just have predictable output values, maybe not drawing the ticks could be a setting like it is for arc now? (Drawing lots of ticks does make knobs kinda ugly imo.)

**Comment by porres** [comment]
even in sliders, ints come out only in a very specific setting (and not the default one by the way) and I don't know why that happens better than in knob, maybe we can improve the rounding internally. One way or another you have to deal with the fact that it's outputting floats
