### ISSUE TITLE
actions failing

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1798]
@charlesneimog eu removi o folder 'libpd' e agora o Linux não acerta a compilation, como arrumar isso?

**Comment by tomara-x** [comment]
need help here?

**Comment by porres** [comment]
yup, and this looks simple, just remove the deleted folder... I'd actually like to learn where to edit and deal with this.

**Comment by tomara-x** [comment]
it's in the actions script `.github/workflows/c-cpp.yml` (it starts with a dot, so it's hidden folder)

i just removed this line here, cause libpd doesn't exist anymore

https://github.com/porres/pd-else/commit/b633a35ab9a088cf7525edaae7411bac5ad52a7a#diff-a6b2b0a5a900a2b301f746f7bafdce303c6c647e00ade3ee28e8f8ebea11c7a5L89

and changed this cause you moved `extra_source` to inside of `Compiled`

https://github.com/porres/pd-else/commit/b633a35ab9a088cf7525edaae7411bac5ad52a7a#diff-a6b2b0a5a900a2b301f746f7bafdce303c6c647e00ade3ee28e8f8ebea11c7a5R91

and then just replaced `signal` with `audio`

**Comment by porres** [comment]
thanks
