### ISSUE TITLE
[dir] allow "~" for home directory

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1803]

**Comment by porres** [comment]
just added this, can you test on windows 32 and 64 bits @Lucarda ?

**Comment by Lucarda** [comment]
It works for me with `[open ~(`. only tested on w64 but it should work also on w32.

![dir](https://github.com/porres/pd-else/assets/25239522/30cd2c04-173e-4064-8802-c0b0204f6e05)

**Comment by porres** [comment]
@Lucarda my concern comes from here you know... https://github.com/porres/pd-else/blob/master/Code_source/Compiled/control/dir.c#L258

**Comment by Lucarda** [comment]
yeah, thats an `ifdef` for Windows and it works.

i can do a w32 build but it will be the same. give me 15' ...

**Comment by Lucarda** [comment]
tested to work correctly in Win32.

for your peace of mind:

```
    #ifdef _WIN32
        this code is for Windows, the compiler has other means to tell which arch is compiling for.
    #else
        this code it's not for Windows
    #endif
```

**Comment by porres** [comment]
thanks a lot
