### ISSUE TITLE
[canvas.active] reports 0 with a right click to the canvas (Ubuntu)

### ISSUE THREAD

**Issue by LGoodacre** [porres/pd-else#181]
I've mentioned this before--the new [window] object send me a 0 whenever I right click on the canvas. This is immediately testable from the window-help.pd patch. It sounds like it's platform specific; I'm on Ubuntu 17.04.

Note that the same bug affects the [cyclone/active] object, I would assume for the same reason.

**Comment by porres** [comment]
yeah, we gotta fix this for both :)

**Comment by porres** [comment]
can you also report a bug on cyclone's repository?

**Comment by porres** [comment]
This has been fixed in the last release or so...
