### ISSUE TITLE
github actions download for linux is bad

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1819]
@charlesneimog eu usei os binários dos actions no deken e dois caras disseram que deu merda e não rolava nada...

**Comment by porres** [comment]
eu refiz e usei binários que gerei numa VM... mas não consigo fazer isso pro plaits~, sfont~ e sfz~

**Comment by charlesneimog** [comment]
mas que merda? Acabbei de baixar os objetos do ultimo commit. Eles estão funcionando....

EDIT.: de fato o `sfont~` não ta funcionando. Mas os demais sim.

**Comment by porres** [comment]
então, na lista do pd outro falou que deum várias zicas também em vários objetos... criei novos binários numa VM e deu certo pra ele

**Comment by porres** [comment]
o plaits~ e o sfz~ eu usei do actions e funconou pra ele! O sftont~ to usando um antigo

**Comment by charlesneimog** [comment]
mas ele nao falou quais zicas, erro de biblioteca dinamica?

**Comment by porres** [comment]
copiou o erro na lista do pd, vários objetos deu "couldn't create"

**Comment by charlesneimog** [comment]
copia esses erros aqui pra mim, dai verifico aqui... Daí resolvo pro Linux

**Comment by porres** [comment]
Thanks for such a great external. Just a note that in Ubuntu 22.04 when trying to load voices~ help file I get the following messages in my console. It seems a number of objects don't have .pd candidates in the else directory including those showing up as not loading below. Not sure whats up here. Thanks for any suggestions. I'm using PD version  0.54.0 . Many of the objects do work however.

lse/voices 1 1
... couldn't create
else/wrap2
... couldn't create
else/wrap2
... couldn't create
else/wrap2
... couldn't create
else/voices
... couldn't create
else/voices 1 1
... couldn't create
else/wrap2
... couldn't create
else/wrap2
... couldn't create
else/wrap2
... couldn't create
else/sum~
... couldn't create
else/vu~
... couldn't create
else/vu~
... couldn't create
else/vu~
... couldn't create
else/vu~
... couldn't create
else/voices
... couldn't create
else/wrap2~
... couldn't create
else/wrap2 -0.5 0.5
... couldn't create
else/unmerge 2
... couldn't create
else/unmerge 3 3
... couldn't create
else/wrap2
... couldn't create

**Comment by porres** [comment]
era isso, um monte de objeto nao rolando, e no facebook teve o outro falando do sum~... estranho que funciona td a vc...

**Comment by charlesneimog** [comment]
Estranho mesmo, será que não foi um caso isolado não? Por que aqui o voices~ ta normal.......... 

Vai entender mano

**Comment by porres** [comment]
qual teu sistema linux?

**Comment by charlesneimog** [comment]
Eu uso o Fedora

**Comment by porres** [comment]
foda-se isso e deu? :)

**Comment by charlesneimog** [comment]
Cara, eu formatei meu computador, só fluidsynth que não funciona. O cara deve ter feito merda e culpa o PD e seus objetos ajahaha
