### ISSUE TITLE
[presets] help - couldn't create else/pmosc~

### ISSUE THREAD

**Issue by ben-wes** [porres/pd-else#1950]
When I looked through the help patches of [presets], I found that there seems to be a missing `[else/pmosc~]` object in the example abstractions in [pd advanced] > [pd abstractions].

![image](https://github.com/porres/pd-else/assets/1923787/2fa480cc-7f6b-45a8-98bd-2b33562aed06)

**Comment by porres** [comment]
yaeah, known issue, object has been renamed and I missed this

**Comment by porres** [comment]
it's just pm~ now
