### ISSUE TITLE
All_objects.pd crashes PD- 0.54.1 on MacBook M1 Pro with Ventura 13.6.2

### ISSUE THREAD

**Issue by seppog** [porres/pd-else#1953]
opening All_objects.pd crashes PD- 0.54.1 on MacBook M1 Pro with Ventura 13.6.2. Anything else seems to work so far. Also crashed students Intel MacBook Pro with Ventura 13.6.2

**Comment by porres** [comment]
I don't have a machine to test or try to reproduce. They all work fine on my mac intel, old and new OSes. It's be great if you could find which object crashes :)

**Comment by seppog** [comment]
Thinks its more complicated ;) deleted all up to line 115, still crashed (just pdFFT pdGUI and switch~) are there, deleted pdGUI, loaded in 0.54-1, opened again (in plug data) deleted only pdGUI - still crashes, so I'm still searching. And it doesn't give any crash information, just closes pd 0.54-1 (btw also closes 0.54-0).

**Comment by seppog** [comment]
ok, started to open all help files etc.. so far all-guy-key.pd and besides All_objects.pd closes pd instantly on my M1. Did test down to from above-help.pd to canvas.zoom , will continue next days..

**Comment by seppog** [comment]
sorry, all-guy-key.pd was one of my striped down All_objects.pd file... so didn't find any till now...

**Comment by porres** [comment]
> so found first object: midi.in crashes pd 0.54.1 (with no midi devices in settings, and with midi device) Mac Book M1 Pro (6) 32GB

can u find more? :) and open a new issue for this one?

**Comment by seppog** [comment]
continue to search and will open new issue as soon as I find a new one...

**Comment by porres** [comment]
closing in favor of https://github.com/porres/pd-else/issues/1988
