### ISSUE TITLE
mov.rms~ outputs dBFS by default, should be [0:1]

### ISSUE THREAD

**Issue by bapch** [porres/pd-else#1956]
Hey
I upgraded to PlugData 0.8.2, shipped with Else 1.0-rc10 and one of my patches has its gain reduction all messed up because of it.
It had several [mov.rms~ 64], and i can get the original behavior by changing them to [mov.rms~ -lin 64].
I think you altered mov.rms~ to output dBFS by default. Am i mistaken to think that it should output [0:1] by default, being an "rms" object ?

**Comment by porres** [comment]
> I think you altered mov.rms~ to output dBFS by default.

yup sorry, this was for consistency, and when the plugdata final version is out (1.0) I will compromise to not try and fix anything because of something like that.

but anyway, I don't understand your problem or the issue

**Comment by bapch** [comment]
My issue is that the default behavior changed, which broke my calculation. If it doesn't change anymore, i'm good ! Thx
