### ISSUE TITLE
(Linux) [wavetable~] / [bl.wavetable~] : offset message doesn't work when interpolation is set to none

### ISSUE THREAD

**Issue by bazilmuzik** [porres/pd-else#1986]
To view the problem:

In the objects' respective help files, open [pd size; offset], create a "none" message and connect it to [wavetable~]/[bl.wavetable~]. Then, when you move the horizontal slider, you will see that the table isn't updated. 

I don't know what happens under the hood, it is also possible that the problem comes from "size".

**Comment by porres** [comment]
already had been fixed....


and then, after being fixed...

offset and size are now removed (bad fucking max influence those were, fuck max)
