### ISSUE TITLE
actions

### ISSUE THREAD

**Issue by porres** [porres/pd-else#2019]
@charlesneimog

![Screen Shot 2024-01-31 at 02 02 05](https://github.com/porres/pd-else/assets/5360142/1535e729-a9fa-401d-8c80-36745d05b96f)

**Comment by porres** [comment]
posso fechar?

**Comment by charlesneimog** [comment]
sim!

**Comment by porres** [comment]
legal, mas anda dando muito erro e ta chato, rs

**Comment by porres** [comment]
e como anda o python?

**Comment by charlesneimog** [comment]
Ta indo, o Estevan ta me reportanto um monte de bug no Mac rsrsrsrs. Resolvendo isso vai faltar testar direito no Windows.
