### ISSUE TITLE
BUG : Opening [order] help crashes PD 

### ISSUE THREAD

**Issue by alfonso73** [porres/pd-else#202]
Hi.
opening [order] help crashes and quits pd (vanilla 0.48.1 Win64)

**Comment by porres** [comment]
hi, what's your exact version of else? please

**Comment by alfonso73** [comment]
Hi @porres ! 
I'm running 1.0beta8

**Comment by porres** [comment]
I don't have any issues in macOS.

well, [order] is a vanilla abstraction, and it does work for you, right?

the help file also creates other objects from else that depend on [order], they are:

[else/resonbank~], [else/resonbank2~], [else/oscbank~],  [else/bpbank~]. The only thing I can think of is that these loading this objects may crash Pd for you. Can you try them?

**Comment by alfonso73** [comment]
@porres The culprit is oscbank~. As soon as i instantiate it PD quits.

**Comment by alfonso73** [comment]
btw [order] works fine.

**Comment by porres** [comment]
just to confirm, do the other "bank" objects work fine?

**Comment by alfonso73** [comment]
this is what i have if i instantiate [oscbank2~]

tried C:/Users/fremen/Documents/Pd/oscbank2~.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/oscbank2~.dll and failed
tried C:/Users/fremen/Documents/Pd/oscbank2~/oscbank2~.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/oscbank2~/oscbank2~.dll and failed
tried C:/Users/fremen/Documents/Pd/oscbank2~.pd and failed
tried C:/Users/fremen/Documents/Pd/oscbank2~.pat and failed
tried C:/Users/fremen/Documents/Pd/oscbank2~/oscbank2~.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/oscbank2~.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/oscbank2~.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/oscbank2~/oscbank2~.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/oscbank2~/oscbank2~.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/oscbank2~.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/oscbank2~.pat and failed
tried C:/Users/fremen/Documents/Pd/externals/oscbank2~/oscbank2~.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/cyclone/oscbank2~.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/cyclone/oscbank2~.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/cyclone/oscbank2~/oscbank2~.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/cyclone/oscbank2~/oscbank2~.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/cyclone/oscbank2~.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/cyclone/oscbank2~.pat and failed
tried C:/Users/fremen/Documents/Pd/externals/cyclone/oscbank2~/oscbank2~.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/oscbank2~.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/oscbank2~.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/else/oscbank2~/oscbank2~.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/oscbank2~/oscbank2~.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/else/oscbank2~.pd and succeeded
tried C:/Users/fremen/Documents/Pd/oscbank2~.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/oscbank2~.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/cyclone/oscbank2~.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/oscbank2~.pd and succeeded
tried C:/Users/fremen/Documents/Pd/externals/else/else/order.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/else/order.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/else/else/order/order.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/else/order/order.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/else/else/order.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/else/order.pat and failed
tried C:/Users/fremen/Documents/Pd/externals/else/else/order/else/order.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/order.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/order.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/else/order/order.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/order/order.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/else/order.pd and succeeded
tried C:/Users/fremen/Documents/Pd/externals/else/else/order.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/order.pd and succeeded
tried C:/Users/fremen/Documents/Pd/externals/else/else/order.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/order.pd and succeeded
tried C:/Users/fremen/Documents/Pd/externals/else/else/order.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/order.pd and succeeded
tried C:/Users/fremen/Documents/Pd/externals/else/else/order.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/order.pd and succeeded
tried C:/Users/fremen/Documents/Pd/externals/else/else/break.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/else/break.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/else/else/break/break.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/else/break/break.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/else/else/break.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/else/break.pat and failed
tried C:/Users/fremen/Documents/Pd/externals/else/else/break/else/break.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/break.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/break.dll and succeeded
tried C:/Users/fremen/Documents/Pd/externals/else/else/order.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/order.pd and succeeded
tried C:/Users/fremen/Documents/Pd/externals/else/else/order.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/order.pd and succeeded
tried C:/Users/fremen/Documents/Pd/externals/else/else/order.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/order.pd and succeeded
tried C:/Users/fremen/Documents/Pd/externals/else/else/order.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/order.pd and succeeded
tried C:/Users/fremen/Documents/Pd/externals/else/./oscclone2.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/./oscclone2.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/else/./oscclone2/oscclone2.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/./oscclone2/oscclone2.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/else/./oscclone2.pd and succeeded
tried C:/Users/fremen/Documents/Pd/externals/else/./oscclone2.pd and succeeded
tried C:/Users/fremen/Documents/Pd/externals/else/./else/sine~.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/./else/sine~.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/else/./else/sine~/sine~.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/./else/sine~/sine~.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/else/./else/sine~.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/./else/sine~.pat and failed
tried C:/Users/fremen/Documents/Pd/externals/else/./else/sine~/else/sine~.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/sine~.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/sine~.dll and succeeded
tried C:/Users/fremen/Documents/Pd/externals/else/./else/float2sig~.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/./else/float2sig~.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/else/./else/float2sig~/float2sig~.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/./else/float2sig~/float2sig~.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/else/./else/float2sig~.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/./else/float2sig~.pat and failed
tried C:/Users/fremen/Documents/Pd/externals/else/./else/float2sig~/else/float2sig~.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/float2sig~.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/float2sig~.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/else/float2sig~/float2sig~.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/float2sig~/float2sig~.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/else/float2sig~.pd and succeeded
tried C:/Users/fremen/Documents/Pd/externals/else/./else/float2sig~.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/float2sig~.pd and succeeded
tried C:/Users/fremen/Documents/Pd/externals/else/loadbanger.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/loadbanger.dll and succeeded
tried C:/Users/fremen/Documents/Pd/externals/else/./else/float2sig~.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/float2sig~.pd and succeeded
tried C:/Users/fremen/Documents/Pd/externals/else/./else/float2sig~.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/float2sig~.pd and succeeded
can't resize to zero or negative number; setting to 1
... you might be able to track this down from the Find menu.
tried C:/Users/fremen/Documents/Pd/externals/else/else/args.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/else/args.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/else/else/args/args.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/else/args/args.dll and failed
tried C:/Users/fremen/Documents/Pd/externals/else/else/args.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/else/args.pat and failed
tried C:/Users/fremen/Documents/Pd/externals/else/else/args/else/args.pd and failed
tried C:/Users/fremen/Documents/Pd/externals/else/args.m_i386 and failed
tried C:/Users/fremen/Documents/Pd/externals/else/args.dll and succeeded

**Comment by alfonso73** [comment]
If i try to open [oscbank2~] help PD just quits

**Comment by alfonso73** [comment]
All the various filter banks [else/resonbank~], [else/resonbank2~],[else/bpbank~] work just fine.

**Comment by alfonso73** [comment]
@porres Deleted the whole else folder and reinstalled...same crashes with [oscbank~].
As before [oscbank2~] instantiate correctly andi can correctly open the abstraction. But if i try to open the help i have a crash and pd quits as when i instantiate [oscbank~]. Porbably in the help file of [oscbank2~] there's an instance of [oscbank~].

**Comment by porres** [comment]
> in the help file of [oscbank2~] there's an instance of [oscbank~].

yup.

Well, I just uploaded a fix for [oscbank~] for a bug I found that might be related or not, it's worth to have a try: https://github.com/porres/pd-else/blob/7763c0ddb4a48a1a8eac2b373b4feae2c251767d/help/Abstractions/oscbank~.pd

Other than that, the [oscbank~] is the only object in else that uses the newly added [inlet2~] object, maybe you're having a problem with it. Try and see if you can instantiate it, or try to  open its help file (from the else folder).

**Comment by alfonso73** [comment]
@porres I guess you found it! I can't instantiate inlet2~ and pd suddenly quits.

**Comment by porres** [comment]
bug referred in https://github.com/porres/pd-else/issues/203
