### ISSUE TITLE
[circle] name clash

### ISSUE THREAD

**Issue by 60-hz** [porres/pd-else#2030]
[circe] has a name clash with gem library classic geometry primitive.

**Comment by porres** [comment]
this is not an ELSE issue :)

**Comment by 60-hz** [comment]
I think reducing name clash as soon as possible in this environnement is important, in Plug data for example, which is shipped with both else and Gem, this is becoming an issue.

**Comment by porres** [comment]
Ask Gem people to change then :)

Ok, seriously, there is no issue in Pd or Plugdata (based on Pd), or Pd-ceammc, or Pd-l2ork/Purr Data, dealing with objects from different libraries with the same name is common and is not an issue anywhere, least of which a problem about ELSE

**Comment by porres** [comment]
I had tried to see if plugdata can't manage this somehow but it can pretty nicely, but you think there is a problem, you can open an issue there

**Comment by 60-hz** [comment]
I think that avoiding name's conflict in a "education oriented" pd distribution would be nice.
It is not a pd-else issue, but since pd-else is at the heart of plugdata, I posted it here.

**Comment by porres** [comment]
I will not respond in this issue anymore, any other further discussion can be made in the plugdata github as I have already suggested and as you have in fact already did...
