### ISSUE TITLE
Objeto [wt2d~] ausente na Else 1.0-0 rc-11

### ISSUE THREAD

**Issue by emviveros** [porres/pd-else#2031]
![Captura de Tela 2024-02-22 às 22 47 08](https://github.com/porres/pd-else/assets/3089536/799ceccb-c7b6-45ef-a143-09d4f2ce1b1f)

**Comment by porres** [comment]
sytema operacional? o objeto tá lá? o que aparece no terminal? qual versão do Pd? Tá com a versão correta da ELSE (rc11)? etc, etc?

**Comment by porres** [comment]
sabe que funciona perfeitamente aqui né :)

**Comment by emviveros** [comment]
Sabe que desinstalei e reinstalei a ELSE rc-11 para fazer um reporte decente e agora também funciona aqui! Preciso fazer isso mais vezes!

Final:
Não existe nenhum problema com [wt2~], talvez algum problema tenha ocorrido na primeira instalação que fiz na ELSE e com uma reinstalação foi resolvido.

Valeu!

**Comment by porres** [comment]
brinca agora entao :)
