### ISSUE TITLE
Some help files cannot be found when using namespace

### ISSUE THREAD

**Issue by 60-hz** [porres/pd-else#2046]
In plug data, asking help files of some object in help patches return "Couldn't find help file" when using namespace.

-----

Scenario 1 example:

- Create a new patch
- [else/amean] -> help
- "Couldn't find help file"

-----

Scenario 12example:

- Create a new patch
- [amean] -> help
- [else/gmean] -> help
- "Couldn't find help file"

-----

PlugData last nightly
MacOSX Sonoma 14.3.1

**Comment by porres** [comment]
you need to post this in the plugdata repo

**Comment by 60-hz** [comment]
oh, yes sorry closing it...
