### ISSUE TITLE
polyphonic / monophonic 

### ISSUE THREAD

**Issue by porres** [porres/pd-else#205]

**Comment by alfonso73** [comment]
Yeah!

**Comment by porres** [comment]
hi @alfonso73 , I have a new abstraction (called [mono]), the first version was just uploaded with this commit: https://github.com/porres/pd-else/tree/09c72aaa4cf662635f6b7c7bf373065b9969b349

**Comment by alfonso73** [comment]
Great. How can i test it? Is there any temp release binary?

**Comment by porres** [comment]
it's an abstraction

**Comment by alfonso73** [comment]
yeah. but i can see only the mono-help.pd file and if i try to instantiate [mono] it doesn't load.

**Comment by porres** [comment]
yeah, if you download it all you can have access to the help file and the abstraction - then put them together in your else folder and see if it runs. If not, you'll have to wait the next release

**Comment by alfonso73** [comment]
Very well designed abstraction! I got some basic bricks for it in vanilla but this really well designed and clear! thanks

**Comment by porres** [comment]
new rewritten version, with 'legato' mode

**Comment by porres** [comment]
maybe not so clear now that I'm abusing [expr] objetcs

**Comment by alfonso73** [comment]
Thanks @porres ...should be enough to downlaod mono.pd and mono-help.pd?

**Comment by porres** [comment]
yes
