### ISSUE TITLE
else.l_amd64: undefined symbol: pdgui_vmess

### ISSUE THREAD

**Issue by rrrccc** [porres/pd-else#2062]
Hello,

I'm using Pd 0.52.1 in Linux Mint 21.2

Following the readme.pdf instructions, I installed else from deken:

http://puredata.info/Members/porres/software/else/1.0-0_rc11-with_live_electronics_tutorial/else%5Bv1.0-0_rc11-with_live_electronics_tutorial%5D(Darwin-amd64-32)(Darwin-arm64-32)(Linux-amd64-32)(Windows-amd64-32).dek

When I open the else-help.pd file I got in console:

/home/xxx/Documents/Pd/externals/else/else.l_amd64: /home/xxx/Documents/Pd/externals/else/else.l_amd64: undefined symbol: pdgui_vmess

Else is in Preference->Path and in ->Startup but the library is not loading.

I'm writing this here because the bug/issues link provided in the README.deken.pd "https://github.com/porres/pd-issues"  gives me an error 404. 

best,
rc

**Comment by porres** [comment]
hi, not a bug, rc11 needs Pd 0.54
