### ISSUE TITLE
improve build system

### ISSUE THREAD

**Issue by porres** [porres/pd-else#2158]
It would be good to build ELSE all on its own... right now I have to do special makes for [plaits~], [play.file~]/[sfload], [circuit~], [sfz~] and [sfont~].

It's ok to have a single way to build just these, but I'd like to have a single make that builds it all

Also, there are a couple of folders that I wanted to copy when doing make, but I don't know how to do that. Both are in the /documentation folder: Live-Electronics-Tutorial and extra_files/sf (I should also put the 'sfz' folder in here).

**Comment by porres** [comment]
sfz~ and circuit~ shouldn't install in ~/library/pd

<img width="646" alt="Screenshot 2024-08-26 at 21 33 00" src="https://github.com/user-attachments/assets/9a307519-795d-4098-ae43-9e663aed8ed4">

**Comment by porres** [comment]
@timothyschoen I'd need your help for these

**Comment by porres** [comment]
I'd like the code_source folder to include objects independently instead of having [play.file~] and [sfload] in the same folder and built together... same with [pd.link] and [pd.link~], specially because I have a separate folder for control and signal objects.

so moving sfload.c to control objects and pd.link~.c to signal objects is necessary.

and now we also have [pd.link] and [pd.link~] that need to be built separately, and I hope ALL objects could be built at once... [plaits~], [play.file~], [sfload], [circuit~], [sfz~], [sfont~] and now  [pd.link] and [pd.link~]

**Comment by porres** [comment]
also, we should and could use a single pd-lib-builder, right now they are all over the place

**Comment by timothyschoen** [comment]
> I'd like the code_source folder to include objects independently instead of having [play.file~] and [sfload] in the same folder and built together... same with [pd.link] and [pd.link~], specially because I have a separate folder for control and signal objects.
> 
> so moving sfload.c to control objects and pd.link~.c to signal objects is necessary.

That's fine, but then all the dependencies of those objects need to move to the "shared" folder. I'm not sure that's the best way to go?

**Comment by timothyschoen** [comment]
Also in general, I wonder if it's useful to separate "signal" and "control" into separate folders? It makes it harder to find related objects. If I could list alphabetically, you can find those much quicker.

A small pet peeve for me is that I have to click through 4 layers of folders to get to objects when working on ELSE. Why not structure it like this:

- Source: all C source, larger objects contained in folders. We put the "shared" folder in there too, so these files can easily be accessed
- Abstractions: All abstractions, Merda
- Documentation: All help files, Live Electronics Tutorial
- Resources: extra stuff, resources, etc.

This way, you can get to the most important parts much faster. There is less width and depth in the amount of folders.

**Comment by timothyschoen** [comment]
For the build system: I can't fix this with Makefiles, I'm not an expert on those. I can write a shell script though, to build and copy everything?

**Comment by porres** [comment]
> but then all the dependencies of those objects need to move to the "shared" folder.

I'd actually like that, makes sense with the rest of things

**Comment by porres** [comment]
> I can write a shell script though, to build and copy everything?

sure

**Comment by porres** [comment]
> Also in general, I wonder if it's useful to separate "signal" and "control" into separate folders? 

One problem I have sometimes if I have cents2ratio and cents2ratio~ on the same folder is that if I change 'cents2ratio' and save, it removes cents2ratio~

I also like to keep count of objects separately (number of signal [coded and abstraction] objects, number of control [coded and abstraction] objects).
