### ISSUE TITLE
[note] gui inside GOP is not correctly sized when zoom = 2

### ISSUE THREAD

**Issue by jyg** [porres/pd-else#2225]
In puredata vanila 0.55, windows 11 64, (Else 1.0-0 RC-12)
when you create an object with zoom = 2, if it contains embedded [else/note], this one is not correctly sized.

-create a new patch
-set zoom= 2
- create an object else/chorus.m~

https://github.com/user-attachments/assets/24936ad1-9507-48c8-a4fa-183e59c3b855

**Comment by porres** [comment]
I see, it's like it's drawn twice as big...
