### ISSUE TITLE
cannot set the file in [player~]

### ISSUE THREAD

**Issue by H-MLim** [porres/pd-else#2227]
what does "set <symbol> - sets a file to open (needs a reload message)" exactly mean in [player~]? I wanted to just set the file (not play it) like [set music.wav( but after clicking it, I got a message "inlet: expected 'symbol' but got 'music.wav'"...

**Comment by porres** [comment]
I can't reproduce the error when I click on the message on the help file.

When playing a file in a loop and I click on this message, the new sound file is played next time it restarts the loop.

But when having the object not playing anything with some file loaded, when I set the new file it still plays the old one when I start playing (it only goes to the next one that I had set later when it loops). So this is a bug.

**Comment by porres** [comment]
> I can't reproduce the error when I click on the message on the help file.
> 
> When playing a file in a loop and I click on this message, the new sound file is played next time it restarts the loop.
> 
> But when having the object not playing anything with some file loaded, when I set the new file it still plays the old one when I start playing (it only goes to the next one that I had set later when it loops). So this is a bug.

damn, I got confused and tested play.file~ instead :) I can reproduce this now

**Comment by porres** [comment]
will try to fix both issues

**Comment by porres** [comment]
well, this is actuallly a documentation error, there's not 'set' message indeed

**Comment by H-MLim** [comment]
> well, this is actuallly a documentation error, there's not 'set' message indeed

I understand. but are there any option to just load/set the soundfile, but not playing in same time?

**Comment by H-MLim** [comment]
so it's right to understand that there's no way to do like that both in `[player~]` and `[play.file~]`? then it's ok.

**Comment by H-MLim** [comment]
oh OK. maybe my ELSE is not the latest. will update and try again later. thanks.

**Comment by porres** [comment]
the current state is not yet released
