### ISSUE TITLE
feature: make [tabplayer~] automatically compensate for sample rate difference via internal communication with [sample~]

### ISSUE THREAD

**Issue by jamshark70** [porres/pd-else#2229]
I had assumed that [tabplayer~] operating with a rate factor = 1 would play at the sound file's normal speed, regardless of the system's sample rate.

But I was just testing with a 44.1 kHz file, and my built-in soundcard can only run 48 kHz. The file was audibly slightly fast (high).

[cyclone/play~] behaves this way... which is understandable because it's based on Pd arrays, which don't retain the sample rate as a property. Even though Max/MSP [play~] does automatically handle sample rate, the use of Pd arrays makes it impossible for [cyclone/play~].

But [else/sample~] does know the sample rate. [tabplayer~] seems to be ignoring that property...? Is that the expected behavior?

**Comment by porres** [comment]
Hi, I can try to fix this for both cyclone and else, but it does seem challenging for cyclone... and I didn't know of this issue (we should at least document the different behaviour from MAX)

**Comment by jamshark70** [comment]
BTW I have a cyclone-based workaround at http://github.com/jamshark70/hjh-abs ([monofile] with [sf-play~], or [stereofile] with [sf-play2~]).

**Comment by porres** [comment]
Having a look at the object, I see this

<img width="411" alt="Screen Shot 2024-12-11 at 23 43 41" src="https://github.com/user-attachments/assets/69b79054-af3b-48d9-afa0-80cff6019c2b" />

So I guess I thought about this and this is how I resolved things. Isn't it good enough?

**Comment by porres** [comment]
For extra convenience I am including a send name into [sample~] that sends a "sr <sample-rate>" message to a send name that is "arrayname-sr". Then I am binding this receive name into the [tabplayer~] object. This way you don't need to patch anything and the [sample~] object will send the 'sr' message to the [tabplayer~] object of the same name.

<img width="552" alt="Screen Shot 2024-12-12 at 11 29 59" src="https://github.com/user-attachments/assets/f04aa10d-3042-4c83-9d20-ffe40910a86e" />

**Comment by porres** [comment]
the printed message in the terminal is an internal post from [tabplayer~], showing that it is receiving the message.

**Comment by porres** [comment]
changed the title because [tabplayer~] was already capable of compensating sample rate difference
