### ISSUE TITLE
playing delay in [player~]

### ISSUE THREAD

**Issue by H-MLim** [porres/pd-else#2230]
https://github.com/user-attachments/assets/c6b57034-02ef-414d-98bb-f3cca129a10d

https://github.com/user-attachments/assets/627f8506-1577-4bd9-859d-35bf8ad26fbc

hello. I was going to play my files in `[player~]`, while alternating files in one object. but each time I change and play my files, there is a little latency and delay. but I'm not sure whether this is a bug or just a problem with my computer. (but at least it was fine when doing the same thing in `[readsf~]`) - tested in both plug and vanilla / Win11

mypatch: https://drive.google.com/file/d/1I-ZXZZTLykAWYyaCdW-tPTemzNoy7Ifr/view?usp=sharing

**Comment by porres** [comment]
please don't send a patch with over half a gigabyte :) 

I don't know how to work with this patch and it looks pretty weird when opening in vanilla, things are too big

try to send a minimal patch that shows the behaviour to see if I can reproduce. Something that compares readsf~ and player~ with a small sample would be nice.  You can also just upload the patch as a zip file here in the comment

**Comment by H-MLim** [comment]
hi. sorry for the inconvenience. here is more simple patch. would this help? https://drive.google.com/file/d/176H2fkcj_ayyXuzPfrNoXIjz6aW4XZvi/view?usp=sharing

**Comment by H-MLim** [comment]
what I also found was when I play the file through `player~`, the console window in vanilla shows the error message "Audio I/O Error". while not in `readsf~`

![image](https://github.com/user-attachments/assets/83a50eba-f0a4-4d3e-8043-0b9b0d029477)

**Comment by porres** [comment]
I don't see much of a difference in your patch example, but I think I see what is going on

note that [player~] is not supposed to be an alternative to readsf~

I already explained that on a facebook post

player~ loads files into tables and your files are big, this is why you see the CPU choking with errors

the play.file~ object is a replacement to readsf~

so if you don't need special features from player~ you should use play.file~ or readsf~ for very large files, or you need to preload these samples into tables and use [tabplayer~] to access different files

**Comment by H-MLim** [comment]
Ok so I understood that this might be a size problem. Will try [play.file~] too. Thanks!
