### ISSUE TITLE
player~ error in windows7

### ISSUE THREAD

**Issue by aclaiman** [porres/pd-else#249]
Hi!
player~ don´t work even in the help patch.
I´m using vanilla 0.48.1 on Windows 7. The same error on 2 machines one with the 32 bits os and another with 64 bits
This is the console message:

`usage: read [flags] filename tablename...
flags: -skip <n> -resize -maxsize <n> ...
-raw <headerbytes> <channels> <bytespersamp> <endian (b, l, or n)>.
usage: read [flags] filename tablename...
flags: -skip <n> -resize -maxsize <n> ...
-raw <headerbytes> <channels> <bytespersamp> <endian (b, l, or n)>.
usage: read [flags] filename tablename...
flags: -skip <n> -resize -maxsize <n> ...
-raw <headerbytes> <channels> <bytespersamp> <endian (b, l, or n)>.`

**Comment by porres** [comment]
what happens when you create it in an empty patch?

**Comment by aclaiman** [comment]
the error occurs when passing the open message (after selecting the file if open doesn´t have any argument o immediatly with an argument.) 
The same occurs if I create the instance player~ with the file name in it. ex: 
`player~ violin.wav`

**Comment by porres** [comment]
I'm only using [soundfiler], basically, on this abstraction, and this is an error given by [soundfiler]. So it might be the case where [soundfiler] is not working for windows 7, as it is just working fine here on macOS.

Can you try using [soundfiler] on its own?

**Comment by porres** [comment]
and of course, I'm using new syntax from [soundfiler], that only works in 0.48-0 and on... I get that kind of error using 0.47, but you say you really have 0.48, which is weird

**Comment by aclaiman** [comment]
I forgot to mention that sampler~ works ok.

**Comment by porres** [comment]
sampler~ doesn't use [soundfiler], but [readsf~] - this is an issue with [sounfiler], like I said. We should see if it has more general issues on windows 7

**Comment by porres** [comment]
so, this is a problem with windows, it won't accept a -maxsize flag bigger than 2.14748e+09 or something for some reason.

So I'm reducing this to 2.14748e+09 so it works

**Comment by porres** [comment]
reported this to https://github.com/pure-data/pure-data/issues/380

**Comment by porres** [comment]
hi, this seems to have been fixed now for Pd 0.48-2, right? can you give it a try?

**Comment by aclaiman** [comment]
Yes! I´ve just test it on Windows7 32 bits with Pd vanilla 0.48.2test1 and player~ works just fine.
Thank´s. You are The Boss! :)

**Comment by porres** [comment]
but did you try beta 10 or beta 11? cause I also had made adjustments for beta 11 to work. Please confirm if you have beta 10 and that it works with 0.48-2 - thanks!

**Comment by aclaiman** [comment]
SOrry about the delay in the answer. I´ve test it in the beta 11 with 0.48.2

**Comment by porres** [comment]
Hi, I believe this is working since 0.49-0 came out. I'm closing this issue, but feel free to reopen if you still have an issue with this
