### ISSUE TITLE
deken uploads should contain sources

### ISSUE THREAD

**Issue by umlaeute** [porres/pd-else#487]
when uploading to deken, please consider providing the sources as well.

**Comment by umlaeute** [comment]
if you build all the deken packages for a given release from the same sources (which i guess is true), it's totally sufficient to upload a single source package, e.g.

    else[v1.0beta20](Sources).dek

as a bonus: if you use the `deken` cmdline tool *and* upload the source package before the binary packages, you don't need to provide the `--no-source-error`.

**Comment by porres** [comment]
doing it right now, thanks

**Comment by porres** [comment]
> as a bonus: if you use the deken cmdline tool and upload the source package before the binary packages, you don't need to provide the --no-source-error.

funny, I tried that after uploading the source, and it gave me that error, so I had to use the flag anyway. Probably I'm not doing something right, but the sources were uploaded successfully.

https://puredata.info/Members/porres/software/else/1.0beta20/

at this very moment, I'm uploading other two binsaries (Windows 64 and Linux 32)

**Comment by umlaeute** [comment]
> funny, I tried that after uploading the source, and it gave me that error, so I had to use the flag anyway. Probably I'm not doing something right, but the sources were uploaded successfully.

weird.

**Comment by porres** [comment]
yeah, I'll pay more attention to this next time I do it. I'm probably not doing things in the way I should...

**Comment by porres** [comment]
I uploaded a new version. I was able to upload the sources, no issues... I didn't need the --no-source-error. It went up, all fine.

Then I tried uploading the binaries without the --no-source-error. And things went bad, as I needed to use this flag.

**Comment by umlaeute** [comment]
you can also upload multiple packages (including the source-only package) in a single step.

~~~
$ deken package --version 1.0beta21 linux-builds/else/
$ deken package --version 1.0beta21 osx-builds/else/
$ deken package --version 1.0beta21 win-builds/else/
$ deken package --version 1.0beta21 src/else
$ deken upload else*1.0beta21*.dek
~~~
