### ISSUE TITLE
1.0 final release roadmap

### ISSUE THREAD

**Issue by porres** [porres/pd-else#504]
1- Band Limited oscillators as compiled objects (hence, way more efficient)
2- curved [function], hopefully
3- All breaking changes I can think of...
4- bunch of fixes and stuff (get the issue list quite low)
5- sort license issues

**Comment by alfonso73** [comment]
Hi @porres! Are point 1 in this list still in the roadmap for 1.0? thanks!

**Comment by porres** [comment]
yeah, sure :) though I can't promise, anyway, I'm moving to release candidate soon

**Comment by alfonso73** [comment]
great. thanks!
