### ISSUE TITLE
[dir] on windows: annoying error and reset message doesn't work

### ISSUE THREAD

**Issue by dfkettle** [porres/pd-else#574]
After installing (using Deken) v1.0 beta-23 under pd v0.50 (also v0.49) under Windows 7 SP1, I get the following error message (22 times) in the PD console window:

`[dir]: cannot open 'C:/Users/user/AppData/Roaming/Pd/else', opening 'C:/Users/user/AppData/Roaming/Pd/else' instead
`

This is the same directory I used to install several other external libraries (cyclone, iemlib, mrpeach, etc.) and didn't have any problem. It's a real directory, not a Windows shortcut.

**Comment by porres** [comment]
you need to start testing the help file of dir, because this is an issue with 'dir', not "All_objects.pd"

what do you get when you:

1- open the help file of [dir]?
2- create the [dir] object in a new patch?

**Comment by porres** [comment]
when dir is loaded, it gets the directory of the patch by default ('C:/Users/user/AppData/Roaming/Pd/else' in your case). You can give it another directory file as an argument, and, if 'dir' cannot open it, then it gives that error and opens the default directory instead.

This error means that it tries to load the default directory but it can't, but the error doesn't really know that it is the same directory as the default one and says it opened the same one instead, but I think that the object could just not open the directory at all.

So we need to make further tests, specially with the help file of [dir], to make sure it didn't open the default directory. Do you follow?

**Comment by porres** [comment]
> 1- open the help file of [dir]?

try testing the messages in the main patch window of the dir-help.pd file, tell me what you see

**Comment by dfkettle** [comment]
I'm not sure I completely understand your explanation. I don't know why
[dir] wouldn't be able to open the default directory, it exists and other
externals I've installed don't seem to have any trouble reading it. But
here's what happened when I created a new patch, added a [dir] object, then
right-clicked on it to open the help file.

When I added the [dir] object to an empty patch (see screen print), the
first error message below appeared in the console window, but the object
was created anyway.

When I right-clicked to open the help file, the remaining messages appeared
in the console window, but the help file opened successfully. Also,
although I didn't test all of the features in the help file, the ones I did
test seemed to work.

Here are the error messages (same as before, except for the first one):

[dir]: cannot open 'C:Usersuser', opening 'C:Usersuser' instead
[dir]: cannot open 'C:/Users/user/AppData/Roaming/Pd/else', opening
'C:/Users/user/AppData/Roaming/Pd/else' instead
[dir]: cannot open 'C:/Users/user/AppData/Roaming/Pd/else', opening
'C:/Users/user/AppData/Roaming/Pd/else' instead
[dir]: cannot open 'C:/Users/user/AppData/Roaming/Pd/else', opening
'C:/Users/user/AppData/Roaming/Pd/else' instead
[dir]: cannot open 'C:/Users/user/AppData/Roaming/Pd/else', opening
'C:/Users/user/AppData/Roaming/Pd/else' instead
[dir]: cannot open 'C:/Users/user/AppData/Roaming/Pd/else', opening
'C:/Users/user/AppData/Roaming/Pd/else' instead
[dir]: cannot open 'C:/Users/user/AppData/Roaming/Pd/else', opening
'C:/Users/user/AppData/Roaming/Pd/else' instead


Everything so far seems to work, except for the error messages in the
console. I can ignore the error messages, but if you can figure out what's
causing them, that would be great. Hasn't anyone else had this issue? Do
you do much testing on Windows? I'd be happy to help test new releases in
the future, if you need people to test under Windows. I have a desktop
running Windows 7 and a laptop running Windows 8. I haven't tried this on
my laptop, since I do all my Pure Data development on my desktop.

David.

**Comment by porres** [comment]
> When I added the [dir] object to an empty patch (see screen print),

i dont see a screenprint

**Comment by porres** [comment]
> Hasn't anyone else had this issue? 

nope 

> Do you do much testing on Windows? 

nah

**Comment by porres** [comment]
>  if you need people to test under Windows. I have a desktop
> running Windows 7 and a laptop running Windows 8. 

awesome, it'd be great if you tested this on 8 as well

**Comment by dfkettle** [comment]
Didn't  you get the attachment? Anyway, there's  not much to see. The [dir]
object was created (no dashes around it).

**Comment by porres** [comment]
> Didn't  you get the attachment?

nope, I guess you need to log in on github and attach manually...

**Comment by porres** [comment]
> Everything so far seems to work, except for the error messages in the console. 

This is very weirs, as it does print an error as it could open the directory, but it does open it in the end... I wonder why!?!!?!?

here'es what I want you to test, I want you to try and open other directories. 

the problem is that if the error is happening,it won't open new directories, and that is BAD!

**Comment by dfkettle** [comment]
Maybe github scrubbed the attachment? Anyway, here's the screen shot.

![Screenshot 2019-09-19 07 13 26](https://user-images.githubusercontent.com/8409615/65263047-ab682b80-dad9-11e9-9153-d28c7b6d9f18.png)

**Comment by porres** [comment]
i can see it now, whatever you did this time, keep doing, or did you do the same? (weird)

**Comment by dfkettle** [comment]
If you mean the screenshot, the first time I just responded to your email, with an attachment. This time I uploaded it to github.

**Comment by porres** [comment]
> This time I uploaded it to github.

so yeah, that's what you gotta do

Anyway, please test if you can open new directories and stuff

**Comment by dfkettle** [comment]
Except for the error message, it seems to work, I can open a different directory (see below). I've never used your library before, so I'm just learning how to use it, though. Is there anything in particular, besides opening a new directory, you'd like me to test?

![Screenshot 2019-09-19 12 56 06](https://user-images.githubusercontent.com/8409615/65264639-0e0ef680-dadd-11e9-9eab-bad769b65560.png)
![Screenshot 2019-09-19 12 56 26](https://user-images.githubusercontent.com/8409615/65264648-123b1400-dadd-11e9-8612-56b6c13c605d.png)

**Comment by porres** [comment]
that's weird as it doesn't seem to make sense. My understanding is that if it did print that error, tha it shouldn't open the directory, let me check it over.

**Comment by dfkettle** [comment]
Could it have something to do with the way path names are formed in Windows vs. Linux and Mac OS ('\' instead of '/')?

**Comment by porres** [comment]
maybe, did you try to open relative directories? that one you tried was an absolute path, right?

**Comment by porres** [comment]
well, actually, for absolute path and the default path, that wouldn't really matter I think, but for relative, that's something to look in, so try it please

**Comment by dfkettle** [comment]
Both absolute and relative paths seem to work correctly.

**Comment by porres** [comment]
and do you get errors for relative paths as well?

**Comment by porres** [comment]
if so, ok, nothing makjes sense to me yet, but you just have annoying errors and the object works

**Comment by dfkettle** [comment]
I only get the error message when I add a [dir] object to a patch, or when I open the help file for it. When I actually use it, though, I don't get any error messages and everything seems to work correctly. So that's good news. If you can't find the problem, a simple kludge would be to compare the two directories in the error message and if they're equal, don't display the message.

**Comment by dfkettle** [comment]
I just tried sending it a "reset" message, but that doesn't seem to do anything. No error message is displayed, but I'm still in the same directory I was in before I clicked on the "reset" message.

**Comment by porres** [comment]
The reset message would get you back to the patch's directory, so if you're not there, it should take you there. You're saying you weren't there but you didn't change as well, right?

what about when you create the object with an argument that sets a different directory to open?

**Comment by dfkettle** [comment]
That's correct, if I'm not in the patch's directory, clicking the reset message doesn't do anything. I haven't tried any creation arguments yet, I'll do that next. 

I did notice something in the help patch, not a bug, just a typo, I think. The description for 'bang' says  "outputs 'n', 'directory' and 'files' ". Should that say "outputs 'n', 'dir' and 'dump' "?

**Comment by dfkettle** [comment]
Hah! I just discovered that if I add a 'dir' object with a creation argument pointing to a different directory, I don't get the error message. It's only when I add a 'dir' object without a creation argument that I get the error message. Hope that helps.

**Comment by porres** [comment]
yeah, that helps me get really confused

**Comment by Lucarda** [comment]
@porres with this I get no errors:

![dir1](https://user-images.githubusercontent.com/25239522/65275824-ce580700-dafc-11e9-8f3a-237448278e76.png)

The creating with no args I get the error : 

![dir2](https://user-images.githubusercontent.com/25239522/65276144-84bbec00-dafd-11e9-9748-c2af20958dac.jpg)

**Comment by dfkettle** [comment]
If I specify a numeric creation argument like [else/dir 1], I get the same error I get with no creation arguments. The '-ext' flag seems to work, though.

**Comment by porres** [comment]
I seem to have fixed the annoying error with 'https://github.com/porres/pd-else/commit/75f3d5962c88dd773d59c62d7398017f82b868ff'

I still need to figure out why the reset message doesn't work

**Comment by porres** [comment]
'reset' message fixed

**Comment by porres** [comment]
Please test it @Lucarda

**Comment by Lucarda** [comment]
> Please test it

All good. No errors are printed and all examples for [dir] are working as expected.
