### ISSUE TITLE
Installation problem on Windows

### ISSUE THREAD

**Issue by dfkettle** [porres/pd-else#578]
While trying to install version 1.0 beta-24 of Else using Deken, I received the following error: 

"[deken]: Unable to extract package automatically.Please perform the followint steps manually:1. Unzip C:/Users/user/AppData/Roaming/Pd/else[v1.0beta24](Windows-i386-32).dek.2. Copy the contents into C:/Users/user/AppData/Roaming/pd." (see screen print).

Because '.dek' isn't an extension recognized by Winzip as a zip file, I had to first rename it to '.zip', but after doing that, I was able to unzip it and move the contents to the target directory. However, I didn't have this problem when installing the previous version of Else (v1.0beta23), or with any other external library that I've ever installed in Pure Data.

![Screenshot 2019-09-23 06 21 47](https://user-images.githubusercontent.com/8409615/65420606-99cf9e00-ddcf-11e9-875b-b1bfc148fa57.png)

**Comment by porres** [comment]
weird, but guess all I can do is try to reupload it

**Comment by dfkettle** [comment]
I think what happened was that it was zipped twice. Anyway, like I said, I resolved the problem "manually" and managed to install the latest. So if nobody else on Windows complains, don't worry about it.

**Comment by porres** [comment]
hey, can you test the new release (beta25)?

**Comment by porres** [comment]
if it works, I'll close this

**Comment by dfkettle** [comment]
I've only used a few of the objects in the library, but I can see if I get
any error messages loading the various help files.

David.

**Comment by porres** [comment]
what I was hoping is that you tried the beta25 from deken to see if it works, it's not up there yet but should be in the next few hours

**Comment by porres** [comment]
it's online now!

**Comment by dfkettle** [comment]
I installed it without any problem, although I haven't had time to try
anything yet. Is there something in particular you'd like me to test?

David.

**Comment by porres** [comment]
I just wanted to make sure you could install 1.0 beta-25 via deken
