### ISSUE TITLE
some source files are marked as "executable"

### ISSUE THREAD

**Issue by umlaeute** [porres/pd-else#580]
a number of files in the repository have the "executable" bit set, even though they cannot be executed in reality.

this is mildly annoying, as people (on operating systems that rely on the executable bit rather than the file-extension to check whether they can "run a program") could accidentally try to run those files (e.g. double clicking them in the file browser) and experiencing segmentation faults:

~~~sh
$ find * -type f -executable
Classes/Abstractions/pan8~.pd
Classes/Abstractions/morph~.pd
Classes/Source/gui.c
Classes/Source/dir.c
Classes/Source/function.c
Help-files/pan8~-help.pd
pd-lib-builder/tips-tricks.md
pd-lib-builder/CHANGELOG.txt
pd-lib-builder/README.md
pd-lib-builder/Makefile.pdlibbuilder
~~~

The fix is pretty simple: remove the executable bit.

~~~sh
$ find * -type f -executable -exec chmod -x {} +
~~~

**Comment by porres** [comment]
I tried running '-executable: unknown primary or operator' on the terminal, but got "find: -executable: unknown primary or operator"

I obviously don't have a good idea of what i'm supposed to do, why it happened and how to prevent it

**Comment by umlaeute** [comment]
well, you can always manually run `chmod -x` on the files i listed.

**Comment by porres** [comment]
I think I got this fixed

**Comment by porres** [comment]
by the way, any idea how I generated this issue? Cause I don;t have the slightest idea! Seems some of the doc files I worked on for Vanilla also got 'corrupted' this way... anyway, just wondering if it's easy to prevent this as to avoid further annoyance - and I still don't know how to find this problem on my own...

**Comment by umlaeute** [comment]
:tada: 

> I think I got this fixes

almost.
rightafter you fixed the permissions on the files I mentioned, you somehow managed to make both *Classes/Source/canvas.mouse.c* and *Help-files/canvas.mouse-help.pd* `executable`. Please fix them as well...

> by the way, any idea how I generated this issue

not really.
a wild guess is, that there's a DOS partition involved (e.g. developing on a shared volume; or sharing stuff by copying it to a USB-stick).

you might try to find out what you did when you last updated `canvas.mouse` in commit c3df913fb32ffef6f5576e41aaf48ab31c2000db, where you changed the permissions of two more files.

**Comment by porres** [comment]
> right after you fixed the permissions on the files I mentioned, you somehow managed to make both Classes/Source/canvas.mouse.c and Help-files/canvas.mouse-help.pd executable. Please fix them as well...

done!

> a wild guess is, that there's a DOS partition involved (e.g. developing on a shared volume; or sharing stuff by copying it to a USB-stick).

nope

> you might try to find out what you did when you last updated 

I had downloaded from github's website an earlier version of those files (cause I regretted the last change I made) and replaced the new files with the old ones. This also explains how the libpd files got corrupted and some of the files in Pd's documentation.

I gotta be careful and remember now that this somehow screws things up

thanks
