### ISSUE TITLE
meter~ -100

### ISSUE THREAD

**Issue by timpauli** [porres/pd-else#584]
Hi,

what do you think about adding a - 100 to the meter~ object.
So 0db is the peak of a fullscale signal.

Thanks for the great library.
It is very useful.
Best
Tim

**Comment by porres** [comment]
sorry, I don't understand

**Comment by timpauli** [comment]
At the moment when I am sending an audio signal that ranges between -1 and 1 to the meter~ object of the pd-else library, the gui-meter completely clips. I expected that the gui-meter shows me something near 0.  But right now it shows me something near 0 when I send a silent audio signal. 

Or am I doing something wrong?

**Comment by porres** [comment]
> Or am I doing something wrong?

I belive so :) just check the help file of [meter~] and you'll see it works right

**Comment by porres** [comment]
>  just check the help file of [meter~] and you'll see it works right

if not, reopen this issue and show me how it ain't working

**Comment by timpauli** [comment]
So the help patch works like this for me:

no signal:
![meter0](https://user-images.githubusercontent.com/9436381/68882847-d3ee5980-0707-11ea-955a-1518146bad2d.png)

fullranged signal:
![meter1](https://user-images.githubusercontent.com/9436381/68882861-dc469480-0707-11ea-91d3-1d60253edcf7.png)

This is not what I would expect. The meter~ uses only 12 steps of the whole range..
Or is this the way it should work? Thanks a lot.

**Comment by porres** [comment]
well, I need more info now, what OS are you on? What version of Pd and else?

**Comment by timpauli** [comment]
OS: Linux Ubuntu 19.10
PD:  0.5
else: v1.0beta24(Linux-amd64-32)

**Comment by porres** [comment]
all should be fixed by now and a new version will come out next week

**Comment by porres** [comment]
new release just out!

**Comment by timpauli** [comment]
Thanks again for changing!
