### ISSUE TITLE
keyboard is not working + examples voices still playing after close

### ISSUE THREAD

**Issue by muziker** [porres/pd-else#629]
The keyboard does not respond to mouse clicks. Occasionally one of the keyboard guis does respond, but the keys stick and do not turn off on mouse click up. 

The examples that have sound also seems to keep playing even after the window is closed. It could be a matter of child windows.

still it's great work ! good going so far

**Comment by muziker** [comment]
The else version is v1.0-beta25-49-g4b15190

**Comment by porres** [comment]
I'm on it ,thanks, I think I've fixed it already for the next release, but I tested it now and it's still weird. 

I'm trying to implement a "toggle" mode, where you click to leave it on then once again to turn it off, but I didn't finish and ended up screwing things up

**Comment by muziker** [comment]
Yes, i was wondering what the toggle parameter was. So far that's the only object that has some issues that i've encountered. There are some weirdness like with the pan8~ but i'm not sure if that's a feature rather than a bug

**Comment by porres** [comment]
what weirdness?

**Comment by porres** [comment]
oh, the spread... yeah, that's a feature

**Comment by porres** [comment]
and it's not "weird" :)

**Comment by porres** [comment]
what do you mean by "examples voices still playing after close"?

**Comment by porres** [comment]
I've fixed keyboard, you may open a new issue about "examples voices still playing after close", which I don't understand what it is supposed to mean
