### ISSUE TITLE
Patches keep playing even if windows are closed

### ISSUE THREAD

**Issue by muziker** [porres/pd-else#646]
This is probably more a user experience thing than anything else.

So let's say you open up a help file. There's a few [pd <example> ]s on the side. If you click on one and start running the examples, and close the window, those examples are still running in the background. This becomes a problem if you open multiple examples and the previous ones are still running, and has some impact with the audio being generated in the current example being affected .

**Comment by porres** [comment]
yeah, you have to turn the volume down if you don't want to hear it anymore, there's nothing to do about it, so I'm closing this

**Comment by umlaeute** [comment]
i guess you could add an indication visible on the outside of whether a subpatch actually creates sound.
e.g. a blinking status led besides the subpatch.
