### ISSUE TITLE
pd-lib-builder makefile does not use PDDIR or DESTDIR

### ISSUE THREAD

**Issue by muziker** [porres/pd-else#653]
In v1.0-beta26-128-ga1e469c, specifying PDDIR or DESTDIR does not affect the make process. These have to be defined in the pd-lib-builder makefile to have any effect. I did not check the rest of the environment variables to see if they're working

**Comment by porres** [comment]
I don't really know what you're talking about or what is the issue. Are you saying I should change https://github.com/porres/pd-else/blob/master/Makefile , but why?

**Comment by porres** [comment]
or are you having issues with pd-lib-builder? In which case you should take it to https://github.com/pure-data/pd-lib-builder

**Comment by muziker** [comment]
To build the else library, i had to specify the PDDIR and DESTDIR in the pd-lib-builder/Makefile.pdlibbuilder . Traditionally, for the other pure data libraries that use pd-lib-builder, doing this "make PDDIR=<path to puredata> DESTDIR=<install directory> build" works. But in this case it does not. It could be the current pd-lib-builder used in the else library is older.

**Comment by porres** [comment]
> Traditionally, for the other pure data libraries that use pd-lib-builder, doing this "make PDDIR= DESTDIR= build" works.

which one, for example?

**Comment by porres** [comment]
well, I just updated to the latest pdlubuilder (6.0), since this is strictly a pdlibbuilder issue, I'm closing this, we can take it to the pdlibbuilder repository's issue if somehow pdlibbuilder isn't working as expected for ELSE, cause I have literally no clue
