### ISSUE TITLE
else/display creates empty objects in the parent when used in an abstraction

### ISSUE THREAD

**Issue by muziker** [porres/pd-else#655]
Sorry porres no example patch, but:

Create an external patch, insert a couple of else/displays. In the parent, you can see an empty object appear. These empty objects are not selectable or removable. 

Delete the else/display from the abstraction to remove this

**Comment by porres** [comment]
sorry, I have no idea what you mean, I cant work with this

**Comment by muziker** [comment]
1. create an external patch
2. use else/display to display output of various objects
3. turn on graph on parent
4. for else/displays that are not in the red box that allows objects to be displayed in the parent, there can be an empty object that appears in the parent, roughly close to the same x,y coordinate of the else/display
5. it doesn't seem to happen all the time

**Comment by porres** [comment]
by "external patch" you mean "subpatch" then, right?

**Comment by porres** [comment]
anyway, this is a Pure Data bug, not an "else" bug, so I'm closing this.

else/display is just an abstraction based on regular Pd objects. You can try and report this issue at https://github.com/pure-data/pure-data/issues
