### ISSUE TITLE
[dir] console errors on Windows.

### ISSUE THREAD

**Issue by Lucarda** [porres/pd-else#663]
If I do **[else/dir]**, **[else/dir 0]**, **[else/dir 1]** the objects works but I get errors on the console:

`[dir]: cannot open 'C:/Users/Lucarda/Documents/Pd', opening 'C:/Users/Lucarda/Documents/Pd' instead`

If I do **[else/dir .]**, **[else/dir ..]**, **[else/dir ../..]** :

I don't get the console errors.

--
using else_1.0beta27

**Comment by porres** [comment]
So, this is foe windows, right? both 32 and 64?

Was this happening before with earlier versions?

**Comment by porres** [comment]
So, this only happens for windows, right? Linux is finem huh? Now, does it happen for both 32 and 64 Pd on windows?

Was this happening before with earlier versions? Like beta 26?

**Comment by Lucarda** [comment]
> So, this only happens for windows, right? Linux is finem huh?

Yes only on Windows. Linux32/64 does not have the problem.

>Now, does it happen for both 32 and 64 Pd on windows?

Yes.

>Was this happening before with earlier versions? Like beta 26?

Does _not_ happens on "beta 26" on win32 or win64.

**Comment by porres** [comment]
hey, can you test and see if it works for you? Seems to be fine over here!

**Comment by Lucarda** [comment]
Its working Ok.

### Additional notes

If i do `git clone` I get this error:

```
remote: Compressing objects: 100% (96/96), done.
error: filename in tree entry contains backslash: 'clock~ imp~ on:off\.pd'
remote: Total 12977 (delta 55), reused 71 (delta 22), pack-reused 12859
Receiving objects: 100% (12977/12977), 20.85 MiB | 2.50 MiB/s, done.
error: filename in tree entry contains backslash: 'clock~ imp~ on:off\.pd'
fatal: Not all child objects of ceb316f39621d3a5512db78289d0494fb0749f3c are reachable
fatal: index-pack failed
```
 I had to download the ZIP from the green button.

**Comment by porres** [comment]
thanks

I have no idea about the git error though

**Comment by porres** [comment]
there isn't even a clock~ object in else... wierd!
