### ISSUE TITLE
peak~ (and vu~ peak outlet) issue

### ISSUE THREAD

**Issue by sevdh** [porres/pd-else#665]
The value coming out of the peak outlet goes only 3 dB down (instead) of 6 dB down when the input signal is halved in amplitude. However, the RMS output of vu~ has the correct behavior.
The peak value is correct for a signal with a peak of 1.0 or -1.0. This counts for the 'linear' behavior and the 'db' behavior (linear output is 1.0 and db output is 0dB). This can be easily tested by sending [sig~ 1] or [sig~ -1] to peak~ or vu~.
With a peak value of 0.5 the linear output of peak is 0.707107 (the square root) of what it should actually be: 0.5. This can easily be tested by sending [sig~ 0.5] to the object. The corresponding value in dB is -3.01 dB. The correct peak value in dB is -6.02 dB.

**Comment by sevdh** [comment]
I just had a look at the code of peak~ and found the issues:

outlet_float(x->x_outlet, sqrtf(x->x_result));
should simply become:
outlet_float(x->x_outlet, x->x_result);

And instead of using pow2db amp2db should be used:
outlet_float(x->x_outlet, pow2db(x->x_result));
becomes:
outlet_float(x->x_outlet, amp2db(x->x_result));

And the amp2db function looks like this:
t_float amp2db(t_float f){
    if(f <= 0)
        return(-999);
    else if(f == 1)
        return(0);
    else{
        float val = log(f) * 20./LOGTEN ;
        return(val < -999 ? -999 : val);
    }
}

The same changes should be made for the peak output of vu~

Cheers!

p.s.: https://www.rapidtables.com/electric/decibel.html

**Comment by sevdh** [comment]
I wasn't aware of meter~, meter2~, meter4~ and meter8~ and just discovered them. They have the same issue for the indicated peak value.

**Comment by porres** [comment]
oops, how did that happen? will fix it, thanks

**Comment by sevdh** [comment]
You are welcome, happy to help!
