### ISSUE TITLE
[dir]: cannot open

### ISSUE THREAD

**Issue by jlquispec** [porres/pd-else#671]
When I create a object dir.

[dir]: cannot open 'C:/Users/xxx/jlquispec', opening 'C:/Users/xxx/jlquispec' instead

else[v1.0beta27](Windows-amd64-32).dek
	Uploaded by porres @ 2020-02-06 17:36:29

Windows 10

Pd version 0.50.2

**Comment by porres** [comment]
this has already been fixed, wait for next release (beta 28)

thanks for reporting
