### ISSUE TITLE
[dir] prints error on Windows 10

### ISSUE THREAD

**Issue by reduzent** [porres/pd-else#699]
Whenever an instance of [dir] is created, or when it receives a 'reset' message, it prints the following message to the Pd windows:

```[dir]: cannot open 'C:/shared', opening 'C:/shared' instead```

It doesn't matter what path the patch is saved in, whether it is writable or not, whether it contains spaces or not. I cannot see any malfunction. And since both paths from the message are the same, it seems the message itself is bogus.

This happens with:
 * else 1.0beta27
 * Pd 0.50.2
 * Windows 10

I cannot see this happen on Linux or on Windows.

**Comment by porres** [comment]
this has been fixed already ;) you can try building from source now and test.

I'll be releasing an update as soon as Pd 0.51-0 final version is out!

**Comment by porres** [comment]
there was another issue for this, which I'm assuming is the same deal and got fixed in the same way https://github.com/porres/pd-else/issues/663
