### ISSUE TITLE
properly bind keyboard to object pointer as a string 

### ISSUE THREAD

**Issue by porres** [porres/pd-else#710]
keyboard gets mouse release from tcl code, we need to convert the object pointer to a string and bind to it, instead of binding all keyboard instances to a single symbol "keyboard".

I've tried copying things from cyclone/scope~ but it didn't work. I have new things commented out in 

https://github.com/porres/pd-else/blob/master/Classes/Source/keyboard.c#L252

and

https://github.com/porres/pd-else/blob/master/Classes/Source/keyboard.c#L447

 mean, I did try other more intrusive things, but this is the starting point that still keeps the last original working.

**Comment by Spacechild1** [comment]
Since you're already generating a bind symbol, just bind the object to the symbol:
```
  char buf[64];
    sprintf(buf, "rel_%lx", (unsigned long)x);
    pd_bind(&x->x_obj.ob_pd, x->x_bindsym = gensym(buf));*/
```
Use the bind symbol in the bound method:
```
sys_vgui(".x%lx.c bind %xrr <ButtonRelease-1> {\n keyboard_mouserelease %s %%b\n}\n", cv, x, x->x_bindsym->s_name);
```
In the method, send the message to symbol:
```
sys_vgui("proc keyboard_mouserelease {id b} {\n");
    sys_vgui("    if {$b == 1} {\n");
    sys_vgui("        pd [concat $id _mouserelease \\;]\n");
    sys_vgui("    }\n");
    sys_vgui("}\n");
```
And the Pd callback method:
```
static void keyboard_mouserelease(t_keyboard* x){
    if(x->x_toggle_mode || x->x_glist->gl_edit) // Give up if toggle or edit mode!
        return;
    keyboard_note_off(x, x->x_last_note);
}
```
```
class_addmethod(keyboard_class, (t_method)keyboard_mouserelease,gensym("_mouserelease"), 0);
```
Something like this.

**Comment by porres** [comment]
> Since you're already generating a bind symbol, just bind the object to the symbol:

ok, like this, right?

```
//    pd_bind(&x->x_obj.ob_pd, gensym("keyboard"));
    char buf[64];
    sprintf(buf, "rel_%lx", (unsigned long)x);
    pd_bind(&x->x_obj.ob_pd, x->x_bindsym = gensym(buf));
    return(void *)x;
```

I've commented the original binding to "keyboard" and now I have this.

> Use the bind symbol in the bound method:

Ok, I'm now using the code you provide and I think I get it now. But it's blowing up Pd when I load the object, something this part of the code in the 'vis' function doesn't agree with Pd.

`sys_vgui(".x%lx.c bind %xrr <ButtonRelease-1> {\n keyboard_mouserelease %s %%b\n}\n", cv, x, x->x_bindsym->s_name);`

f I have the object hidden in a subpatch and open the subpatch to see it... BOOM... Pd blows again.

See the new code I uploaded for reference 

https://github.com/porres/pd-else/blob/master/Classes/Source/keyboard.c

**Comment by Spacechild1** [comment]
run it in a debugger and see where it crashes...

**Comment by porres** [comment]
hey, didn't run a debugger cause I don't have or know how to use one, but I just screwed up pretty badly ;) thanks for you help, it's working now!

**Comment by Spacechild1** [comment]
great!

> I don't have or know how to use one

I'm sure you have lldb or gdb installed. Learn to use it ;-)

**Comment by porres** [comment]
haha

hey, what if I want the object to have also a receive symbol, like other guis (tgl, vsl, etc)?

I can't bind to two different names, so is it impossible or is there an alternative?

**Comment by Spacechild1** [comment]
> I can't bind to two different names,

why not? objects are bound to a symbols, not vice versa.

example: `[v foo]` `[r foo]` `[s foo]`

**Comment by Spacechild1** [comment]
e.g. with `[namecanvas]` you can bind the same canvas to different names. Also, Pd temporarly binds a canvas to the `#A` symbol while loading.

**Comment by porres** [comment]
I meant binding to two names at the same time... but I guess I can have two different classes in the same object and use one just for clicking and getting these tcl/tk messages.  I see that something like that is going on in cyclone/scope~

**Comment by Spacechild1** [comment]
> I meant binding to two names at the same time...

As I said, you *can* do this.
