### ISSUE TITLE
issue with drum.seq

### ISSUE THREAD

**Issue by smomid** [porres/pd-else#715]
Hi. This is an issue with the drum.seq object. If I make a drum seq object that is 8 tracks and 64 slots long [drum.seq 8 64] and I play a sequence the object works fine. But if I send the drum.seq object an [export( message, then try and play the sequence again, the first or second track will continually output a drum hit. I've been able to get this behavior pretty consistently. 

I am using Pd .51.0 on a Raspberry Pi running Raspian 10. I have an example patch I can show you but Github won't let me attatch a PD file. 

I recorded a little video of the behavior and uploaded it at  https://youtu.be/S9yOYX0E_dA 

if you need more info feel free to email me at smomid27@gmail.com. thanks. Nick

**Comment by porres** [comment]
> I am using Pd .51.0 on a Raspberry Pi running Raspian 10. I have an example patch I can show you but Github won't let me attatch a PD file.

try compressing/zipping the file and upload it in a comment

**Comment by smomid** [comment]
[drumseqtest2.pd.zip](https://github.com/porres/pd-else/files/4815089/drumseqtest2.pd.zip)

**Comment by smomid** [comment]
OK thanks. I uploaded the patch from the video in a comment.

**Comment by porres** [comment]
ok, I can reproduce the bug, so I'll try to fix this ASAP... and then you can use the new abstraction (you don't even need to recompile, just download the object when I fix it, because it is just an abstraction).

**Comment by porres** [comment]
I might also release an update quite soon, as I already have some new and exciting things. But in order to keep my tradition, I want to at least include a couple of new objects to update the library...

**Comment by porres** [comment]
Actually, the problem is in your patch... I may need to alter the object to make things easier

**Comment by porres** [comment]
just so you know what's happening...

when you hit "export", it sends a big list and route will get it and send the rest of the list forward.

[sel] has two inlets, the second one is for resetting the argument. When select gets a list, it will update both inlets. So... you're changing the argument!

one way to deal with this is setting two arguments to [sel] (like [select 1 0]). This will remove the 2nd inlet and avoid this issue...

**Comment by porres** [comment]
but anyway, I'm thinking of adding an "export" selector when you send it an export message, because then [route] wouldn't route the list...

**Comment by porres** [comment]
here's a way to manage this on your patch 

[drumseqtest2-fix.pd.zip](https://github.com/porres/pd-else/files/4815200/drumseqtest2-fix.pd.zip)

**Comment by smomid** [comment]
Oh Shit. Ok that makes sense. Ok, this new patch works. 

This drum.seq object is really awesome. Thanks for creating it. 

Nick

**Comment by porres** [comment]
wellcome, anyway, heads up, I changed the object now! 

in the next release an export message will send "export" followed by a list, which will make things easier to route and deal with ;) see https://github.com/porres/pd-else/commit/eb88b586b2a28cfa82a85bc4e383c3efbd18c1f6

if you want, you can already start using the new abstraction instead!

**Comment by smomid** [comment]
AWESOME!!!

thanks man.
