### ISSUE TITLE
opening specific directory with DiR

### ISSUE THREAD

**Issue by Cryolipis** [porres/pd-else#721]
It' s possible it' s only a misunderstanding of what DIR does
in this case sorry!

[folderopeningproblem.txt](https://github.com/porres/pd-else/files/4947288/folderopeningproblem.txt)

**Comment by porres** [comment]
In mac, it opens the chosen directory, I'll test in Linux and Windows.

**Comment by porres** [comment]
Ok, this never really worked in windows, but I fixed it now, and I'll release an update right away...

**Comment by porres** [comment]
there's already a new release, please test! https://github.com/porres/pd-else/releases/tag/v1.0-beta29

**Comment by Cryolipis** [comment]
It works !
thanks!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
