### ISSUE TITLE
Else objects not opening correctly in Pd .51.1

### ISSUE THREAD

**Issue by smomid** [porres/pd-else#749]
Hi, 
I am setting up a new Raspberry Pi computer, with 8 gig RAM. 
I just installed Pd .51.1

When I try and open an object or help file from ELSE, for example, if I try to open the helpfile for bi.saw2~ I get these messages: 

else/out~  couldn't create
else/saw2~  couldn't create
else/bl.saw2~ 400 couldn't create
else/play.file~  couldn't create

If I actually go into the help file and change else/out~ to out~ then then object is fine. 

When I try and open drum.seq I get so many messages of objects not opening that I can't even use the object. 

I don't think I had this issue on my last Pi with Pd .51.0 

Any idea of what to do? 

thanks

**Comment by porres** [comment]
hi, what version of ELSE do you have? And which binary exactly are you using?

**Comment by porres** [comment]
> If I actually go into the help file and change else/out~ to out~ then then object is fine.

where do you have the 'else' folder installed? this is the instructions on how to download/install https://github.com/porres/pd-else#downloading-else are you following it?

**Comment by smomid** [comment]
OK I read the instructions. I made my own externals folder and installed it into that, maybe that’s the problem. I’ll try installing it into the folder in the instructions. 

I downloaded the most recent version of ELSE, from Dekken. I think it was released like August 18 or 20.

**Comment by porres** [comment]
> OK I read the instructions. I made my own externals folder and installed it into that, maybe that’s the problem

certainly that's it

**Comment by porres** [comment]
> I made my own externals folder

if you wanna do that, you have to put it in "Preferences Path"
