### ISSUE TITLE
spectrograph~ without hann~

### ISSUE THREAD

**Issue by jlquispec** [porres/pd-else#788]
"The ELSE library offers [spectrograph~], which is an abstraction that plots spectral amplitude information based on what **we've seen so far**. You can set its size and how to display the amplitude (linear or dB) and frequency (linear or log)"

**Comment by jlquispec** [comment]
![image](https://user-images.githubusercontent.com/53123770/93949885-80757080-fd07-11ea-890e-755d55509dce.png)

**Comment by porres** [comment]
As it is, your issue is unclear, but I suspect you're requesting me to include a hann window, right?

**Comment by jlquispec** [comment]
Yes, inside of Live Electronics Tutorial - 27-FFT-IFFT - 2.FFT, some concepts are exposed and I guess specgtrograph~ should use these.

"The ELSE library offers [spectrograph~], which is an abstraction that plots spectral amplitude information **based on what we've seen so far**".

**Comment by porres** [comment]
>  I guess specgtrograph~ should use these.

it could, but doesn't really have to, I'll think about it - it could be an option

**Comment by jlquispec** [comment]
Yes, I think it could be more methodological in the tutorial because that is one of the last examples
