### ISSUE TITLE
Some objects missed in deken version of else-v1.0beta1-(Darwin-i386-32)(Darwin-x86_64-32)

### ISSUE THREAD

**Issue by emviveros** [porres/pd-else#79]
MISSED Objects
[else/imp~]
[else/imp~]
[else/impulse2~]
[else/pimp~]
[else/pulse~]
[else/notch~]
[else/cosine~]
[else/sine~]
[else/parabolic~]
[else/sawtooth~]
[else/sawtooth2~]
[else/vsaw~]
[else/symbol2]
[else/triangular~]

**Comment by porres** [comment]
fixed
