### ISSUE TITLE
tabplayer~ add bang method / speed / jump/ flags / revise and more

### ISSUE THREAD

**Issue by porres** [porres/pd-else#792]
- input not in ms but in samples
- add all sorts of interpolation

**Comment by emviveros** [comment]
O bang de fim do tabplayer~ cospe montes de bangs quando acionado por mensagem `start <f, f>`

**Comment by porres** [comment]
kd o patch?

**Comment by emviveros** [comment]
Tá aqui..! Pd 0.51-2 ELSE beta 32
[tabplayer_outbang_bug.pd.zip](https://github.com/porres/pd-else/files/5449579/tabplayer_outbang_bug.pd.zip)

**Comment by porres** [comment]
ok, quando termina de tocar manda uma caralhada de bang, saquei

**Comment by porres** [comment]
arrumei esse bug @emviveros
