### ISSUE TITLE
[display]

### ISSUE THREAD

**Issue by AydinHumphries** [porres/pd-else#793]
**description**

when I put display into parent-on-graph and try to recreate that patch through dynamic patching, it will go dark and not display any floats sent there until I save and reload the patch. as an example, here is the code that let's me create a graph dynamically:

![image](https://user-images.githubusercontent.com/48067862/94289586-d1c47080-ff50-11ea-8ae0-88aff0f273fd.png)

this is what the display looks like on the graph:

![image](https://user-images.githubusercontent.com/48067862/94289638-e7d23100-ff50-11ea-8247-7c85352fc32d.png)

as you can see, it's gone all dark and whereas I will be able to enter symbols or floats in the display when it functions as normal or I save and reload, the first time I create the graph, it will not.

and how it looks when I save/reload:

![image](https://user-images.githubusercontent.com/48067862/94289855-439cba00-ff51-11ea-9454-8e9d061720ce.png)

**steps to recreate:**

create a graph-on-parent, put a number box and hook it up to a display inside the graph. save your patch as "test.pd". create a new patch in the same folder "test2.pd", then create code:

[;
pd-test2.pd obj 100 100 test;{

click on the message, then see if numbers you enter in the number atom send through to the display. if not, save and exit pd - then see if it works on reloading the file.

**OS:**

windows 10, lenovo laptop

**urgency:**

medium - if you want to plug numbers into a display on graph you've already created before loading a patch before performance, you're fine. if you want to plug numbers (or possibly this could be problematic for symbols too) into a display on graph you want to dynamically patch _during_ a performance, this won't work.

**Comment by porres** [comment]
please try to provide the minimal patch that shows the error with the steps as comments, it's really helpful. You can upload pd patches as zip files here on github.

**Comment by AydinHumphries** [comment]
> please try to provide the minimal patch that shows the error with the steps as comments, it's really helpful. You can upload pd patches as zip files here on github.

ok:

https://github.com/AydinHumphries/displayglitch/

**Comment by porres** [comment]
ok, this is a vanilla issue, where patches with [loadbang] do not trigger a bang when created via dynamic patching. I'll post the issue over there.

**Comment by AydinHumphries** [comment]
> ok, this is a vanilla issue, where patches with [loadbang] do not trigger a bang when created via dynamic patching. I'll post the issue over there.

thanks, I have noted quite a few issues with dynamic patching. the one I mentioned in 1149 - where sending objects to the parent patch only work inconsistently - I am quite positive that is a real thing in vanilla too. I just haven't been able to screenshot an instance yet where it won't let you do hat

**Comment by porres** [comment]
IOhannes closed the issue I opened in Vanilla and gave me an alternative, so now with https://github.com/porres/pd-cyclone/commit/0f3906267bb14c0935ccf53393838b0ef8be7f52

you won't have that issue anymore - if you don't want to wait for the next release, you can already download the fixed else/display abstraction and use it

**Comment by porres** [comment]
> so now with porres/pd-cyclone@0f39062

damn, I referred to the wrong commit

**Comment by porres** [comment]
ok, now I got it https://github.com/porres/pd-else/commit/c670dadaa2d40b199e8f6c12521f9599328b24e1

**Comment by AydinHumphries** [comment]
> ok, now I got it [c670dad](https://github.com/porres/pd-else/commit/c670dadaa2d40b199e8f6c12521f9599328b24e1)

thanks.

do I have to download from this link? does it add to the else path automatically or is there a special location it has to be accessed on windows 10?

**Comment by porres** [comment]
you can download the source code as it is and get the [display] object from it.

I should have a new release in a couple of weeks anyway

**Comment by AydinHumphries** [comment]
> you can download the source code as it is and get the [display] object from it.
> 
> I should have a new release in a couple of weeks anyway

sorry, I don't understand: do you mean re-download pd-else itself or straight from the link you shared itself? if the latter I couldn't find the link. I know the updated library will be available soon, I am just keen to work my patch with display functioning as I intend it to.

**Comment by porres** [comment]
just get the source code from here https://github.com/porres/pd-else , click on the "code" button and download as a zip

we're in the repository, it has all the latest changes that are not into a new release yet
