### ISSUE TITLE
"$4: argument out of range"

### ISSUE THREAD

**Issue by AydinHumphries** [porres/pd-else#814]
my patch doesn't use any $4 arguments, so this was how I knew it was to do with an externals library. I searched the patch for $4 and found this:

![image](https://user-images.githubusercontent.com/48067862/95488741-d09e3500-098d-11eb-9861-fd8a8607dfab.png)

I think it is to do with else but I cannot be more precise than that. I haven't looked up this particular external either - I'm only using else/display in my patch so I don't see how this error occurred. I have set up [declare -path else] as my method for installing else so maybe it's to do with that - when I should have been using [declare -lib else] but it hasn't been an issue with that, also the issue happens in a part of the patch I don't even use display. also replaced the display file with one from a new github repo, due to the issue with loadbang and vanilla library not launching patches with loadbang dynamically that I mentioned a few weeks ago.

**Comment by porres** [comment]
you have to provide me with a minimal patch with an objective and verifiable/reproducible issue - sorry, I can't work with this

> I have set up [declare -path else] as my method for installing else so maybe it's to do with that 

no, it's fine

**Comment by AydinHumphries** [comment]
> you have to provide me with a minimal patch with an objective and verifiable/reproducible issue - sorry, I can't work with this

sorry for posting this issue, the problem was with something I had not noticed in my patch in the end, not else. the fact the vanilla search function takes me through else externals is confusing, since I often use that to debug the patch.
