### ISSUE TITLE
button issues

### ISSUE THREAD

**Issue by emviveros** [porres/pd-else#823]
Every time [button] object have background modified when out the patch pd popup save patch message.

Another issue is every time I open [button] help pd return error message:
```
(Tcl) NOME DE COMANDO INVÁLIDO: invalid command name ".x7fbcd61400c0.c"
    while executing
".x7fbcd61400c0.c itemconfigure 7fbcd617a7b0BASE -fill #0000ff"
    ("uplevel" body line 7)
    invoked from within
"uplevel #0 $docmds
```

[ELSEbutton.pd.zip](https://github.com/porres/pd-else/files/5434103/ELSEbutton.pd.zip)

**Comment by porres** [comment]
cara, pode fazer os reports em português :)

**Comment by porres** [comment]
eu nao entendi nada e o teu exemplo me parece funcionar, explica

**Comment by emviveros** [comment]
Ufa...

Então.. coloca o botão pra piscar e depois pode parar. Na hora de fechar o patch, o Pd pergunta se pode salvar.

Tenho um patch com 16 desses pads, e toda vez que mudo a cor deles, o pd me pede pra salvar dando umas engasgadas por vezes travando.

Tem como desativar isso?

**Comment by porres** [comment]
tem, isso tá na ista na real :)  https://github.com/porres/pd-else/issues/806

mas sobre o erro de tcl/tk... nao to reproduzindo

**Comment by emviveros** [comment]
> tem, isso tá na ista na real :) #806

Massa!

**Comment by porres** [comment]
> mas sobre o erro de tcl/tk... nao to reproduzindo

e aí?

**Comment by emviveros** [comment]
Cara.. Aqui é só chamar o help... Fiz esse teste com o Pd limpo..
![else_button_errorTCL](https://user-images.githubusercontent.com/3089536/97123434-97deb980-170a-11eb-963f-67cdac2c6463.gif)

**Comment by porres** [comment]
então, doesn't happen here...

**Comment by porres** [comment]
manda o teu patch

**Comment by porres** [comment]
ah, já o tenho...

**Comment by porres** [comment]
> ah, já o tenho...

e nothing happens

**Comment by porres** [comment]
tá usando que pd, que OS, que versão da ELSE?

abre um novo issue?

**Comment by emviveros** [comment]
Acho que não precisa abrir um novo issue ñ.. Mas to usando o Pd 0.51-2 ELSE beta 32 OSx 10.13.6 High Sierra

**Comment by emviveros** [comment]
Nem precisa.. Agora que vi q estava usando ELSE beta31, instalei o beta32 e não tem mais erro! RESOLVIDO! 👍

**Comment by porres** [comment]
desenvolvedor foda é aquele que resolve os bug antes das pessoas reclamarem dele :)

**Comment by emviveros** [comment]
> Every time `[button]` object have background modified when out the patch pd popup save patch message.

Ví a existência de uma tal mensagem `[dirty 0(` para o canvas que pode oferecer uma solução pra esse problema de usar o button como sinalização tb enquanto não tem implementação de um método que permita alterar a cor de setar `[set 1(` `[set 0(` o estado do `[button]` ou mesmo acionar remotamente.

**Comment by porres** [comment]
tem método que permite alterar a cor agora...

**Comment by porres** [comment]
vc só compilar? não instala pra usar e nem vê o changelog? :)

**Comment by emviveros** [comment]
Malz... Mas tava de olho no help apenas....
