### ISSUE TITLE
[readsf~] and [makefilename] generates processing overhead 

### ISSUE THREAD

**Issue by gui-fiorentini** [porres/pd-else#830]
I'm doing a sampler here with [readsf ~] and [makefilename]. If there is no file with the name generated by the patch, the pd looks for it in looping and consumes all the processing until it locks up. I would like to know if there is any way to make a security mechanism, in case when you can't find a certain name, it does not enter this loop.

Thanks!

**Comment by porres** [comment]
send me a test patch please so I can reproduce

**Comment by porres** [comment]
tem a ver com a lib não :)
