### ISSUE TITLE
Questões no modo loop do pvoc.player~

### ISSUE THREAD

**Issue by emviveros** [porres/pd-else#850]
Oi Porres seu lindo!

Segue um patch de teste para confirmar uma reinicialização do sample com o loop em andamento. No patch, aqui, no início da quarta vez que o sample é loopado, pvoc.player~ envia um endbang e reinicia a reprodução.
[bug_test_1.pd.zip](https://github.com/porres/pd-else/files/5573600/bug_test_1.pd.zip)

Outro ponto é se não seria interessante a cada fim de loop o pvoc.player enviar um bang de fim sinalizando que o sample completo foi reproduzido, assim possibilitando uma automação quantas n vezes será reproduzido o sample em loop?

**Comment by porres** [comment]
arrumei uma caralhada de pobrema :) como é abstação, pode baixar e testar ;)
