### ISSUE TITLE
add mtx.ctl dump method

### ISSUE THREAD

**Issue by porres** [porres/pd-else#875]

**Comment by umlaeute** [comment]
yes. and vice versa.

ideally, the format would be compatible with iemmatrix' messages

~~~
[mtx <rows> <cols> a[0][0] a[0][1] ... a[rows-1]a[cols-2] a[rows-1]a[cols-1](
~~~

**Comment by porres** [comment]
> yes. and vice versa.

what exactly? :) just made an actual title description ;) but will check your comment too

**Comment by umlaeute** [comment]
i'm asking for a method to dump the entire state of `[mtx.ctl]`, and for a single message to restore the state of the object (that's the "vice-versa")

the original title "mtx.ctl dump" suggested that this was a feature-request for a general "dump" message (which is what i responded to).
now that you've changed the title to something that is DSP-related, my reply no longer makes sense.

**Comment by porres** [comment]
Geez I got confused, I have an issue with [mtx~], anyway, will do that ;)

**Comment by porres** [comment]
new issue for this and more https://github.com/porres/pd-else/issues/1043
