### ISSUE TITLE
args was funny again (grainsynth~ / autotune2)

### ISSUE THREAD

**Issue by porres** [porres/pd-else#891]

**Comment by dfkettle** [comment]
[grainsynth] used [autotune], not [autotune2]. It's [autotune] that contains an [args] object.

**Comment by porres** [comment]
> [grainsynth] used [autotune], not [autotune2]. It's [autotune] that contains an [args] object.

I know, but this is why I changed [autotune2] to use [pdcontrol], and in the end I kept grain.synth as it is, anyway, the issue is covered here ;)

**Comment by porres** [comment]
another example of the crash [eqdiv.pd.zip](https://github.com/porres/pd-else/files/6503091/eqdiv.pd.zip)

**Comment by porres** [comment]
closing in favor of this --> https://github.com/porres/pd-else/issues/1249 I guess it will now work when I fix it ;)
