### ISSUE TITLE
Typo in the Tutorial

### ISSUE THREAD

**Issue by bazilmuzik** [porres/pd-else#907]
There's a little typo in 02-Intervals-Tuning, 4.Just.Interval.vs.Tempered.pd of the tutorial : it's written [fract2ratio] but the object is [frac2ratio]

**Comment by porres** [comment]
this is ok, but note there's a repo for the tutorial itself for next time: https://github.com/porres/Live-Electronics-Tutorial/issues

**Comment by bazilmuzik** [comment]
Oh, ok ! Sorry for the inconvenience, I'll write issues to the
corresponding repo next time !
