### ISSUE TITLE
else/graph~ hangs pure data

### ISSUE THREAD

**Issue by muziker** [porres/pd-else#915]
In trying to change the graph output to have a Y range of 0 to 100, i found that doing this using properties->dialog box didn't work. The gui would still be from -1 to 1 but the properties would show a range of 0 to 100. Using open, and doing the same on the graph there yielded the same issue where the gui would still be from -1 to 1. Using open yet again on this graph, and doing properties->dialogbox, the pd main window would show  

`Tcl) UNHANDLED ERROR: wrong # args: should be "pdtk_array_dialog mytoplevel name size flags newone"
    while executing`

Eventually the entire gui hangs and the audio is no longer responsive to changes in the gui.

**Comment by porres** [comment]
please provide a minimal patch as an example so I can try to reproduce and debug

**Comment by muziker** [comment]
It's a process issue though. 

1. Open a new patch, put a [else/graph~ ]
2. start changing the Y range  
3. observe the actual drawn output doesn't change,
4. open the graph ( B ) 
5. change Y range of B
6. observe the drawn output doesn't change
7. unhandled pdtk_array_dialog in main pd console window 

It's probably something to do with tcl/tk and pd rather than the else library itself.

**Comment by porres** [comment]
sorry, I can't get it, maybe a video helps, but sometimes even processes can be clear if there are instructions in a patch

**Comment by porres** [comment]
ping

**Comment by muziker** [comment]
closed ... read the help file. The range can only be altered using the [range ( command and not any other method
