### ISSUE TITLE
Typo in 2.Transfer.Function-Poles.zeros [pd IIR]

### ISSUE THREAD

**Issue by muziker** [porres/pd-else#916]
The transfer function written in this file should be 

Y(z)(1 - a * z^-1 ) in the denominator

**Comment by porres** [comment]
hi, you're gonna have to be more specific where the typo is and why

**Comment by porres** [comment]
oh, and you opened this in the wrong repository :) please open a new one here https://github.com/porres/Live-Electronics-Tutorial
