### ISSUE TITLE
Cannot open 'All_objects.pd'

### ISSUE THREAD

**Issue by dfkettle** [porres/pd-else#960]
When I try to open 'All_objects.pd', Pd just crashes with no error message to indicate what the problem might be. I ran Pd with '-verbose' and captured the output (see attached file), but I don't know if it contains anything useful. I'm running on Windows 7, SP 1 (64-bit) under Pd v0.51.3 (64-bit).

[error.txt](https://github.com/porres/pd-else/files/6017624/error.txt)

**Comment by porres** [comment]
are you trying else 1.0 beta 36?

this test patch loads fine here on my, we'd have to load each object, one by one, to see which one blows up pd in windows :(

**Comment by dfkettle** [comment]
Yes, that's the latest version available in Deken for Windows. I'll see if I can narrow it down.

**Comment by dfkettle** [comment]
What does the "gotcha" message mean? I see that in the console log I attached, but I don't know if it's anything to be concerned about.

**Comment by dfkettle** [comment]
If I try to open the help files for [grain.live~], [grain.sampler~] or [grain.synth~] then Pd crashesl. I can open [grain.live~] and [grain.sampler~], though, but not [grain.synth~].

**Comment by porres** [comment]
so you cannot create [grain.synth~] that Pd crashes, right?

if so, can we close this issue and reopen as a more proper one?

**Comment by dfkettle** [comment]
That's correct. The two help files,  [grain.live~-help] and [grain.sampler~-help], contain a [grain.synth~] object, which is probably why I can't open them either. So it's just [grain.synth~] that crashes Pd.

**Comment by porres** [comment]
can you then open a new issue saying  [grain.synth~] crashes Pd? You can reference to this one, but please provide again your system information and all
