### ISSUE TITLE
tabwriter~ inconsistent interface with tabplayer~

### ISSUE THREAD

**Issue by muziker** [porres/pd-else#961]
Version: 1.0.0 beta-33

In tabwriter~, the start & end settings are in samples, and not in ms. tabplayer~ is in ms. The units are inconsistent with each other. also the help file for tabwriter~ has specifications in ms.

**Comment by porres** [comment]
you mean tabplay~ or else/tabplayer~?

**Comment by muziker** [comment]
Sorry i meant else/tabplayer~ . A slight hiccup there
