### ISSUE TITLE
stutter~

### ISSUE THREAD

**Issue by porres** [porres/pd-else#964]

**Comment by muziker** [comment]
From the previous threads on tabplayer and tabwriter. 

To achieve a stutter effect, the read head must be, for example, 120 ms behind the write head, and looping from the read start point to where the write head stopped. In the code, it starts the read head some time, say 120 ms, after the write head has started writing, and the heads wrap automatically at the end of the circular buffer. To know where the write head is at the buffer level, tabwrite must output an indication of where it is on the buffer. Then from there, the start loop point of where the read head should be can be calculated. The end loop point of the read head is where the write head has stopped. 

There's a work around to all this, by setting a [timer ] at tabwriter start and to get the time elapsed when stutter is engaged and tabwriter is stopped.
