### ISSUE TITLE
else/tabplayer~ does not output a bang when play has ended when using line~

### ISSUE THREAD

**Issue by muziker** [porres/pd-else#969]
else version: 1.0.-0 beta-33

When using a signal to control the speed of else/tabplayer~, the tabplayer does not output a bang when it has ended. Using messages, tabplayer~ outputs a bang when it has finished playing.

**Comment by porres** [comment]
please test current version (beta 36 at the time of this writing) when posting bugs - and provide a test patch

**Comment by muziker** [comment]
On the 1.0.-0 beta-33, [ 0, 100 200 ( ->[line ~ ] --->[*~ <sample length in ms>] --> [tabplayer~ ], once line has ended, tabplayer does not send out a bang. It might be due to signals being always on, but the behaviour isn't consistent with using [ start <start> <end> ( directly

**Comment by muziker** [comment]
The same thing happens with beta-36.

**Comment by porres** [comment]
> It might be due to signals being always on

it is

**Comment by porres** [comment]
if you want to have a trigger on this case, I suggest you to use the signal input and analyze it so you can have either a signal trigger (an impulse) or an actual bang with something like [else/trig2bang~] 

it's just complicated to have it output a bang with a signal input and if you have a control from outside the object, you can predict or analyze if it's over or not
