### ISSUE TITLE
else/tabplayer~ should not bang output at the end of buffer when on loop

### ISSUE THREAD

**Issue by muziker** [porres/pd-else#971]
beta-36 else/tabplayer~ has a different behaviour to beta-33. Beta-33 tabplayer~ does not output a bang when loop is engaged, but beta-36 outputs a bang at the end of the buffer no matter if loop is enagaged or not. The semantics of this seems a little strange, since the player hasn't finished playing yet. In a looping sampler interface, i've based some of its button behaviours on tabplayer not emitting a [bang ] when on loop. I've worked around the newer tabplayer, but can this behaviour be reinstated?

**Comment by porres** [comment]
This is not a bug but actually a feature request so one can use this to loop "x" times and then stop or do something else
