### ISSUE TITLE
Pd crashes when opening patch with [grain.synth~] object

### ISSUE THREAD

**Issue by dfkettle** [porres/pd-else#973]
When I try to open a patch with a [grain.synth~] object, Pd just crashes with no error message to indicate what the problem might be. For example, opening the help patch 'grain.synth~-help' causes Pd to crash.

If I try to add a [grain.synth~] object to an open patch, Pd also crashes. 

I'm running on Windows 7, SP 1 (64-bit) under Pd v0.51.3 (64-bit).

**Comment by porres** [comment]
does it blow up Pd if the DSP is off?

@Lucarda can you help me on this one please?

it works really fine her on my macos :/

**Comment by dfkettle** [comment]
Yes, when adding to an open patch it makes no difference whether DSP is on or not. When opening an existing patch (like the help patch), it crashes before you even have a chance to turn DSP on, or do anything.

**Comment by dfkettle** [comment]
Well, I could try, but I've never compiled any externals for Pd (I do have some experience in C/C++, though). However, I'd need some clear instructions (which compiler to use on Windows, what compile options to use, etc.). Did you make a change to that particular object that might fix the problem? I'm thinking it may not be a Windows issue, but a compile option related to optimization that isn't supported by my CPU (an AMD Phenom II X4 810). Here's some technical info on it, maybe you could ask whoever compiled the Windows version the last time what options were used.

https://www.cpu-world.com/CPUs/K10/AMD-Phenom%20II%20X4%20810%20-%20HDX810WFK4FGI%20(HDX810WFGIBOX).html

**Comment by Lucarda** [comment]
I couldn't replicate the crash.

Pd-0.51.4(64bits) Windows10.

@dfkettle these are the cpu flags as set by pd-lib-builder: `-march=core2 -msse -msse2 -msse3 -mfpmath=sse` when compiling for Windows(64bit).


https://github.com/pure-data/pd-lib-builder/blob/e6cff665a3a30a967c72c382c6fe92bcdedd7b44/Makefile.pdlibbuilder#L580

**Comment by porres** [comment]
well, grain.synth is an abstraction, it's hard to see what might be causing it, because it's the same objects basically that are also used in the other grain like objects (live and sampler). I made an attempt, maybe @Lucarda can provide new 64 bit builds so you can test it. In the readme we explain how to compile, it should be straightforward with pd-lib-builder

**Comment by Lucarda** [comment]
@dfkettle I had compiled. If you want to test download from [here](https://nc.nubegris.com.ar/index.php/s/dTpmiPTgsonDBBB)

**Comment by dfkettle** [comment]
> @dfkettle I had compiled. If you want to test download from [here](https://nc.nubegris.com.ar/index.php/s/dTpmiPTgsonDBBB)

@Lucarda Same result.

**Comment by dfkettle** [comment]
> well, grain.synth is an abstraction, it's hard to see what might be causing it, because it's the same objects basically that are also used in the other grain like objects (live and sampler). I made an attempt, maybe @Lucarda can provide new 64 bit builds so you can test it. In the readme we explain how to compile, it should be straightforward with pd-lib-builder

@porres I see your point. So on a hunch, I removed the line in [grain.synth~] that clones [grain.synth.grain] and the patch opens. Then I created a patch (in a text editor) with just the following two lines:

#N canvas 812 194 450 300 12;
#X obj 48 103 clone else/grain.synth.grain 256;

If I try to open it in Pd, or if I double-click on the file, Pd crashes. It seems as if the clone operation is causing the crash, although I know that [clone] is used elsewhere and it works.  However, this is the only patch in Else that clones an instance of [grain.synth.grain]. Still hard to understand, as you say, but then crashes are usually hard to understand, until you figure out what's causing the crash.

**Comment by porres** [comment]
> It seems as if the clone operation is causing the crash

why? can you open [grain.synth.grain] by itself outside clone?

**Comment by dfkettle** [comment]
> > It seems as if the clone operation is causing the crash
> 
> why? can you open [grain.synth.grain] by itself outside clone?

Yes.

**Comment by porres** [comment]
wow, that's really fucked up... so, one of the objects (most likely from ELSE) used in the [grain.synth.grain] abstraction crashes Pd only when used in clone and only when used in Windows 7 (not 8 or 10) and perhaps only on the 64 bit version. How is that?

And just by cloning it, with the DSP off and all, you get "BBBOOOOMMMM"... very very weird.

Well, if we want to narrow it down a bit more we need to remove suspicious objects and see if it opens. Since we have two very similar abstractions that open just fine, this one uses just one object that the others don't (I think), and that'd be [wavetable~]. 

Since you can open the abstraction, can you inutilize this object by giving it a wrong name and test?

another question, does the number of instances in clone affect the crash? What if you clone the abstraction just once?

**Comment by dfkettle** [comment]
> wow, that's really fucked up... so, one of the objects (most likely from ELSE) used in the [grain.synth.grain] abstraction crashes Pd only when used in clone and only when used in Windows 7 (not 8 or 10) and perhaps only on the 64 bit version. How is that?

Like I said, I don't think it's a Windows issue, it more likely  has something to do with my hardware, even though it does work under Ubuntu Linux on the same computer. It's a relatively old CPU. Do you know anyone that's still on Windows 7 who could test it?

> Well, if we want to narrow it down a bit more we need to remove suspicious objects and see if it opens. Since we have two very similar abstractions that open just fine, this one uses just one object that the others don't (I think), and that'd be [wavetable~].

It still crashes after renaming [wavetable~] to [xwavetable~]. But there are a number of other abstractions and sub-patches, I can try renaming them one by one and see.

> another question, does the number of instances in clone affect the crash? What if you clone the abstraction just once?

It's only being cloned once in [grain.synth~], and no other objects are being cloned. Similarly, it's only being cloned once in the two-line patch I posted above: 

#N canvas 812 194 450 300 12;
#X obj 48 103 clone else/grain.synth.grain 256;

![Image1](https://user-images.githubusercontent.com/8409615/110641133-9f65a300-817f-11eb-841d-fa612cea5133.png)

**Comment by dfkettle** [comment]
Sorry, I misunderstood. You mean change the argument to [clone] from 256 to 1?

**Comment by porres** [comment]
> You mean change the argument to [clone] from 256 to 1?

yeah

**Comment by porres** [comment]
> It still crashes after renaming [wavetable~] to [xwavetable~]. But there are a number of other abstractions and sub-patches, I can try renaming them one by one and see.

but [wavetable~] is the only object that only this object uses (I think), it's gonna be even weirder if some other object crashes in this patch but not the others :)

**Comment by dfkettle** [comment]
You're right, my bare-bones test patch opens with an argument of 1.

#N canvas 812 194 450 300 12;
#X obj 48 103 clone else/grain.synth.grain 1;

Does that tell us anything?

**Comment by dfkettle** [comment]
It also opens with an argument of 2, but no higher.

**Comment by dfkettle** [comment]
Like this? It seems to work.

![Image3](https://user-images.githubusercontent.com/8409615/110643722-67139400-8182-11eb-8a60-da91b57061ef.png)
![Image2](https://user-images.githubusercontent.com/8409615/110643727-67ac2a80-8182-11eb-9741-a62ba063ca7c.png)

**Comment by porres** [comment]
yeah, wavetable is basically the only odd one out...

I see [autotune] is also unique here, as grain.sampler.grain has [autotune2] instead, but these are practically the same, it wouldn't make sense. We can try it as a last ditch effort

**Comment by dfkettle** [comment]
This is how [autotune] is declared in the file:

#X obj 92 424 autotune -bypass, f 8;

What does "-bypass" do? I don't see it mentioned in the help files for either [autotune] or [autotune2]. Likewise, what does "f 8" do? And should there be a comma after "-bypass"?

What if I just changed it to [autotune2]?

**Comment by dfkettle** [comment]
I changed it to [autotune2] and now the clone works.

#X obj 92 424 autotune2 -bypass, f 8;

What is the difference between [autotune] and [autotune2]?

![Image1](https://user-images.githubusercontent.com/8409615/110646615-0df92f80-8185-11eb-9f78-165f74c2df05.png)

**Comment by porres** [comment]
> What is the difference between [autotune] and [autotune2]?

we have to see the help file for that :) 

in the abstraction itself, I have to inspect what the difference is.

We should probably reboot the issue once again. Now, it's some object in [autotune] and not in [autotune2] inside clone more than twice that gives us problems.

so, as it is, can you try cloning an abstraction just with [autotune]?

**Comment by porres** [comment]
> What is the difference between [autotune] and [autotune2]?

virtually none I can say, check for yourself, the patches are basically the same, this nonsense has gone too far :)

**Comment by dfkettle** [comment]
> virtually none I can say, check for yourself, the patches are basically the same, this nonsense has gone too far :)

What nonsense? If you want to close the issue, go ahead. Maybe I'm the only one having the problem, but I was just trying to help.

**Comment by porres** [comment]
> What nonsense?

I'm mad at the bug, not you :) this bug is nonsensical and it's gotta be the weirdest one ever, haha

I wanna fix it anyway, but it seems we've hit a wall, I can't tell what may be causing this if it's the difference between autotune and autotune2

can you test autotune and autotune2 with [clone]?

**Comment by dfkettle** [comment]
Sure, but it will have to wait, I have some other things I have to do today. I wouldn't bother creating another issue until we know that [autotune] is really causing the problem.

**Comment by dfkettle** [comment]
Well, it appears that [autotune2] can be cloned more than 2 times, but [autotune] can't (Pd crashes). Like you said, they're almost the same, except that [autotune] has an extra flag, "-base". I'm not really sure why you even have 2 different versions, if [autotune] does everything that [autotune2] does, plus the extra functionality provided by the "-base" flag. But that's not relevant to the problem, I guess.

I did notice some differences in the sub-patch [init], which I don't really understand, but I don't know why they'd cause a problem. The [init] sub-patch for [autotune2] contains [pdcontrol] and [break] objects, whereas the [init] sub-patch for [autotune] contains an [args] object instead.

![autotune2-init](https://user-images.githubusercontent.com/8409615/110825498-1bd0b280-8262-11eb-8302-d8462cab7568.png)
![autotune-init](https://user-images.githubusercontent.com/8409615/110825502-1c694900-8262-11eb-843b-3f986f773b53.png)

**Comment by porres** [comment]
> whereas the [init] sub-patch for [autotune] contains an [args] object instead.

well, actually, [args] has been causing some weird crashes for me too, so that can be it. For this case, it's easily replaceble by [pdcontrol]

**Comment by dfkettle** [comment]
But [args] is used in a lot of places, isn't it?

**Comment by porres** [comment]
well, actually... and really actually... I mean actually actually, more actually than before, I have already an issue that mentions this:

https://github.com/porres/pd-else/issues/891

but then, it stopped giving me the error and as you can see, this is really hard to replicate :/ 

so, thanks for this, I'll just close this issue and focus on the other duplicate one. And I'll just replace [args] for pdcontrol as a quick solution

**Comment by dfkettle** [comment]
Do you want to send me the modified version of [autotune] so I can test it?

**Comment by porres** [comment]
> But [args] is used in a lot of places, isn't it?

oh yeah, everywhere!

**Comment by porres** [comment]
> Do you want to send me the modified version of [autotune] so I can test it?

that's be great

**Comment by porres** [comment]
I already changed it anyway

**Comment by dfkettle** [comment]
I tried the new version of [autotune] (without the [args] object) and Pd no longer crashes when I try to clone more than 2 copies.

Thanks.

**Comment by dfkettle** [comment]
I tried the new version of [autotune] (without the [args] object) and Pd no longer crashes when I try to clone more than 2 copies.

Thanks.
